import crafttweaker.item.IItemStack;
import crafttweaker.game.IGame;

mods.jei.JEI.addDescription(<quark:chute>, "When items are pushed into a Chute, the items get dropped out of the exact center of the bottom.");
mods.jei.JEI.addDescription(<minecraft:dispenser>, "Dispensers can plant seeds, place blocks, and insert Records into Jukeboxes.");
mods.jei.JEI.addDescription(<minecraft:sticky_piston>, "Sticky Pistons can now push Tile Entities like Chests and Furnaces (except Mob Spawners).");
mods.jei.JEI.addDescription(<quark:sturdy_stone>, "Sturdy Stone can't be pushed by Pistons.");
mods.jei.JEI.addDescription(<quark:gold_button>, "When pressed, emits a 2 tick long signal.");
mods.jei.JEI.addDescription(<quark:iron_button>, "When pressed, emits a 5 second signal.");
mods.jei.JEI.addDescription(<quark:obsidian_pressure_plate>, "Only triggers when used by a Player.");
mods.jei.JEI.addDescription(<quark:iron_rod>, "Breaks blocks when pushed into them with a Piston");
mods.jei.JEI.addDescription(<quark:redstone_randomizer>, "When it gets a signal, it randomly gives a signal to either its left or right side.");
mods.jei.JEI.addDescription(<quark:rain_detector>, "Provides a signal when it's being rained on.", "Can be inverted by right clicking.");
mods.jei.JEI.addDescription(<quark:trowel>, "When right clicked, places a random block from your hotbar.");
mods.jei.JEI.addDescription(<quark:glass_item_frame>, "Disappears when an item is placed in it, so you can only see the item.");
mods.jei.JEI.addDescription(<quark:iron_ladder>, "Iron Ladders can stand freely without a block behind them, as long as the top block does.");
mods.jei.JEI.addDescription(<minecraft:lead>, "Leads can now connect two Fences, instead of just a Fence and a Mob.");
mods.jei.JEI.addDescription(<quark:candle>, "Comes in all 16 colors.", "If there is no block underneath, it will fall like sand.", "Candles are equal to half a Bookshelf for Enchanting Tables.");
mods.jei.JEI.addDescription(<quark:witch_hat>, "Highly enchantable, and provides 50% resistance to Potions of Harming.");
mods.jei.JEI.addDescription(<minecraft:boat>, "Right click a Chest on a Boat to place it on the Boat. While in the Boat, opening your inventory will also open the Chest's inventory.");
mods.jei.JEI.addDescription(<minecraft:spruce_boat>, "Right click a Chest on a Boat to place it on the Boat. While in the Boat, opening your inventory will also open the Chest's inventory.");
mods.jei.JEI.addDescription(<minecraft:birch_boat>, "Right click a Chest on a Boat to place it on the Boat. While in the Boat, opening your inventory will also open the Chest's inventory.");
mods.jei.JEI.addDescription(<minecraft:jungle_boat>, "Right click a Chest on a Boat to place it on the Boat. While in the Boat, opening your inventory will also open the Chest's inventory.");
mods.jei.JEI.addDescription(<minecraft:acacia_boat>, "Right click a Chest on a Boat to place it on the Boat. While in the Boat, opening your inventory will also open the Chest's inventory.");
mods.jei.JEI.addDescription(<minecraft:dark_oak_boat>, "Right click a Chest on a Boat to place it on the Boat. While in the Boat, opening your inventory will also open the Chest's inventory.");
mods.jei.JEI.addDescription(<minecraft:purple_shulker_box>, "Shulker Boxes are now explosion-proof.");
mods.jei.JEI.addDescription(<minecraft:compass>, "While in the Nether or End, Compasses will point towards the Portal that took you there.");
mods.jei.JEI.addDescription(<minecraft:ladder>, "Using a Ladder on a Ladder will place it at the bottom.", "You can quickly slide down Ladders by looking down.");
mods.jei.JEI.addDescription(<minecraft:armor_stand>, "Sneak right click an Armor Stand to swap all of your armor and the item in your offhand.");
mods.jei.JEI.addDescription(<minecraft:sign>, "You can right click a placed Sign to edit it");
mods.jei.JEI.addDescription(<minecraft:emerald_block>, "Villagers will follow players holding a Block of Emerald.");
mods.jei.JEI.addDescription(<minecraft:elytra>, "You can dye Elytras.");
mods.jei.JEI.addDescription(<quark:smoker>, "Emits smoke if there is no block above it.", "If there is a 1x1 chimney directly above it surrounded by solid blocks, the smoke will travel all the way to the top.");
mods.jei.JEI.addDescription(<quark:diamond_heart>, "Has a chance of dropping from Stonelings.", "Right click on a Stoneling to tame it, allowing it to hold your items, eat Stone, and follow you when you're holding a Diamond.");
mods.jei.JEI.addDescription(<quark:soul_bead>, "Has a chance of dropping from Wraiths, which spawn in the Nether.", "When used, inflicts the Curse debuff for 20 minutes. Monsters will spawn regardless of light level around the player during that time.");
mods.jei.JEI.addDescription(<quark:ancient_tome>, "Rare loot in dungeons. Combine with an Enchanted Book of the same enchantment and level to create an Enchanted Book one level above the usual max, which can be applied to items.");
mods.jei.JEI.addDescription(<quark:rune:*>, "Combine with enchanted items in an Anvil to change the color of the glow.");
mods.jei.JEI.addDescription(<quark:enderdragon_scale>, "Craft with the Elytra to duplicate it.");
mods.jei.JEI.addDescription(<quark:arrow_ender>, "Teleports the player to where it landed.");
mods.jei.JEI.addDescription(<quark:arrow_explosive>, "Explodes where it hits.", "Can be fired from Dispensers.");
mods.jei.JEI.addDescription(<quark:arrow_torch>, "Places a Torch where it lands.", "Can be fired from Dispensers.");
mods.jei.JEI.addDescription(<quark:parrot_egg:*>, "Feeding Beetroot Seeds to a Parrot has a chance to make it hatch a Parrot Egg, which can be thrown to get a guaranteed Parrot of the same color.");
mods.jei.JEI.addDescription(<quark:pickarang>, "Breaks the block it hits when thrown, and returns with the drop.");
mods.jei.JEI.addDescription(<minecraft:glowstone_dust>, "Can be placed like Redstone Dust to emit light, similar to a Torch.");
mods.jei.JEI.addDescription(<minecraft:gunpowder>, "Can be placed like Redstone Dust and ignited with a Flint and Steel. The Fire will spread along the Gunpowder at 2 blocks a second.", "Placing on Netherrack makes it go twice as fast.");
mods.jei.JEI.addDescription(<quark:slime_bucket>, "Right click a Slime with a Bucket to put the Slime in a Bucket.", "While in your inventory, it will hop around when you are in a Slime chunk.");
mods.jei.JEI.addDescription(<quark:soul_powder>, "Right click in the Nether to create a spirit that will fly in the direction of the nearest Nether Fortress.");
mods.jei.JEI.addDescription(<minecraft:dragon_breath>, "Can be thrown to replace nearby Stone with End Stone.");
mods.jei.JEI.addDescription(<quark:black_ash>, "Monsters cannot spawn on Wither Ash, or on the block above Wither Ash.");

<zcontent:cpu1>.addTooltip("Computer Component");
<zcontent:cpu2>.addTooltip("Computer Component");
<zcontent:cpu3>.addTooltip("Computer Component");
<zcontent:datacard1>.addTooltip("Computer Component");
<zcontent:datacard2>.addTooltip("Computer Component");
<zcontent:datacard3>.addTooltip("Computer Component");
<zcontent:graphicscard1>.addTooltip("Computer Component");
<zcontent:graphicscard2>.addTooltip("Computer Component");
<zcontent:graphicscard3>.addTooltip("Computer Component");
<refinedstorage:processor_binding>.addTooltip("Computer Component");
<refinedstorage:processor>.addTooltip("Computer Component");
<refinedstorage:processor:1>.addTooltip("Computer Component");
<refinedstorage:processor:2>.addTooltip("Computer Component");
<refinedstorage:processor:3>.addTooltip("Computer Component");
<refinedstorage:processor:4>.addTooltip("Computer Component");
<refinedstorage:processor:5>.addTooltip("Computer Component");
<zcontent:transistor>.addTooltip("Computer Component");
<zcontent:alu>.addTooltip("Computer Component");
<zcontent:proc_base>.addTooltip("Computer Component");
<zcontent:proc_raw_1>.addTooltip("Computer Component");
<zcontent:proc_raw_2>.addTooltip("Computer Component");
<zcontent:proc_raw_3>.addTooltip("Computer Component");
<zcontent:chip1>.addTooltip("Computer Component");
<zcontent:chip2>.addTooltip("Computer Component");
<zcontent:chip3>.addTooltip("Computer Component");
<zcontent:printedcircuitboard>.addTooltip("Computer Component");
<zcontent:circuitboard>.addTooltip("Computer Component");
<zcontent:cu>.addTooltip("Computer Component");
<zcontent:proc_1>.addTooltip("Computer Component");
<zcontent:proc_2>.addTooltip("Computer Component");
<zcontent:proc_3>.addTooltip("Computer Component");
<zcontent:componentbus1>.addTooltip("Computer Component");
<zcontent:componentbus2>.addTooltip("Computer Component");
<zcontent:componentbus3>.addTooltip("Computer Component");
<zcontent:card>.addTooltip("Computer Component");
<zcontent:rawcircuitboard>.addTooltip("Computer Component");
<zcontent:hdd1>.addTooltip("Computer Component");
<zcontent:hdd2>.addTooltip("Computer Component");
<zcontent:hdd3>.addTooltip("Computer Component");
<zcontent:ram1>.addTooltip("Computer Component");
<zcontent:ram2>.addTooltip("Computer Component");
<zcontent:ram3>.addTooltip("Computer Component");
<zcontent:server1>.addTooltip("Computer Component");
<zcontent:server2>.addTooltip("Computer Component");
<zcontent:server3>.addTooltip("Computer Component");
<zcontent:terminalserver>.addTooltip("Computer Component");

<zcontent:extended_tier1>.addTooltip("Right Click Block of Black Iron w/Iron Trim");
<zcontent:extended_tier2>.addTooltip("Right Click Block of Black Iron w/Gold Trim");
<zcontent:extended_tier3>.addTooltip("Right Click Block of Black Iron w/Diamond Trim");
<zcontent:extended_tier4>.addTooltip("Right Click Block of Black Iron w/Emerald Trim");
<zcontent:machineframe_1>.addTooltip("For Virtual: Farm/Fishery/Dark Room");
<zcontent:machineframe_2>.addTooltip("For Virtual: Mob Spawner/Animal Spawner");
<zcontent:machineframe_3>.addTooltip("For Virtual: Mob Farm");
<zcontent:charged_gunpowder>.addTooltip("§d§oHuge Energy Potential");
<zcontent:pill_antidote>.addTooltip("Consume to remove most negative status effects");

<zcontent:server1>.addShiftTooltip(format.italic("2 ALU"), format.italic("<Hold Shift>"));
<zcontent:server1>.addShiftTooltip(format.italic("2 CU"));
<zcontent:server1>.addShiftTooltip("4 RAM Tier 1");

<zcontent:server2>.addShiftTooltip(format.italic("3 ALU"), format.italic("<Hold Shift>"));
<zcontent:server2>.addShiftTooltip(format.italic("3 CU"));
<zcontent:server2>.addShiftTooltip("6 RAM Tier 1");
<zcontent:server2>.addShiftTooltip(format.yellow("4 RAM Tier 2"));

<zcontent:server3>.addShiftTooltip(format.italic("6 ALU"), format.italic("<Hold Shift>"));
<zcontent:server3>.addShiftTooltip(format.italic("6 CU"));
<zcontent:server3>.addShiftTooltip("8 RAM Tier 1");
<zcontent:server3>.addShiftTooltip(format.yellow("6 RAM Tier 2"));
<zcontent:server3>.addShiftTooltip(format.aqua("4 RAM Tier 3"));

<zcontent:terminalserver>.addShiftTooltip(format.italic("15 ALU"), format.italic("<Hold Shift>"));
<zcontent:terminalserver>.addShiftTooltip(format.italic("9 CU"));
<zcontent:terminalserver>.addShiftTooltip("22 RAM Tier 1");
<zcontent:terminalserver>.addShiftTooltip(format.yellow("16 RAM Tier 2"));
<zcontent:terminalserver>.addShiftTooltip(format.aqua("10 RAM Tier 3"));

<minecraft:mob_spawner>.addTooltip("Break with any tool to turn a Spawner into a "+format.italic("Broken Spawner")+" and some "+format.italic(" Spawner Shards"));
<minecraft:mob_spawner>.addTooltip("Right Click with a "+format.italic("Drop of Evil")+" to turn a Spawner into a "+format.italic("Resturbed Spawner"));
<minecraft:mob_spawner>.addTooltip("Right Click with a "+format.italic("Draconic Core")+" to turn a Spawner into a "+format.italic("Stabilized Spawner"));

<enderio:item_material:50>.displayName = "Organic Black Dye Mix";
<enderio:item_material:49>.displayName = "Organic Brown Dye Mix";
<enderio:item_material:48>.displayName = "Organic Green Dye Mix";
<actuallyadditions:item_misc:19>.displayName = "Blank Charm";
<techguns:sand_hard>.displayName = "Sand";
<techguns:slimy>.displayName = "Sand";
<deepmoblearning:polymer_clay>.displayName = "U-Matter";
<tp:kappa_pick>.displayName = "Iron Pickaxe";
<extrautils2:luxsaber>.displayName = "Light Saber";
<quark:iron_plate>.displayName = "Metal Plate";
<quark:iron_plate:1>.displayName = "Rusty Metal Plate";
<quark:iron_plate_stairs>.displayName = "Metal Plate Stairs";
<quark:iron_plate_slab>.displayName = "Metal Plate Slab";
<tp:wither_helmet>.displayName = "Nano Helmet";
<tp:wither_chestplate>.displayName = "Nano Chestplate";
<tp:wither_leggings>.displayName = "Nano Leggings";
<tp:wither_boots>.displayName = "Nano Boots";
<refinedstorage:processor_binding>.displayName = "Empty Processor Core";
<refinedstorage:processor:3>.displayName = "Basic Processor Core";
<refinedstorage:processor:4>.displayName = "Improved Processor Core";
<refinedstorage:processor:5>.displayName = "Advanved Processor Core";
<enderio:block_alloy:9>.displayName = "Construct Alloy Block";
<enderio:item_alloy_ingot:9>.displayName = "Construct Alloy Ingot";
<enderio:item_alloy_nugget:9>.displayName = "Construct Alloy Nugget";
<tp:stone_hammer>.displayName = "Spectre Hammer";
<tp:dragon_scale>.displayName = "Dirty Dragon Scale";
<tp:maloberry_bush>.displayName = "Strawberry Bush";
<tp:maloberry_berry>.displayName = "Strawberry";


game.setLocalization("item.redst5ne.name","§4Redst5ne Flux Dust§r");

game.setLocalization("potion.potency.1","§51§r");
game.setLocalization("potion.potency.2","§52§r");
game.setLocalization("potion.potency.3","§53§r");
game.setLocalization("potion.potency.4","§54§r");
game.setLocalization("potion.potency.5","§55§r");
game.setLocalization("potion.potency.6","§56§r");
game.setLocalization("potion.potency.7","§57§r");
game.setLocalization("potion.potency.8","§58§r");
game.setLocalization("potion.potency.9","§59§r");
game.setLocalization("potion.potency.10","§510§r");

game.setLocalization("enderio.power.symbol","RF");
game.setLocalization("enderio.power.format","%s RF");
game.setLocalization("enderio.power.format.of","%s / %s RF");
game.setLocalization("enderio.power.format.pertick","%s RF/t");
game.setLocalization("enderio.power.format.name","Redstone Flux (%s)");

game.setLocalization("enderio.top.suffix.rf","RF");

game.setLocalization("enderio.gui.stirling_generator.remaining","Remaining {0,number,percent}|{1,choice,0#|0<{1}m }{2,number}s|");
game.setLocalization("tile.block_wired_charger.tooltip.detailed.line1","Charges items with RF");

game.setLocalization("item.wand_1.name","§eGold§r §6Wand§r");
game.setLocalization("item.wand_2.name","§aTerraglaz§r §6Wand§r");
game.setLocalization("item.wand_3.name","§bMana Infused§r §6Wand§r");
game.setLocalization("item.wand_4.name","§5Ultimate§r §6Wand§r");

game.setLocalization("item.youmatter.thumb_drive.name","§dThumb Drive");
game.setLocalization("item.youmatter.black_hole.name","§6§kStabilising Agent");

game.setLocalization("tile.virtualmachines.farm.name","§eVirtual Farm");
game.setLocalization("tile.virtualmachines.fishery.name","§eVirtual Fishery");
game.setLocalization("tile.virtualmachines.dark_room.name","§eVirtual Dark Room");
game.setLocalization("tile.virtualmachines.animal_farm.name","§bVirtual Animal Spawner");
game.setLocalization("tile.virtualmachines.mob_spawner.name","§bVirtual Mob Spawner");
game.setLocalization("tile.virtualmachines.mob_farm.name","§dVirtual Mob Farm");
game.setLocalization("tab.virtualmachines.machine.animal_farm","Virtual Animal Spawner");

game.setLocalization("item.techguns.yellowcake.name","§2Radioactive Waste");
game.setLocalization("item.techguns.enricheduranium.name","§2Enriched Uranium Pellet");
game.setLocalization("item.techguns.rubberbar.name","Rubber");
game.setLocalization("item.techguns.rawrubber.name","Resin");

game.setLocalization("item.refinedstorage:quartz_enriched_iron.name","Enriched Alloy");
game.setLocalization("block.refinedstorage:quartz_enriched_iron_block.name","Block of Enriched Alloy");
game.setLocalization("misc.refinedstorage:energy_stored","%d / %d RF");
game.setLocalization("misc.refinedstorage:energy_usage","Usage: %d RF/t");
game.setLocalization("misc.refinedstorage:energy_usage_minimal","%d RF/t");

game.setLocalization("item.gem.name","§6Repair Gem");

game.setLocalization("quark.subtitles.throw_pickarang","§6Pickarang is flung");
game.setLocalization("quark.subtitles.clank_pickarang","§6Pickarang clanks");
game.setLocalization("quark.subtitles.pickup_pickarang","§6Pickarang is taken");
game.setLocalization("item.quark:pickarang.name","§6Pickarang");
game.setLocalization("entity.quark:pickarang.name","§6Pickarang");

game.setLocalization("tile.futuremc.stonecutter.name","Mechanical Sawmill");
game.setLocalization("container.stonecutter","Mechanical Sawmill");
game.setLocalization("container.jei.futuremc.stonecutter.name","Mechanical Sawmill");

game.setLocalization("item.fluxnetworks.flux.name","Flux Dust");
game.setLocalization("tooltip.fluxnetworks.flux","Crush the FLux Out!");
game.setLocalization("item.items.everlastingabilities.ability_totem.name","Ability Charm");
game.setLocalization("item.items.everlastingabilities.ability_bottle.name","Player Totem");

game.setLocalization("item.pe_philosophers_stone.name","§6Philosopher's Stone");
game.setLocalization("item.pe_alchemical_bag.name","§6Alchemical Bag");
game.setLocalization("item.pe_repair_talisman.name","§6Repair Talisman");
game.setLocalization("item.pe_covalence_dust_low.name","§2Low Covalence Dust");
game.setLocalization("item.pe_covalence_dust_medium.name","§3Medium Covalence Dust");
game.setLocalization("item.pe_covalence_dust_high.name","§1High Covalence Dust");
game.setLocalization("item.pe_matter_dark.name","§5§5Dark Matter");
game.setLocalization("item.pe_matter_red.name","§cRed Matter");
game.setLocalization("item.pe_divining_rod_1.name","§2Divining Rod (low)");
game.setLocalization("item.pe_divining_rod_2.name","§3Divining Rod (medium)");
game.setLocalization("item.pe_divining_rod_3.name","§1Divining Rod (high)");
game.setLocalization("item.pe_dm_pick.name","§5Dark Matter Pickaxe");
game.setLocalization("item.pe_dm_axe.name","§5Dark Matter Axe");
game.setLocalization("item.pe_dm_shovel.name","§5Dark Matter Shovel");
game.setLocalization("item.pe_dm_sword.name","§5Dark Matter Sword");
game.setLocalization("item.pe_dm_hoe.name","§5Dark Matter Hoe");
game.setLocalization("item.pe_dm_shears.name","§5Dark Matter Shears");
game.setLocalization("item.pe_dm_hammer.name","§5Dark Matter Hammer");
game.setLocalization("item.pe_rm_pick.name","§cRed Matter Pickaxe");
game.setLocalization("item.pe_rm_axe.name","§cRed Matter Axe");
game.setLocalization("item.pe_rm_shovel.name","§cRed Matter Shovel");
game.setLocalization("item.pe_rm_sword.name","§cRed Matter Sword");
game.setLocalization("item.pe_rm_hoe.name","§cRed Matter Hoe");
game.setLocalization("item.pe_rm_shears.name","§cRed Matter Shears");
game.setLocalization("item.pe_rm_hammer.name","§cRed Matter Hammer");
game.setLocalization("item.pe_rm_katar.name","§cRed Katar");
game.setLocalization("item.pe_rm_morning_star.name","§cRed Morningstar");
game.setLocalization("item.pe_dm_armor_0.name","§5Dark Matter Boots");
game.setLocalization("item.pe_dm_armor_1.name","§5Dark Matter Leggings");
game.setLocalization("item.pe_dm_armor_2.name","§5Dark Matter Chestplate");
game.setLocalization("item.pe_dm_armor_3.name","§5Dark Matter Helmet");
game.setLocalization("item.pe_rm_armor_0.name","§cRed Matter Boots");
game.setLocalization("item.pe_rm_armor_1.name","§cRed Matter Leggings");
game.setLocalization("item.pe_rm_armor_2.name","§cRed Matter Chestplate");
game.setLocalization("item.pe_rm_armor_3.name","§cRed Matter Helmet");
game.setLocalization("item.pe_gem_armor_0.name","§6Gem Boots");
game.setLocalization("item.pe_gem_armor_1.name","§6Gem Leggings");
game.setLocalization("item.pe_gem_armor_2.name","§6Gem Chestplate");
game.setLocalization("item.pe_gem_armor_3.name","§6Gem Helmet");
game.setLocalization("item.pe_tome.name","§6Tome of Knowledge");
game.setLocalization("item.pe_transmutation_tablet.name","§6Transmutation Tablet");
game.setLocalization("tile.pe_alchemy_chest.name","§6Alchemical Chest");
game.setLocalization("tile.pe_transmutation_stone.name","§6Transmutation Table");
game.setLocalization("tile.pe_condenser.name","§6Energy Condenser");
game.setLocalization("tile.pe_condenser_mk2.name","§6Energy Condenser MK2");
game.setLocalization("tile.pe_rm_furnace.name","§cRed Matter Furnace");
game.setLocalization("tile.pe_dm_furnace.name","§5Dark Matter Furnace");
game.setLocalization("tile.pe_rm_block.name","§cRed Matter Block");
game.setLocalization("tile.pe_dm_block.name","§5Dark Matter Block");
game.setLocalization("tile.pe_dmPedestal.name","§5Dark Matter Pedestal");

game.setLocalization("item.draconicevolution:awakened_core.name","§6Awakened Core");
game.setLocalization("item.draconicevolution:dragon_heart.name","§6Dragon Heart");
game.setLocalization("item.draconicevolution:wyvern_core.name","§5Wyvern Core");
game.setLocalization("item.draconicevolution:wyvern_pick.name","§5Pickaxe of the Wyvern");
game.setLocalization("item.draconicevolution:wyvern_axe.name","§5Axe of the Wyvern");
game.setLocalization("item.draconicevolution:wyvern_shovel.name","§5Shovel of the Wyvern");
game.setLocalization("item.draconicevolution:wyvern_sword.name","§5Sword of the Wyvern");
game.setLocalization("item.draconicevolution:wyvern_bow.name","§5Bow of the Wyvern");
game.setLocalization("item.draconicevolution:wyvern_helm.name","§5Wyvern Helm");
game.setLocalization("item.draconicevolution:wyvern_chest.name","§5Wyvern Chestplate");
game.setLocalization("item.draconicevolution:wyvern_legs.name","§5Wyvern Leggings");
game.setLocalization("item.draconicevolution:wyvern_boots.name","§5Wyvern Boots");
game.setLocalization("item.draconicevolution:draconic_pick.name","§6Draconic Pickaxe");
game.setLocalization("item.draconicevolution:draconic_axe.name","§6Draconic Axe");
game.setLocalization("item.draconicevolution:draconic_shovel.name","§6Draconic Shovel");
game.setLocalization("item.draconicevolution:draconic_hoe.name","§6Draconic Hoe");
game.setLocalization("item.draconicevolution:draconic_sword.name","§6Draconic Sword");
game.setLocalization("item.draconicevolution:draconic_bow.name","§6Draconic Bow");
game.setLocalization("item.draconicevolution:draconic_helm.name","§6Draconic Helm");
game.setLocalization("item.draconicevolution:draconic_chest.name","§6Draconic Chestplate");
game.setLocalization("item.draconicevolution:draconic_legs.name","§6Draconic Leggings");
game.setLocalization("item.draconicevolution:draconic_boots.name","§6Draconic Boots");
game.setLocalization("item.draconicevolution:draconic_staff_of_power.name","§6Draconic Staff of Power");
game.setLocalization("item.draconicevolution:wyvern_energy_core.name","§5Wyvern Energy Core");
game.setLocalization("item.draconicevolution:draconic_energy_core.name","§6Draconic Energy Core");
game.setLocalization("item.draconicevolution:draconium_capacitor.wyvern.name","§5Wyvern Flux Capacitor");
game.setLocalization("item.draconicevolution:draconium_capacitor.draconic.name","§6Draconic Flux Capacitor");
game.setLocalization("item.draconicevolution:draconic_ingot.name","§6Awakened Draconium Ingot");
game.setLocalization("item.draconicevolution:chaotic_core.name","§0Chaotic Core");
game.setLocalization("item.draconicevolution:nugget.awakened.name","§6Awakened Draconium Nugget");




