//This file was created via CT-GUI! Editing it is not advised!
//Don't touch me!
//#Remove
//Don't touch me!
//#Add
recipes.addShapeless(<zcontent:withered_bone_meal> * 3, [<ore:boneWithered>]);
recipes.addShapeless(<immersiveengineering:material:23>, [<ore:plateSteel>, <immersiveengineering:tool:1> | <ore:toolShears>]);
recipes.addShapeless(<immersiveengineering:material:22>, [<ore:plateAluminum>, <immersiveengineering:tool:1> | <ore:toolShears>]);
recipes.addShapeless(<immersiveengineering:material:21>, [<ore:plateElectrum>, <immersiveengineering:tool:1> | <ore:toolShears>]);
recipes.addShapeless(<immersiveengineering:material:20>, [<ore:plateCopper>, <immersiveengineering:tool:1> | <ore:toolShears>]);
recipes.addShaped(<quark:crystal:8> * 12, [[<jaopca:item_essencecrystalblack>, <jaopca:item_essencecrystalblack>, <jaopca:item_essencecrystalblack>],[<jaopca:item_essencecrystalblack>, null, <jaopca:item_essencecrystalblack>], [<jaopca:item_essencecrystalblack>, <jaopca:item_essencecrystalblack>, <jaopca:item_essencecrystalblack>]]);
recipes.addShaped(<quark:crystal:7> * 12, [[<jaopca:item_essencecrystalviolet>, <jaopca:item_essencecrystalviolet>, <jaopca:item_essencecrystalviolet>],[<jaopca:item_essencecrystalviolet>, null, <jaopca:item_essencecrystalviolet>], [<jaopca:item_essencecrystalviolet>, <jaopca:item_essencecrystalviolet>, <jaopca:item_essencecrystalviolet>]]);
recipes.addShaped(<quark:crystal:6> * 12, [[<jaopca:item_essencecrystalindigo>, <jaopca:item_essencecrystalindigo>, <jaopca:item_essencecrystalindigo>],[<jaopca:item_essencecrystalindigo>, null, <jaopca:item_essencecrystalindigo>], [<jaopca:item_essencecrystalindigo>, <jaopca:item_essencecrystalindigo>, <jaopca:item_essencecrystalindigo>]]);
recipes.addShaped(<quark:crystal:5> * 12, [[<jaopca:item_essencecrystalblue>, <jaopca:item_essencecrystalblue>, <jaopca:item_essencecrystalblue>],[<jaopca:item_essencecrystalblue>, null, <jaopca:item_essencecrystalblue>], [<jaopca:item_essencecrystalblue>, <jaopca:item_essencecrystalblue>, <jaopca:item_essencecrystalblue>]]);
recipes.addShaped(<quark:crystal:4> * 12, [[<jaopca:item_essencecrystalgreen>, <jaopca:item_essencecrystalgreen>, <jaopca:item_essencecrystalgreen>],[<jaopca:item_essencecrystalgreen>, null, <jaopca:item_essencecrystalgreen>], [<jaopca:item_essencecrystalgreen>, <jaopca:item_essencecrystalgreen>, <jaopca:item_essencecrystalgreen>]]);
recipes.addShaped(<quark:crystal:3> * 12, [[<jaopca:item_essencecrystalyellow>, <jaopca:item_essencecrystalyellow>, <jaopca:item_essencecrystalyellow>],[<jaopca:item_essencecrystalyellow>, null, <jaopca:item_essencecrystalyellow>], [<jaopca:item_essencecrystalyellow>, <jaopca:item_essencecrystalyellow>, <jaopca:item_essencecrystalyellow>]]);
recipes.addShaped(<quark:crystal:2> * 12, [[<jaopca:item_essencecrystalorange>, <jaopca:item_essencecrystalorange>, <jaopca:item_essencecrystalorange>],[<jaopca:item_essencecrystalorange>, null, <jaopca:item_essencecrystalorange>], [<jaopca:item_essencecrystalorange>, <jaopca:item_essencecrystalorange>, <jaopca:item_essencecrystalorange>]]);
recipes.addShaped(<quark:crystal:1> * 12, [[<jaopca:item_essencecrystalred>, <jaopca:item_essencecrystalred>, <jaopca:item_essencecrystalred>],[<jaopca:item_essencecrystalred>, null, <jaopca:item_essencecrystalred>], [<jaopca:item_essencecrystalred>, <jaopca:item_essencecrystalred>, <jaopca:item_essencecrystalred>]]);
recipes.addShaped(<quark:crystal> * 12, [[<jaopca:item_essencecrystalwhite>, <jaopca:item_essencecrystalwhite>, <jaopca:item_essencecrystalwhite>],[<jaopca:item_essencecrystalwhite>, null, <jaopca:item_essencecrystalwhite>], [<jaopca:item_essencecrystalwhite>, <jaopca:item_essencecrystalwhite>, <jaopca:item_essencecrystalwhite>]]);
recipes.addShapeless(<minecraft:bone> * 9, [<ore:blockBone>]);
recipes.addShapeless(<zcontent:wither_bone> * 9, [<ore:blockBoneWithered>]);
recipes.addShapeless(<minecraft:gunpowder> * 9, [<ore:blockGunpowder>]);
recipes.addShapeless(<minecraft:flint> * 9, [<ore:blockFlint>]);
recipes.addShapeless(<minecraft:rotten_flesh> * 9, [<zcontent:rotten_flesh_block>]);
recipes.addShapeless(<zcontent:flint_block>, [<ore:flint>,<ore:flint>,<ore:flint>,<ore:flint>,<ore:flint>,<ore:flint>,<ore:flint>,<ore:flint>,<ore:flint>]);
recipes.addShapeless(<zcontent:gunpowder_block>, [<ore:gunpowder>,<ore:gunpowder>,<ore:gunpowder>,<ore:gunpowder>,<ore:gunpowder>,<ore:gunpowder>,<ore:gunpowder>,<ore:gunpowder>,<ore:gunpowder>]);
recipes.addShapeless(<zcontent:wither_bone_block>, [<ore:boneWithered>,<ore:boneWithered>,<ore:boneWithered>,<ore:boneWithered>,<ore:boneWithered>,<ore:boneWithered>,<ore:boneWithered>,<ore:boneWithered>,<ore:boneWithered>]);
recipes.addShapeless(<zcontent:bone_block>, [<ore:bone>,<ore:bone>,<ore:bone>,<ore:bone>,<ore:bone>,<ore:bone>,<ore:bone>,<ore:bone>,<ore:bone>]);
recipes.addShapeless(<zcontent:rotten_flesh_block>, [<minecraft:rotten_flesh>,<minecraft:rotten_flesh>,<minecraft:rotten_flesh>,<minecraft:rotten_flesh>,<minecraft:rotten_flesh>,<minecraft:rotten_flesh>,<minecraft:rotten_flesh>,<minecraft:rotten_flesh>,<minecraft:rotten_flesh>]);
recipes.addShaped(<tp:unhardened_stone>, [[<ore:stoneBasalt>, <ore:stoneDiorite>, <ore:stoneBasalt>],[<ore:stoneDiorite>, <ore:blockClay>, <ore:stoneDiorite>], [<ore:stoneBasalt>, <ore:stoneDiorite>, <ore:stoneBasalt>]]);
recipes.addShaped(<quark:redstone_inductor>, [[null, null, null],[<minecraft:redstone>, <ore:itemBall>, <minecraft:redstone>], [<ore:stonePolished>, <ore:stonePolished>, <ore:stonePolished>]]);
recipes.addShaped(<darkutils:timer>, [[null, <minecraft:redstone>, null],[<minecraft:redstone_torch>, <minecraft:clock>, <minecraft:redstone_torch>], [<ore:stonePolished>, <ore:stonePolished>, <ore:stonePolished>]]);
recipes.addShaped(<quark:redstone_randomizer>, [[null, <minecraft:redstone_torch>, null],[<minecraft:redstone_torch>, <ore:gemQuartzBlack>, <minecraft:redstone_torch>], [<ore:stonePolished>, <ore:stonePolished>, <ore:stonePolished>]]);
recipes.addShaped(<minecraft:comparator>, [[null, <minecraft:redstone_torch>, null],[<minecraft:redstone_torch>, <ore:gemQuartz>, <minecraft:redstone_torch>], [<ore:stonePolished>, <ore:stonePolished>, <ore:stonePolished>]]);
recipes.addShaped(<minecraft:repeater>, [[<minecraft:redstone>, null, <minecraft:redstone>],[<minecraft:stick>, <minecraft:redstone>, <minecraft:stick>], [<ore:stonePolished>, <ore:stonePolished>, <ore:stonePolished>]]);
recipes.addShaped(<minecraft:repeater>, [[null, null, null],[<minecraft:redstone_torch>, <minecraft:redstone>, <minecraft:redstone_torch>], [<ore:stonePolished>, <ore:stonePolished>, <ore:stonePolished>]]);
recipes.addShaped(<tesseract:tesseract>, [[<ore:plateDarkSteel>, <thermaldynamics:duct_0:2>, <ore:plateDarkSteel>],[<thermaldynamics:duct_32:2>, <rftools:infused_enderpearl>, <thermaldynamics:duct_16:4>], [<ore:plateDarkSteel>, <techguns:itemshared:69>, <ore:plateDarkSteel>]]);
recipes.addShapeless(<quantumstorage:remote>, [<quantumstorage:remote>]);
recipes.addShaped(<zcontent:icesword>, [[null, <mysticalagriculture:ice_essence>, null],[<mysticalagriculture:ice_essence>, <immersiveengineering:sword_steel>, <mysticalagriculture:ice_essence>], [null, <mysticalagriculture:ice_essence>, null]]);
recipes.addShaped(<zcontent:firesword>, [[null, <mysticalagriculture:fire_essence>, null],[<mysticalagriculture:fire_essence>, <immersiveengineering:sword_steel>, <mysticalagriculture:fire_essence>], [null, <mysticalagriculture:fire_essence>, null]]);
recipes.addShaped(<quark:pipe> * 16, [[null, null, null],[<ore:ingotConstructionAlloy>, <ore:blockGlassColorless>, <ore:ingotConstructionAlloy>], [null, null, null]]);
recipes.addShaped(<futuremc:netherite_leggings>, [[<ore:ingotNetherite>, <ore:ingotNetherite>, <ore:ingotNetherite>],[<ore:ingotNetherite>, null, <ore:ingotNetherite>], [<ore:ingotNetherite>, null, <ore:ingotNetherite>]]);
recipes.addShaped(<futuremc:netherite_chestplate>, [[<ore:ingotNetherite>, null, <ore:ingotNetherite>],[<ore:ingotNetherite>, <ore:ingotNetherite>, <ore:ingotNetherite>], [<ore:ingotNetherite>, <ore:ingotNetherite>, <ore:ingotNetherite>]]);
recipes.addShaped(<futuremc:netherite_boots>, [[<ore:ingotNetherite>, null, <ore:ingotNetherite>],[<ore:ingotNetherite>, null, <ore:ingotNetherite>], [null, null, null]]);
recipes.addShaped(<futuremc:netherite_helmet>, [[<ore:ingotNetherite>, <ore:ingotNetherite>, <ore:ingotNetherite>],[<ore:ingotNetherite>, null, <ore:ingotNetherite>], [null, null, null]]);
recipes.addShaped(<enderio:item_material:10>, [[null, <ore:stonePolished>, null],[<ore:stonePolished>, <ore:gearWood>, <ore:stonePolished>], [null, <ore:stonePolished>, null]]);
recipes.addShaped(<tp:stone_hammer>, [[null, <randomthings:ingredient:3>, <ore:stringFluxed>],[null, <redstonearsenal:material:193>, <randomthings:ingredient:3>], [<redstonearsenal:material:193>, null, null]]);
recipes.addShaped(<cyclicmagic:water_candle>, [[null, <quark:tallow>, null],[<rftools:infused_diamond>, <techguns:itemshared:103>, <rftools:infused_diamond>], [<minecraft:light_weighted_pressure_plate>, <minecraft:light_weighted_pressure_plate>, <minecraft:light_weighted_pressure_plate>]]);
recipes.addShaped(<cyclicmagic:beacon_potion>, [[<ore:blockGlassColorless>, <ore:blockGlassColorless>, <ore:blockGlassColorless>],[<ore:blockGlassColorless>, <ore:netherStar>, <ore:blockGlassColorless>], [<ore:blockEmerald>, <ore:blockEmerald>, <ore:blockEmerald>]]);
recipes.addShapeless(<cyclicmagic:bundled_pipe> * 3, [<cyclicmagic:item_pipe>,<cyclicmagic:energy_pipe>,<cyclicmagic:fluid_pipe>]);
recipes.addShaped(<cyclicmagic:fluid_pump>, [[<cyclicmagic:fluid_pipe>, null, null],[<minecraft:heavy_weighted_pressure_plate>, null, null], [null, null, null]]);
recipes.addShaped(<cyclicmagic:energy_pump>, [[<cyclicmagic:energy_pipe>, null, null],[<minecraft:heavy_weighted_pressure_plate>, null, null], [null, null, null]]);
recipes.addShaped(<cyclicmagic:item_pump>, [[<cyclicmagic:item_pipe>, null, null],[<minecraft:heavy_weighted_pressure_plate>, null, null], [null, null, null]]);
recipes.addShapeless(<cyclicmagic:fluid_pipe> * 8, [<extrautils2:pipe>,<extrautils2:pipe>,<extrautils2:pipe>,<extrautils2:pipe>,<ore:nuggetSapphire>,<extrautils2:pipe>,<extrautils2:pipe>,<extrautils2:pipe>,<extrautils2:pipe>]);
recipes.addShapeless(<cyclicmagic:item_pipe> * 8, [<extrautils2:pipe>,<extrautils2:pipe>,<extrautils2:pipe>,<extrautils2:pipe>,<ore:nuggetTanzanite>,<extrautils2:pipe>,<extrautils2:pipe>,<extrautils2:pipe>,<extrautils2:pipe>]);
recipes.addShapeless(<cyclicmagic:energy_pipe> * 8, [<extrautils2:pipe>,<extrautils2:pipe>,<extrautils2:pipe>,<extrautils2:pipe>,<ore:nuggetRuby>,<extrautils2:pipe>,<extrautils2:pipe>,<extrautils2:pipe>,<extrautils2:pipe>]);
recipes.addShaped(<extrautils2:pipe> * 64, [[<ore:ingotTin>, <ore:ingotTin>, <ore:ingotTin>],[<extrautils2:decorativeglass:5>, <extrautils2:decorativeglass:5>, <extrautils2:decorativeglass:5>], [<ore:ingotTin>, <ore:ingotTin>, <ore:ingotTin>]]);
recipes.addShaped(<cyclicmagic:cable_wireless_energy>, [[<ore:gemRuby>, <cyclicmagic:ender_pearl_reuse> | <cyclicmagic:ender_pearl_mounted>, <ore:gemRuby>],[<cyclicmagic:ender_pearl_reuse> | <cyclicmagic:ender_pearl_mounted>, <ore:blockSilver>, <cyclicmagic:ender_pearl_reuse> | <cyclicmagic:ender_pearl_mounted>], [<ore:gemRuby>, <cyclicmagic:ender_pearl_reuse> | <cyclicmagic:ender_pearl_mounted>, <ore:gemRuby>]]);
recipes.addShaped(<cyclicmagic:cable_wireless_fluid>, [[<ore:gemSapphire>, <cyclicmagic:ender_pearl_reuse> | <cyclicmagic:ender_pearl_mounted>, <ore:gemSapphire>],[<cyclicmagic:ender_pearl_reuse> | <cyclicmagic:ender_pearl_mounted>, <ore:blockSilver>, <cyclicmagic:ender_pearl_reuse> | <cyclicmagic:ender_pearl_mounted>], [<ore:gemSapphire>, <cyclicmagic:ender_pearl_reuse> | <cyclicmagic:ender_pearl_mounted>, <ore:gemSapphire>]]);
recipes.addShaped(<cyclicmagic:cable_wireless>, [[<ore:gemTanzanite>, <cyclicmagic:ender_pearl_reuse> | <cyclicmagic:ender_pearl_mounted>, <ore:gemTanzanite>],[<cyclicmagic:ender_pearl_reuse> | <cyclicmagic:ender_pearl_mounted>, <ore:blockSilver>, <cyclicmagic:ender_pearl_reuse> | <cyclicmagic:ender_pearl_mounted>], [<ore:gemTanzanite>, <cyclicmagic:ender_pearl_reuse> | <cyclicmagic:ender_pearl_mounted>, <ore:gemTanzanite>]]);
recipes.addShaped(<cyclicmagic:ender_pearl_mounted>, [[<extrautils2:endershard>, <extrautils2:endershard>, <extrautils2:endershard>],[<extrautils2:endershard>, <ore:gemSapphire>, <extrautils2:endershard>], [<extrautils2:endershard>, <extrautils2:endershard>, <extrautils2:endershard>]]);
recipes.addShaped(<cyclicmagic:ender_pearl_reuse>, [[<extrautils2:endershard>, <extrautils2:endershard>, <extrautils2:endershard>],[<extrautils2:endershard>, <ore:gemRuby>, <extrautils2:endershard>], [<extrautils2:endershard>, <extrautils2:endershard>, <extrautils2:endershard>]]);
recipes.addShaped(<cyclicmagic:wireless_receiver>, [[null, <minecraft:repeater>, null],[null, <cyclicmagic:ender_pearl_reuse>.giveBack(), null], [null, <quark:polished_stone>, null]]);
recipes.addShaped(<cyclicmagic:wireless_transmitter>, [[null, <minecraft:repeater>, null],[null, <cyclicmagic:ender_pearl_mounted>.giveBack(), null], [null, <quark:polished_stone>, null]]);
recipes.addShaped(<cyclicmagic:spikes_diamond>, [[null, <ore:nuggetDiamond>, null],[<ore:nuggetDiamond>, <cyclicmagic:spikes_iron>, <ore:nuggetDiamond>], [<quark:polished_stone>, <minecraft:redstone_block>, <quark:polished_stone>]]);
recipes.addShaped(<cyclicmagic:spikes_iron>, [[null, <ore:nuggetIron>, null],[<ore:nuggetIron>, <minecraft:iron_bars>, <ore:nuggetIron>], [<minecraft:stone>, <minecraft:redstone>, <minecraft:stone>]]);
recipes.addShapeless(<cyclicmagic:plate_push_fast>, [<cyclicmagic:plate_push_fast_angle>]);
recipes.addShapeless(<cyclicmagic:plate_push_fast_angle>, [<cyclicmagic:plate_push_fast_corner>]);
recipes.addShapeless(<cyclicmagic:plate_push_fast_corner>, [<cyclicmagic:plate_push_fast>]);
recipes.addShapeless(<cyclicmagic:plate_push_slowest>, [<cyclicmagic:plate_push_slowest_angle>]);
recipes.addShapeless(<cyclicmagic:plate_push_slowest_angle>, [<cyclicmagic:plate_push_slowest_corner>]);
recipes.addShapeless(<cyclicmagic:plate_push_slowest_corner>, [<cyclicmagic:plate_push_slowest>]);
recipes.addShapeless(<cyclicmagic:plate_push_slow>, [<cyclicmagic:plate_push_slow_angle>]);
recipes.addShapeless(<cyclicmagic:plate_push_slow_angle>, [<cyclicmagic:plate_push_slow_corner>]);
recipes.addShapeless(<cyclicmagic:plate_push_slow_corner>, [<cyclicmagic:plate_push_slow>]);
recipes.addShapeless(<cyclicmagic:plate_push>, [<cyclicmagic:plate_push_med_angle>]);
recipes.addShapeless(<cyclicmagic:plate_push_med_angle>, [<cyclicmagic:plate_push_corner>]);
recipes.addShapeless(<cyclicmagic:plate_push_corner>, [<cyclicmagic:plate_push>]);
recipes.addShaped(<cyclicmagic:plate_push_slowest> * 64, [[<ore:ingotAluminium>, <ore:gemSapphire>, <ore:ingotAluminium>], [<minecraft:redstone>, <ore:gearAluminum>, <minecraft:redstone>]]);
recipes.addShaped(<cyclicmagic:plate_push_slow> * 64, [[<ore:ingotAluminium>, <ore:gemTanzanite>, <ore:ingotAluminium>], [<minecraft:redstone>, <ore:gearAluminum>, <minecraft:redstone>]]);
recipes.addShaped(<cyclicmagic:plate_push_fast> * 64, [[<ore:ingotAluminium>, <ore:gemRuby>, <ore:ingotAluminium>], [<minecraft:redstone>, <ore:gearAluminum>, <minecraft:redstone>]]);
recipes.addShaped(<cyclicmagic:plate_push> * 64, [[<ore:ingotAluminium>, <ore:gemPeridot>, <ore:ingotAluminium>], [<minecraft:redstone>, <ore:gearAluminum>, <minecraft:redstone>]]);
recipes.addShaped(<cyclicmagic:glowing_helmet>, [[<minecraft:glowstone_dust>, <minecraft:glowstone_dust>, <minecraft:glowstone_dust>],[<minecraft:glowstone_dust>, <biomesoplenty:gem:7>, <minecraft:glowstone_dust>], [<minecraft:glowstone_dust>, <thermalfoundation:armor.helmet_constantan>, <minecraft:glowstone_dust>]]);
recipes.addShaped(<cyclicmagic:password_remote>, [[null, <minecraft:lever>, null],[null, <cyclicmagic:ender_pearl_reuse>.giveBack(), null], [null, <minecraft:stone_slab>, null]]);
recipes.addShaped(<cyclicmagic:dynamite_mining> * 64, [[<ore:paper>, <ore:gunpowder>],[<ore:gunpowder>, <ore:dyePurple>]]);
recipes.addShaped(<cyclicmagic:dynamite_safe> * 64, [[<ore:paper>, <ore:gunpowder>],[<ore:gunpowder>, <ore:dyeLime>]]);
recipes.addShaped(<cyclicmagic:moon_sensor>, [[<extrautils2:ingredients:5>],[<minecraft:daylight_detector>]]);
recipes.addShapeless(<cyclicmagic:button_large>, [<minecraft:cobblestone>,<minecraft:cobblestone>]);
recipes.addShapeless(<thermalfoundation:tome_experience>.withTag({ench: [{lvl: 1000, id: 106 as short}]}), [<minecraft:barrier>]);
recipes.addShapeless(<minecraft:nether_star>, [<mysticalagradditions:stuff>,<mysticalagradditions:stuff>,<mysticalagradditions:stuff>,<mysticalagradditions:stuff>]);
recipes.addShaped(<mysticalagriculture:mystical_fertilizer>, [[<mysticalagriculture:fertilized_essence>, <mysticalagriculture:fertilized_essence>, <mysticalagriculture:fertilized_essence>],[<mysticalagriculture:fertilized_essence>, <minecraft:dye:15>, <mysticalagriculture:fertilized_essence>], [<mysticalagriculture:fertilized_essence>, <mysticalagriculture:fertilized_essence>, <mysticalagriculture:fertilized_essence>]]);
recipes.addShaped(<mysticalagradditions:special:1>, [[<ore:essenceInsanium>, <ore:dragonEgg>, <ore:essenceInsanium>],[<ore:dragonEgg>, <extendedcrafting:storage:6>, <ore:dragonEgg>], [<ore:essenceInsanium>, <ore:dragonEgg>, <ore:essenceInsanium>]]);
recipes.addShaped(<mysticalagradditions:special:5>, [[<ore:essenceInsanium>, <ore:blockCosmicNeutronium>, <ore:essenceInsanium>],[<ore:blockCosmicNeutronium>, <extendedcrafting:storage:6>, <ore:blockCosmicNeutronium>], [<ore:essenceInsanium>, <ore:blockCosmicNeutronium>, <ore:essenceInsanium>]]);
recipes.addShaped(<mysticalagradditions:special:4>, [[<ore:essenceInsanium>, <ore:blockDraconiumAwakened>, <ore:essenceInsanium>],[<ore:blockDraconiumAwakened>, <extendedcrafting:storage:6>, <ore:blockDraconiumAwakened>], [<ore:essenceInsanium>, <ore:blockDraconiumAwakened>, <ore:essenceInsanium>]]);
recipes.addShaped(<mysticalagradditions:special>, [[<ore:essenceInsanium>, <ore:blockNetherStar>, <ore:essenceInsanium>],[<ore:blockNetherStar>, <extendedcrafting:storage:6>, <ore:blockNetherStar>], [<ore:essenceInsanium>, <ore:blockNetherStar>, <ore:essenceInsanium>]]);
recipes.addShapeless(<refinedstorage:fluid_storage_disk:3>, [<refinedstorage:storage_housing>,<refinedstorage:fluid_storage_part:3>]);
recipes.addShapeless(<refinedstorage:fluid_storage_disk:2>, [<refinedstorage:storage_housing>,<refinedstorage:fluid_storage_part:2>]);
recipes.addShapeless(<refinedstorage:fluid_storage_disk:1>, [<refinedstorage:storage_housing>,<refinedstorage:fluid_storage_part:1>]);
recipes.addShapeless(<refinedstorage:fluid_storage_disk>, [<refinedstorage:storage_housing>,<refinedstorage:fluid_storage_part>]);
recipes.addShapeless(<refinedstorage:storage_disk:3>, [<refinedstorage:storage_housing>,<refinedstorage:storage_part:3>]);
recipes.addShapeless(<refinedstorage:storage_disk:2>, [<refinedstorage:storage_housing>,<refinedstorage:storage_part:2>]);
recipes.addShapeless(<refinedstorage:storage_disk:1>, [<refinedstorage:storage_housing>,<refinedstorage:storage_part:1>]);
recipes.addShapeless(<refinedstorage:storage_disk>, [<refinedstorage:storage_housing>,<refinedstorage:storage_part>]);
recipes.addShaped(<enderio:block_enchanter>, [[null, <eplus:decorative_book:1>, null],[<ore:gemDiamond>, <ore:plateDenseDarkSteel>, <ore:gemDiamond>], [<enderio:item_alloy_ingot:6>, <enderio:item_alloy_ingot:6>, <enderio:item_alloy_ingot:6>]]);
recipes.addShapeless(<tp:ender_dust>, [<ore:nuggetEnderpearl>,<ore:nuggetEnderpearl>,<ore:nuggetEnderpearl>,<ore:nuggetEnderpearl>,<ore:nuggetEnderpearl>,<ore:nuggetEnderpearl>,<ore:nuggetEnderpearl>,<ore:nuggetEnderpearl>,<ore:nuggetEnderpearl>]);
recipes.addShapeless(<enderio:item_material:28> * 9, [<ore:dustEnder>]);
recipes.addShapeless(<eplus:decorative_book:1>, [<extendedcrafting:material:7>,<extendedcrafting:material:7>,<quark:ancient_tome>,<extendedcrafting:material:7>,<extendedcrafting:material:7>]);
recipes.addShapeless(<eplus:decorative_book:1>, [<extendedcrafting:material:7>,<ore:essenceInsanium>,<extendedcrafting:material:7>,<ore:essenceInsanium>,<minecraft:enchanted_book>,<ore:essenceInsanium>,<extendedcrafting:material:7>,<ore:essenceInsanium>,<extendedcrafting:material:7>]);
recipes.addShapeless(<enderio:item_material:3>, [<ore:itemPowderPhotovoltaic>, <minecraft:glass_pane>]);
recipes.addShapeless(<redstonerepository:material:1>, [<ore:dustGelidEnderium>,<ore:dustPyrotheum>]);
recipes.addShapeless(<redstonearsenal:material:32>, [<ore:dustElectrumFlux>,<ore:dustPyrotheum>]);
recipes.addShapeless(<thermalfoundation:material:167>, [<ore:dustEnderium>,<ore:dustPyrotheum>]);
recipes.addShapeless(<thermalfoundation:material:166>, [<ore:dustLumium>,<ore:dustPyrotheum>]);
recipes.addShapeless(<thermalfoundation:material:165>, [<ore:dustSignalum>,<ore:dustPyrotheum>]);
recipes.addShapeless(<cyclicmagic:ender_torch>, [<ore:dustEnder>,<minecraft:torch>,<minecraft:torch>,<minecraft:torch>,<minecraft:torch>,<minecraft:torch>,<minecraft:torch>,<minecraft:torch>,<minecraft:torch>]);
recipes.addShaped(<tp:birthday_pickaxe>, [[null, <ore:gemDiamond>, null],[null, <minecraft:cake>, null], [null, <actuallyadditions:item_pickaxe_obsidian>, null]]);
recipes.addShaped(<zcontent:silver_obsidian_axe>, [[<ore:ingotSilver>, <ore:ingotSilver>, null],[<ore:ingotSilver>, <ore:stickObsidian>, null], [null, <ore:stickObsidian>, null]]);
recipes.addShaped(<zcontent:silver_obsidian_shovel>, [[null, <ore:ingotSilver>, null],[null, <ore:stickObsidian>, null], [null, <ore:stickObsidian>, null]]);
recipes.addShaped(<zcontent:silver_obsidian_pick>, [[<ore:ingotSilver>, <ore:ingotSilver>, <ore:ingotSilver>],[null, <ore:stickObsidian>, null], [null, <ore:stickObsidian>, null]]);
recipes.addShaped(<zcontent:silver_obsidian_sword>, [[null, <ore:ingotSilver>, null],[null, <ore:ingotSilver>, null], [null, <ore:stickObsidian>, null]]);
recipes.addShapeless(<jaopca:item_stickobsidian>, [<ore:obsidian>,<ore:obsidian>,<tp:stone_hammer>]);
recipes.addShaped(<zcontent:sulfur_crystal>, [[<ore:dustSulfur>, <ore:crystalSlag>, <ore:dustSulfur>],[<ore:crystalSlagRich>, <ore:crystalCinnabar>, <ore:crystalSlagRich>], [<ore:dustSulfur>, <ore:crystalSlag>, <ore:dustSulfur>]]);
recipes.addShapeless(<storagenetwork:controller>, [<storagenetwork:master>,<minecraft:emerald>]);
recipes.addShapeless(<storagenetwork:request>, [<storagenetwork:master>,<minecraft:crafting_table>]);
recipes.addShaped(<storagenetwork:master>, [[<ore:blockQuartz>, <storagenetwork:kabel>, <ore:blockQuartz>],[<storagenetwork:kabel>, <fluxnetworks:fluxblock>, <storagenetwork:kabel>], [<ore:blockQuartz>, <storagenetwork:kabel>, <ore:blockQuartz>]]);
recipes.addShapeless(<storagenetwork:upgrade>, [<ore:plateSilver>,<minecraft:redstone>]);
recipes.addShapeless(<storagenetwork:upgrade:2>, [<ore:plateSilver>,<ore:dustGlowstone>]);
recipes.addShapeless(<storagenetwork:upgrade:3>, [<ore:plateSilver>,<ore:blockChest>]);
recipes.addShapeless(<storagenetwork:upgrade:1>, [<ore:plateSilver>,<minecraft:redstone_torch>]);
recipes.addShapeless(<storagenetwork:process_kabel> * 8, [<ore:gemTopaz>,<storagenetwork:kabel>,<storagenetwork:kabel>,<storagenetwork:kabel>,<storagenetwork:kabel>,<storagenetwork:kabel>,<storagenetwork:kabel>,<storagenetwork:kabel>,<storagenetwork:kabel>]);
recipes.addShapeless(<storagenetwork:im_kabel> * 8, [<ore:gemRuby>,<storagenetwork:kabel>,<storagenetwork:kabel>,<storagenetwork:kabel>,<storagenetwork:kabel>,<storagenetwork:kabel>,<storagenetwork:kabel>,<storagenetwork:kabel>,<storagenetwork:kabel>]);
recipes.addShapeless(<storagenetwork:ex_kabel> * 8, [<ore:gemPeridot>,<storagenetwork:kabel>,<storagenetwork:kabel>,<storagenetwork:kabel>,<storagenetwork:kabel>,<storagenetwork:kabel>,<storagenetwork:kabel>,<storagenetwork:kabel>,<storagenetwork:kabel>]);
recipes.addShapeless(<storagenetwork:storage_kabel> * 8, [<ore:gemTanzanite>,<storagenetwork:kabel>,<storagenetwork:kabel>,<storagenetwork:kabel>,<storagenetwork:kabel>,<storagenetwork:kabel>,<storagenetwork:kabel>,<storagenetwork:kabel>,<storagenetwork:kabel>]);
recipes.addShaped(<storagenetwork:kabel> * 8, [[null, null, null],[<ore:ingotAluminum>, <deepmoblearning:soot_covered_redstone>, <ore:ingotAluminum>], [null, null, null]]);
recipes.addShaped(<rsinfinitewireless:infinite_wireless_transmitter>, [[<enderio:block_holy_fog>, <enderio:block_holy_fog>, <enderio:block_holy_fog>],[<enderio:block_holy_fog>, <refinedstorage:wireless_transmitter>, <enderio:block_holy_fog>], [<enderio:block_holy_fog>, <enderio:block_holy_fog>, <enderio:block_holy_fog>]]);
recipes.addShaped(<refinedstorage:wireless_transmitter>, [[<extendedcrafting:material:40>], [<refinedstorage:quartz_enriched_iron>]]);
recipes.addShaped(<refinedstorage:filter> * 4, [[null, <refinedstorage:quartz_enriched_iron>, null],[<refinedstorage:quartz_enriched_iron>, <ore:paper>, <refinedstorage:quartz_enriched_iron>], [null, <refinedstorage:quartz_enriched_iron>, null]]);
recipes.addShapeless(<refinedstorage:network_card>, [<refinedstorage:upgrade:1>,<zcontent:proc_3>]);
recipes.addShapeless(<refinedstorage:upgrade:9>, [<refinedstorage:upgrade>,<ore:gemEmerald>,<ore:gemEmerald>,<ore:gemEmerald>]);
recipes.addShapeless(<refinedstorage:upgrade:8>, [<refinedstorage:upgrade>,<ore:gemEmerald>,<ore:gemEmerald>]);
recipes.addShapeless(<refinedstorage:upgrade:7>, [<refinedstorage:upgrade>,<ore:gemEmerald>]);
recipes.addShapeless(<refinedstorage:upgrade:6>, [<refinedstorage:upgrade>,<minecraft:sponge>]);
recipes.addShapeless(<refinedstorage:upgrade:3>, [<refinedstorage:upgrade>,<ore:craftingTableWood>]);
recipes.addShapeless(<refinedstorage:upgrade:4>, [<refinedstorage:upgrade>,<ore:blockGlowstone>]);
recipes.addShapeless(<refinedstorage:upgrade:2>, [<refinedstorage:upgrade>,<ore:dustGlowstone>]);
recipes.addShapeless(<refinedstorage:upgrade:1>, [<refinedstorage:upgrade>,<ore:dustEnder>]);
recipes.addShaped(<refinedstorage:upgrade> * 4, [[null, <refinedstorage:quartz_enriched_iron>, null],[<refinedstorage:quartz_enriched_iron>, <zcontent:chip2>, <refinedstorage:quartz_enriched_iron>], [null, <refinedstorage:quartz_enriched_iron>, null]]);
recipes.addShapeless(<refinedstorage:core:1>, [<refinedstorage:processor:3>, <ore:dustRedGlowstone>]);
recipes.addShapeless(<refinedstorage:core>, [<refinedstorage:processor:3>, <ore:dustCyanGlowstone>]);
recipes.addShapeless(<refinedstorage:processor:5>, [<refinedstorage:processor_binding>,<zcontent:proc_3>]);
recipes.addShapeless(<refinedstorage:processor:4>, [<refinedstorage:processor_binding>,<zcontent:proc_2>]);
recipes.addShapeless(<refinedstorage:processor:3>, [<refinedstorage:processor_binding>,<zcontent:proc_1>]);
recipes.addShapeless(<refinedstorage:crafter>, [<refinedstorage:machine_casing>,<refinedstorage:core>,<refinedstorage:core:1>]);
recipes.addShapeless(<storagedrawers:trim:5> * 4, [<futuremc:stripped_dark_oak_log>]);
recipes.addShapeless(<storagedrawers:trim:4> * 4, [<futuremc:stripped_acacia_log>]);
recipes.addShapeless(<storagedrawers:trim:3> * 4, [<futuremc:stripped_jungle_log>]);
recipes.addShapeless(<storagedrawers:trim:2> * 4, [<futuremc:stripped_birch_log>]);
recipes.addShapeless(<storagedrawers:trim:1> * 4, [<futuremc:stripped_spruce_log>]);
recipes.addShapeless(<storagedrawers:trim> * 4, [<futuremc:stripped_oak_log>]);
recipes.addShaped(<techguns:goldenrevolver>, [[<techguns:itemshared:39>, <ore:plateGold>, <minecraft:flint_and_steel>],[null, <techguns:itemshared:59>, <techguns:itemshared:44>], [null, null, null]]);
recipes.addShaped(<techguns:revolver>, [[<techguns:itemshared:38>, <ore:plateIron>, <minecraft:flint_and_steel>],[null, <techguns:itemshared:57>, <techguns:itemshared:42>], [null, null, null]]);
recipes.addShaped(<techguns:itemshared:35>, [[<ore:plateObsidianSteel>, <ore:plateObsidianSteel>, <ore:plateObsidianSteel>], [null, <techguns:itemshared:58>, <ore:ingotObsidianSteel>], [null, null, <ore:ingotObsidianSteel>]]);
recipes.addShapeless(<enderio:block_enderman_skull>, [<minecraft:skull:3>.withTag({SkullOwner: "MHF_Enderman"})]);
recipes.addShapeless(<compactstorage:compactchest>.withTag({size: [24, 10] as int[], hue: -1}), [<compactstorage:compactchest>]);
recipes.addShapeless(<compactstorage:backpack>.withTag({size: [24, 10] as int[], hue: -1}), [<compactstorage:backpack>]);
furnace.addRecipe(<thermalfoundation:material:101>, <thermalfoundation:material:165>, 5.0);
furnace.addRecipe(<thermalfoundation:material:102>, <thermalfoundation:material:166>, 5.0);
furnace.addRecipe(<thermalfoundation:material:103>, <thermalfoundation:material:167>, 5.0);
furnace.addRecipe(<redstonearsenal:material>, <redstonearsenal:material:32>);
furnace.addRecipe(<redstonerepository:material>, <redstonerepository:material:1>);
recipes.addShapeless(<thermalfoundation:material:33>, [<ore:blockSheetmetalGold>]);
recipes.addShapeless(<thermalfoundation:material:32>, [<ore:blockSheetmetalIron>]);
recipes.addShapeless(<thermalfoundation:material:352>, [<ore:blockSheetmetalSteel>]);
recipes.addShapeless(<thermalfoundation:material:353>, [<ore:blockSheetmetalElectrum>]);
recipes.addShapeless(<thermalfoundation:material:356>, [<ore:blockSheetmetalConstantan>]);
recipes.addShapeless(<immersiveengineering:metal:35>, [<ore:blockSheetmetalUranium>]);
recipes.addShapeless(<thermalfoundation:material:325>, [<ore:blockSheetmetalNickel>]);
recipes.addShapeless(<thermalfoundation:material:322>, [<ore:blockSheetmetalSilver>]);
recipes.addShapeless(<thermalfoundation:material:323>, [<ore:blockSheetmetalLead>]);
recipes.addShapeless(<thermalfoundation:material:324>, [<ore:blockSheetmetalAluminium>]);
recipes.addShapeless(<thermalfoundation:material:320>, [<ore:blockSheetmetalCopper>]);
recipes.addShaped(<minecraft:brewing_stand>, [[<ore:nuggetIron>, <ore:rodBlaze>, <ore:nuggetIron>],[null, <ore:rodBlaze>, null], [<minecraft:stone_slab>, <minecraft:stone_slab>, <minecraft:stone_slab>]]);
recipes.addShaped(<minecraft:enchanting_table>, [[<minecraft:carpet:14>, <eplus:decorative_book:1>, <minecraft:carpet:14>],[<ore:blockDiamond>, <minecraft:obsidian>, <ore:blockDiamond>], [<minecraft:obsidian>, <minecraft:obsidian>, <minecraft:obsidian>]]);
recipes.addShaped(<danknull:dank_null_5>, [[null, <danknull:dank_null_panel_5>, null],[<danknull:dank_null_panel_5>, <danknull:dank_null_panel_5>, <danknull:dank_null_panel_5>], [null, <danknull:dank_null_panel_5>, null]]);
recipes.addShaped(<danknull:dank_null_panel_5>, [[<ore:plateDenseCoal>, <ore:gemEmerald>, <ore:plateDenseCoal>],[<ore:gemEmerald>, <minecraft:stained_glass_pane:5>, <ore:gemEmerald>], [<ore:plateDenseCoal>, <ore:gemEmerald>, <ore:plateDenseCoal>]]);
recipes.addShaped(<futuremc:netherite_sword>, [[null, <ore:ingotNetherite>, null],[null, <ore:ingotNetherite>, null], [null, <ore:itemNutritiousStick>, null]]);
recipes.addShaped(<futuremc:netherite_shovel>, [[null, <ore:ingotNetherite>, null],[null, <ore:itemNutritiousStick>, null], [null, <ore:itemNutritiousStick>, null]]);
recipes.addShaped(<futuremc:netherite_pickaxe>, [[<ore:ingotNetherite>, <ore:ingotNetherite>, <ore:ingotNetherite>],[null, <ore:itemNutritiousStick>, null], [null, <ore:itemNutritiousStick>, null]]);
recipes.addShaped(<futuremc:netherite_hoe>, [[<ore:ingotNetherite>, <ore:ingotNetherite>, null],[null, <ore:itemNutritiousStick>, null], [null, <ore:itemNutritiousStick>, null]]);
recipes.addShaped(<futuremc:netherite_axe>, [[<ore:ingotNetherite>, <ore:ingotNetherite>, null],[<ore:ingotNetherite>, <ore:itemNutritiousStick>, null], [null, <ore:itemNutritiousStick>, null]]);
recipes.addShapeless(<thermalfoundation:coin:96> * 3, [<ore:plateSteel>,<immersiveengineering:tool> | <tp:stone_hammer>,<immersiveengineering:tool:1>]);
recipes.addShaped(<furnus:pulvus>, [[<quark:charred_nether_bricks>, <quark:charred_nether_bricks>, <quark:charred_nether_bricks>],[<quark:charred_nether_bricks>, <quark:charred_nether_brick_slab>, <quark:charred_nether_bricks>], [<ore:stonePolished>, <ore:slabStone>, <ore:stonePolished>]]);
recipes.addShaped(<furnus:furnus>, [[<minecraft:brick_block>, <minecraft:brick_block>, <minecraft:brick_block>],[<minecraft:brick_block>, <ore:slabBricks>, <minecraft:brick_block>], [<ore:stonePolished>, <ore:slabStone>, <ore:stonePolished>]]);
recipes.addShaped(<futuremc:smithing_table>, [[<ore:plateNetherite>, <ore:plateNetherite>, <ore:plateNetherite>],[<immersiveengineering:tool>.noReturn(), <ore:plankTreatedWood>, <immersiveengineering:tool:1>.noReturn()], [<ore:plankTreatedWood>, <ore:plankTreatedWood>, <ore:plankTreatedWood>]]);
recipes.addShaped(<minecraft:anvil>, [[<zcontent:iron_stone>, <zcontent:iron_stone>, <zcontent:iron_stone>],[null, <ore:ingotConstructionAlloy>, null], [<ore:ingotConstructionAlloy>, <ore:ingotConstructionAlloy>, <ore:ingotConstructionAlloy>]]);
recipes.addShapeless(<jaopca:item_dustconstructionalloy> * 2, [<ore:dustIron>,<ore:dustIron>,<ore:dustGraphite>]);
recipes.addShapeless(<thermalfoundation:material:32>,[<immersiveengineering:tool> | <tp:stone_hammer>,<ore:ingotIron>]);
recipes.addShapeless(<thermalfoundation:material:33>,[<immersiveengineering:tool> | <tp:stone_hammer>,<ore:ingotGold>]);
recipes.addShapeless(<thermalfoundation:material:320>,[<immersiveengineering:tool> | <tp:stone_hammer>,<ore:ingotCopper>]);
recipes.addShapeless(<thermalfoundation:material:321>,[<immersiveengineering:tool> | <tp:stone_hammer>,<ore:ingotTin>]);
recipes.addShapeless(<thermalfoundation:material:322>,[<immersiveengineering:tool> | <tp:stone_hammer>,<ore:ingotSilver>]);
recipes.addShapeless(<thermalfoundation:material:323>,[<immersiveengineering:tool> | <tp:stone_hammer>,<ore:ingotLead>]);
recipes.addShapeless(<thermalfoundation:material:324>,[<immersiveengineering:tool> | <tp:stone_hammer>,<ore:ingotAluminum>]);
recipes.addShapeless(<thermalfoundation:material:325>,[<immersiveengineering:tool> | <tp:stone_hammer>,<ore:ingotNickel>]);
recipes.addShapeless(<thermalfoundation:material:326>,[<immersiveengineering:tool> | <tp:stone_hammer>,<ore:ingotPlatinum>]);
recipes.addShapeless(<thermalfoundation:material:327>,[<immersiveengineering:tool> | <tp:stone_hammer>,<ore:ingotIridium>]);
recipes.addShapeless(<thermalfoundation:material:328>,[<immersiveengineering:tool> | <tp:stone_hammer>,<ore:ingotMithril>]);
recipes.addShapeless(<thermalfoundation:material:352>,[<immersiveengineering:tool> | <tp:stone_hammer>,<ore:ingotSteel>]);
recipes.addShapeless(<thermalfoundation:material:353>,[<immersiveengineering:tool> | <tp:stone_hammer>,<ore:ingotElectrum>]);
recipes.addShapeless(<thermalfoundation:material:354>,[<immersiveengineering:tool> | <tp:stone_hammer>,<ore:ingotInvar>]);
recipes.addShapeless(<thermalfoundation:material:355>,[<immersiveengineering:tool> | <tp:stone_hammer>,<ore:ingotBronze>]);
recipes.addShapeless(<thermalfoundation:material:356>,[<immersiveengineering:tool> | <tp:stone_hammer>,<ore:ingotConstantan>]);
recipes.addShapeless(<thermalfoundation:material:357>,[<immersiveengineering:tool> | <tp:stone_hammer>,<ore:ingotSignalum>]);
recipes.addShapeless(<thermalfoundation:material:358>,[<immersiveengineering:tool> | <tp:stone_hammer>,<ore:ingotLumium>]);
recipes.addShapeless(<thermalfoundation:material:359>,[<immersiveengineering:tool> | <tp:stone_hammer>,<ore:ingotEnderium>]);
recipes.addShapeless(<redstonearsenal:material:128>,[<immersiveengineering:tool> | <tp:stone_hammer>,<ore:ingotElectrumFlux>]);
recipes.addShapeless(<redstonerepository:material:4>,[<immersiveengineering:tool> | <tp:stone_hammer>,<ore:ingotGelidEnderium>]);
recipes.addShapeless(<immersiveengineering:metal:35>,[<immersiveengineering:tool> | <tp:stone_hammer>,<ore:ingotUranium>]);
recipes.addShapeless(<techguns:itemshared:53>,[<immersiveengineering:tool> | <tp:stone_hammer>,<ore:ingotCarbon>]);
recipes.addShapeless(<techguns:itemshared:51>,[<immersiveengineering:tool> | <tp:stone_hammer>,<ore:ingotObsidianSteel>]);
recipes.addShapeless(<techguns:itemshared:54>,[<immersiveengineering:tool> | <tp:stone_hammer>,<ore:ingotTitanium>]);
recipes.addShapeless(<thermalfoundation:material:324>,[<immersiveengineering:tool> | <tp:stone_hammer>,<ore:ingotAluminium>]);
recipes.addShapeless(<jaopca:item_platenetherite>,[<immersiveengineering:tool> | <tp:stone_hammer>,<ore:ingotNetherite>]);
recipes.addShapeless(<jaopca:item_plateardite>,[<immersiveengineering:tool> | <tp:stone_hammer>,<ore:ingotArdite>]);
recipes.addShapeless(<jaopca:item_platecobalt>,[<immersiveengineering:tool> | <tp:stone_hammer>,<ore:ingotCobalt>]);
recipes.addShapeless(<jaopca:item_platedraconium>,[<immersiveengineering:tool> | <tp:stone_hammer>,<ore:ingotDraconium>]);
recipes.addShapeless(<jaopca:item_plateamber>,[<immersiveengineering:tool> | <tp:stone_hammer>,<ore:gemAmber>]);
recipes.addShapeless(<jaopca:item_plateamethyst>,[<immersiveengineering:tool> | <tp:stone_hammer>,<ore:gemAmethyst>]);
recipes.addShapeless(<jaopca:item_platecoal>,[<immersiveengineering:tool> | <tp:stone_hammer>,<ore:gemCoal>]);
recipes.addShapeless(<jaopca:item_platediamond>,[<immersiveengineering:tool> | <tp:stone_hammer>,<ore:gemDiamond>]);
recipes.addShapeless(<jaopca:item_platedimensionalshard>,[<immersiveengineering:tool> | <tp:stone_hammer>,<ore:gemDimensionalShard>]);
recipes.addShapeless(<jaopca:item_plateemerald>,[<immersiveengineering:tool> | <tp:stone_hammer>,<ore:gemEmerald>]);
recipes.addShapeless(<jaopca:item_platelapis>,[<immersiveengineering:tool> | <tp:stone_hammer>,<ore:gemLapis>]);
recipes.addShapeless(<jaopca:item_platemalachite>,[<immersiveengineering:tool> | <tp:stone_hammer>,<ore:gemMalachite>]);
recipes.addShapeless(<jaopca:item_plateperidot>,[<immersiveengineering:tool> | <tp:stone_hammer>,<ore:gemPeridot>]);
recipes.addShapeless(<jaopca:item_platequartz>,[<immersiveengineering:tool> | <tp:stone_hammer>,<ore:gemQuartz>]);
recipes.addShapeless(<jaopca:item_platequartzblack>,[<immersiveengineering:tool> | <tp:stone_hammer>,<ore:gemQuartzBlack>]);
recipes.addShapeless(<jaopca:item_plateruby>,[<immersiveengineering:tool> | <tp:stone_hammer>,<ore:gemRuby>]);
recipes.addShapeless(<jaopca:item_platesapphire>,[<immersiveengineering:tool> | <tp:stone_hammer>,<ore:gemSapphire>]);
recipes.addShapeless(<jaopca:item_platetanzanite>,[<immersiveengineering:tool> | <tp:stone_hammer>,<ore:gemTanzanite>]);
recipes.addShapeless(<jaopca:item_platetopaz>,[<immersiveengineering:tool> | <tp:stone_hammer>,<ore:gemTopaz>]);
recipes.addShapeless(<jaopca:item_platebrass>,[<immersiveengineering:tool> | <tp:stone_hammer>,<ore:ingotBrass>]);
recipes.addShapeless(<jaopca:item_platebaseessence>,[<immersiveengineering:tool> | <tp:stone_hammer>,<ore:ingotBaseEssence>]);
recipes.addShapeless(<jaopca:item_plateblackiron>,[<immersiveengineering:tool> | <tp:stone_hammer>,<ore:ingotBlackIron>]);
recipes.addShapeless(<jaopca:item_platecoldiron>,[<immersiveengineering:tool> | <tp:stone_hammer>,<ore:ingotColdiron>]);
recipes.addShapeless(<jaopca:item_plateconductiveiron>,[<immersiveengineering:tool> | <tp:stone_hammer>,<ore:ingotConductiveIron>]);
recipes.addShapeless(<jaopca:item_plateconstructionalloy>,[<immersiveengineering:tool> | <tp:stone_hammer>,<ore:ingotConstructionAlloy>]);
recipes.addShapeless(<jaopca:item_platecosmicneutronium>,[<immersiveengineering:tool> | <tp:stone_hammer>,<ore:ingotCosmicNeutronium>]);
recipes.addShapeless(<jaopca:item_platecrudesteel>,[<immersiveengineering:tool> | <tp:stone_hammer>,<ore:ingotCrudeSteel>]);
recipes.addShapeless(<jaopca:item_platecrystallinealloy>,[<immersiveengineering:tool> | <tp:stone_hammer>,<ore:ingotCrystallineAlloy>]);
recipes.addShapeless(<jaopca:item_platecrystallinepinkslime>,[<immersiveengineering:tool> | <tp:stone_hammer>,<ore:ingotCrystallinePinkSlime>]);
recipes.addShapeless(<jaopca:item_platecrystalmatrix>,[<immersiveengineering:tool> | <tp:stone_hammer>,<ore:ingotCrystalMatrix>]);
recipes.addShapeless(<jaopca:item_platecrystaltine>,[<immersiveengineering:tool> | <tp:stone_hammer>,<ore:ingotCrystaltine>]);
recipes.addShapeless(<jaopca:item_platedarksteel>,[<immersiveengineering:tool> | <tp:stone_hammer>,<ore:ingotDarkSteel>]);
recipes.addShapeless(<jaopca:item_platedemonicmetal>,[<immersiveengineering:tool> | <tp:stone_hammer>,<ore:ingotDemonicMetal>]);
recipes.addShapeless(<jaopca:item_platedraconiumawakened>,[<immersiveengineering:tool> | <tp:stone_hammer>,<ore:ingotDraconiumAwakened>]);
recipes.addShapeless(<jaopca:item_plateelectricalsteel>,[<immersiveengineering:tool> | <tp:stone_hammer>,<ore:ingotElectricalSteel>]);
recipes.addShapeless(<jaopca:item_plateelectrofluxalloy>,[<immersiveengineering:tool> | <tp:stone_hammer>,<ore:ingotElectroFluxAlloy>]);
recipes.addShapeless(<jaopca:item_plateelectrotinealloy>,[<immersiveengineering:tool> | <tp:stone_hammer>,<ore:ingotElectrotineAlloy>]);
recipes.addShapeless(<jaopca:item_plateenchantedmetal>,[<immersiveengineering:tool> | <tp:stone_hammer>,<ore:ingotEnchantedMetal>]);
recipes.addShapeless(<jaopca:item_plateendsteel>,[<immersiveengineering:tool> | <tp:stone_hammer>,<ore:ingotEndSteel>]);
recipes.addShapeless(<jaopca:item_plateenergeticalloy>,[<immersiveengineering:tool> | <tp:stone_hammer>,<ore:ingotEnergeticAlloy>]);
recipes.addShapeless(<jaopca:item_plateenergeticsilver>,[<immersiveengineering:tool> | <tp:stone_hammer>,<ore:ingotEnergeticSilver>]);
recipes.addShapeless(<jaopca:item_plateevilmetal>,[<immersiveengineering:tool> | <tp:stone_hammer>,<ore:ingotEvilMetal>]);
recipes.addShapeless(<jaopca:item_plateevilterraglaz>,[<immersiveengineering:tool> | <tp:stone_hammer>,<ore:ingotEvilTerraglaz>]);
recipes.addShapeless(<jaopca:item_platefluxalloy>,[<immersiveengineering:tool> | <tp:stone_hammer>,<ore:ingotFluxAlloy>]);
recipes.addShapeless(<jaopca:item_plategalvanizedsteel>,[<immersiveengineering:tool> | <tp:stone_hammer>,<ore:ingotGalvanizedsteel>]);
recipes.addShapeless(<jaopca:item_plategraphite>,[<immersiveengineering:tool> | <tp:stone_hammer>,<ore:ingotGraphite>]);
recipes.addShapeless(<jaopca:item_platehopgraphite>,[<immersiveengineering:tool> | <tp:stone_hammer>,<ore:ingotHOPGraphite>]);
recipes.addShapeless(<jaopca:item_plateinferium>,[<immersiveengineering:tool> | <tp:stone_hammer>,<ore:ingotInferium>]);
recipes.addShapeless(<jaopca:item_plateinfinity>,[<immersiveengineering:tool> | <tp:stone_hammer>,<ore:ingotInfinity>]);
recipes.addShapeless(<jaopca:item_plateinsanium>,[<immersiveengineering:tool> | <tp:stone_hammer>,<ore:ingotInsanium>]);
recipes.addShapeless(<jaopca:item_plateintermedium>,[<immersiveengineering:tool> | <tp:stone_hammer>,<ore:ingotIntermedium>]);
recipes.addShapeless(<jaopca:item_platemanyullyn>,[<immersiveengineering:tool> | <tp:stone_hammer>,<ore:ingotManyullyn>]);
recipes.addShapeless(<jaopca:item_platemelodicalloy>,[<immersiveengineering:tool> | <tp:stone_hammer>,<ore:ingotMelodicAlloy>]);
recipes.addShapeless(<jaopca:item_platenichrome>,[<immersiveengineering:tool> | <tp:stone_hammer>,<ore:ingotNichrome>]);
recipes.addShapeless(<jaopca:item_plateprudentium>,[<immersiveengineering:tool> | <tp:stone_hammer>,<ore:ingotPrudentium>]);
recipes.addShapeless(<jaopca:item_platepulsatingiron>,[<immersiveengineering:tool> | <tp:stone_hammer>,<ore:ingotPulsatingIron>]);
recipes.addShapeless(<jaopca:item_plateredstonealloy>,[<immersiveengineering:tool> | <tp:stone_hammer>,<ore:ingotRedstoneAlloy>]);
recipes.addShapeless(<jaopca:item_platesoularium>,[<immersiveengineering:tool> | <tp:stone_hammer>,<ore:ingotSoularium>]);
recipes.addShapeless(<jaopca:item_platesoulium>,[<immersiveengineering:tool> | <tp:stone_hammer>,<ore:ingotSoulium>]);
recipes.addShapeless(<jaopca:item_platestainlesssteel>,[<immersiveengineering:tool> | <tp:stone_hammer>,<ore:ingotStainlesssteel>]);
recipes.addShapeless(<jaopca:item_platestellaralloy>,[<immersiveengineering:tool> | <tp:stone_hammer>,<ore:ingotStellarAlloy>]);
recipes.addShapeless(<jaopca:item_platesuperium>,[<immersiveengineering:tool> | <tp:stone_hammer>,<ore:ingotSuperium>]);
recipes.addShapeless(<jaopca:item_platesupremium>,[<immersiveengineering:tool> | <tp:stone_hammer>,<ore:ingotSupremium>]);
recipes.addShapeless(<jaopca:item_plateterraglaz>,[<immersiveengineering:tool> | <tp:stone_hammer>,<ore:ingotTerraglaz>]);
recipes.addShapeless(<jaopca:item_plateultimate>,[<immersiveengineering:tool> | <tp:stone_hammer>,<ore:ingotUltimate>]);
recipes.addShapeless(<jaopca:item_plateunstable>,[<immersiveengineering:tool> | <tp:stone_hammer>,<ore:ingotUnstable>]);
recipes.addShapeless(<jaopca:item_plateuraniumenriched>,[<immersiveengineering:tool> | <tp:stone_hammer>,<ore:ingotUraniumEnriched>]);
recipes.addShapeless(<jaopca:item_platevibrantalloy>,[<immersiveengineering:tool> | <tp:stone_hammer>,<ore:ingotVibrantAlloy>]);
recipes.addShapeless(<jaopca:item_platevividalloy>,[<immersiveengineering:tool> | <tp:stone_hammer>,<ore:ingotVividAlloy>]);
recipes.addShapeless(<jaopca:item_platecrystalblack>,[<immersiveengineering:tool> | <tp:stone_hammer>,<ore:gemCrystalBlack>]);
recipes.addShapeless(<jaopca:item_platecrystalblue>,[<immersiveengineering:tool> | <tp:stone_hammer>,<ore:gemCrystalBlue>]);
recipes.addShapeless(<jaopca:item_platecrystalflux>,[<immersiveengineering:tool> | <tp:stone_hammer>,<ore:gemCrystalFlux>]);
recipes.addShapeless(<jaopca:item_platecrystalgreen>,[<immersiveengineering:tool> | <tp:stone_hammer>,<ore:gemCrystalGreen>]);
recipes.addShapeless(<jaopca:item_platecrystalindigo>,[<immersiveengineering:tool> | <tp:stone_hammer>,<ore:gemCrystalIndigo>]);
recipes.addShapeless(<jaopca:item_platecrystalorange>,[<immersiveengineering:tool> | <tp:stone_hammer>,<ore:gemCrystalOrange>]);
recipes.addShapeless(<jaopca:item_platecrystalred>,[<immersiveengineering:tool> | <tp:stone_hammer>,<ore:gemCrystalRed>]);
recipes.addShapeless(<jaopca:item_platecrystalviolet>,[<immersiveengineering:tool> | <tp:stone_hammer>,<ore:gemCrystalViolet>]);
recipes.addShapeless(<jaopca:item_platecrystalwhite>,[<immersiveengineering:tool> | <tp:stone_hammer>,<ore:gemCrystalWhite>]);
recipes.addShapeless(<jaopca:item_platecrystalyellow>,[<immersiveengineering:tool> | <tp:stone_hammer>,<ore:gemCrystalYellow>]);
recipes.addShapeless(<jaopca:item_plategelid>,[<immersiveengineering:tool> | <tp:stone_hammer>,<ore:gemGelid>]);
recipes.addShapeless(<jaopca:item_platemoon>,[<immersiveengineering:tool> | <tp:stone_hammer>,<ore:gemMoon>]);
recipes.addShapeless(<jaopca:item_plateobsidian>,[<immersiveengineering:tool> | <tp:stone_hammer>,<ore:gemObsidian>]);
recipes.addShapeless(<jaopca:item_plateprismarine>,[<immersiveengineering:tool> | <tp:stone_hammer>,<ore:gemPrismarine>]);
recipes.addShapeless(<refinedstorage:quartz_enriched_iron> * 9, [<refinedstorage:quartz_enriched_iron_block>]);
recipes.addShaped(<tp:infin_bucket>, [[null, <mysticalagriculture:crafting:4>, null],[<mysticalagriculture:crafting:4>, <randomthings:reinforcedenderbucket>.withTag({Fluid: {FluidName: "water", Amount: 10000}}).onlyWithTag({Fluid: {FluidName: "water", Amount: 10000}}), <mysticalagriculture:crafting:4>], [null, <mysticalagriculture:crafting:4>, null]]);
recipes.addShapeless(<jaopca:item_dustinsanium>, [<ore:essenceInsanium>,<ore:essenceInsanium>,<ore:essenceInsanium>,<ore:essenceInsanium>,<ore:dustSupremium>,<ore:essenceInsanium>,<ore:essenceInsanium>,<ore:essenceInsanium>,<ore:essenceInsanium>]);
recipes.addShapeless(<jaopca:item_dustsupremium>, [<ore:essenceSupremium>,<ore:essenceSupremium>,<ore:essenceSupremium>,<ore:essenceSupremium>,<ore:dustSuperium>,<ore:essenceSupremium>,<ore:essenceSupremium>,<ore:essenceSupremium>,<ore:essenceSupremium>]);
recipes.addShapeless(<jaopca:item_dustsuperium>, [<ore:essenceSuperium>,<ore:essenceSuperium>,<ore:essenceSuperium>,<ore:essenceSuperium>,<ore:dustIntermedium>,<ore:essenceSuperium>,<ore:essenceSuperium>,<ore:essenceSuperium>,<ore:essenceSuperium>]);
recipes.addShapeless(<jaopca:item_dustintermedium>, [<ore:essenceIntermedium>,<ore:essenceIntermedium>,<ore:essenceIntermedium>,<ore:essenceIntermedium>,<ore:dustPrudentium>,<ore:essenceIntermedium>,<ore:essenceIntermedium>,<ore:essenceIntermedium>,<ore:essenceIntermedium>]);
recipes.addShapeless(<jaopca:item_dustprudentium>, [<ore:essencePrudentium>,<ore:essencePrudentium>,<ore:essencePrudentium>,<ore:essencePrudentium>,<ore:dustInferium>,<ore:essencePrudentium>,<ore:essencePrudentium>,<ore:essencePrudentium>,<ore:essencePrudentium>]);
recipes.addShapeless(<jaopca:item_dustinferium>, [<ore:essenceInferium>,<ore:essenceInferium>,<ore:essenceInferium>,<ore:essenceInferium>,<ore:dustBaseEssence>,<ore:essenceInferium>,<ore:essenceInferium>,<ore:essenceInferium>,<ore:essenceInferium>]);
recipes.addShaped(<cookingforblockheads:sink>, [[<ore:ingotIron>, <ore:ingotIron>, <ore:ingotIron>], [<minecraft:hardened_clay>, <tp:infin_bucket>, <minecraft:hardened_clay>], [<minecraft:hardened_clay>, <minecraft:hardened_clay>, <minecraft:hardened_clay>]]);
recipes.addShapeless(<minecraft:flint_and_steel>.withTag({Unbreakable:1}), [<ore:ingotSteel>, <minecraft:flint>]);
recipes.addShapeless(<tp:asphalt_block> * 512, [<ore:sand>,<ore:sand>,<minecraft:gravel>,<ore:blockGravel>,<thermalfoundation:material:833>,<immersivepetroleum:material>,<immersivepetroleum:material>,<biomesoplenty:ash>,<biomesoplenty:ash>]);
recipes.addShaped(<zcontent:stainless_steel_pick>.withTag({Unbreakable:1}), [[<ore:ingotStainlesssteel>, <ore:ingotStainlesssteel>, <ore:ingotStainlesssteel>],[null, <ore:stickTreatedWood>, null], [null, <ore:stickTreatedWood>, null]]);
recipes.addShaped(<zcontent:stainless_steel_shovel>.withTag({Unbreakable:1}), [[null, <ore:ingotStainlesssteel>, null],[null, <ore:stickTreatedWood>, null], [null, <ore:stickTreatedWood>, null]]);
recipes.addShaped(<zcontent:stainless_steel_axe>.withTag({Unbreakable:1}), [[<ore:ingotStainlesssteel>, <ore:ingotStainlesssteel>, null],[<ore:ingotStainlesssteel>, <ore:stickTreatedWood>, null], [null, <ore:stickTreatedWood>, null]]);
recipes.addShaped(<zcontent:stainless_steel_sword>.withTag({Unbreakable:1}), [[null, <ore:ingotStainlesssteel>, null],[null, <ore:ingotStainlesssteel>, null], [null, <ore:stickTreatedWood>, null]]);
recipes.addShaped(<zcontent:mastersword1>, [[null, <zcontent:masterswordblade>, null],[null, <zcontent:masterswordcore>, null], [null, <zcontent:masterswordgrip>, null]]);
recipes.addShapeless(<tp:bread_slice> * 20, [<minecraft:bread>,<minecraft:bread>]);
recipes.addShaped(<quantumstorage:chest_quantum>, [[<ore:plankWood>, <ore:stickEmerald>, <ore:plankWood>],[<ore:stickEmerald>, <ore:pressurePlateWood>, <ore:stickEmerald>], [<ore:plankWood>, <ore:stickEmerald>, <ore:plankWood>]]);
recipes.addShaped(<quantumstorage:chest_diamond>, [[<ore:plankWood>, <ore:stickDiamond>, <ore:plankWood>],[<ore:stickDiamond>, <ore:pressurePlateWood>, <ore:stickDiamond>], [<ore:plankWood>, <ore:stickDiamond>, <ore:plankWood>]]);
recipes.addShaped(<quantumstorage:chest_gold>, [[<ore:plankWood>, <ore:stickGold>, <ore:plankWood>],[<ore:stickGold>, <ore:pressurePlateWood>, <ore:stickGold>], [<ore:plankWood>, <ore:stickGold>, <ore:plankWood>]]);
recipes.addShaped(<quantumstorage:chest_iron>, [[<ore:plankWood>, <ore:stickIron>, <ore:plankWood>],[<ore:stickIron>, <ore:pressurePlateWood>, <ore:stickIron>], [<ore:plankWood>, <ore:stickIron>, <ore:plankWood>]]);
recipes.addShapeless(<biomesoplenty:ash> * 9, [<biomesoplenty:ash_block>]);
recipes.addShaped(<darkutils:wither_block>, [[<ore:dustAsh>, <ore:dustAsh>], [<ore:dustAsh>, <ore:dustAsh>]]);
recipes.addShaped(<darkutils:material:3> * 8, [[<minecraft:sugar:*>, <minecraft:sugar:*>, <minecraft:sugar:*>], [<minecraft:sugar:*>, <darkutils:material:*>, <minecraft:sugar:*>], [<minecraft:sugar:*>, <minecraft:sugar:*>, <minecraft:sugar:*>]]);
recipes.addShaped(<darkutils:trap_tile:5>, [[<ore:stone>, <ore:dustAsh>, <ore:stone>]]);
recipes.addShapeless(<darkutils:material:2>, [<ore:dustAsh>, <ore:slimeball>]);
recipes.addShapeless(<minecraft:dye:8> * 2, [<ore:dustAsh>]);
recipes.addShapeless(<biomesoplenty:ash_block>, [<ore:dustAsh>, <ore:dustAsh>, <ore:dustAsh>, <ore:dustAsh>, <ore:dustAsh>, <ore:dustAsh>, <ore:dustAsh>, <ore:dustAsh>, <ore:dustAsh>]);
recipes.addShapeless(<zcontent:charcoal_tiny_small> * 8, [<ore:charcoal>]);
recipes.addShapeless(<zcontent:coal_tiny_small> * 8, [<ore:gemCoal>]);
recipes.addShapeless(<minecraft:coal:1>, [<zcontent:charcoal_tiny_small>,<zcontent:charcoal_tiny_small>,<zcontent:charcoal_tiny_small>,<zcontent:charcoal_tiny_small>,<zcontent:charcoal_tiny_small>,<zcontent:charcoal_tiny_small>,<zcontent:charcoal_tiny_small>,<zcontent:charcoal_tiny_small>]);
recipes.addShapeless(<minecraft:coal>, [<zcontent:coal_tiny_small>,<zcontent:coal_tiny_small>,<zcontent:coal_tiny_small>,<zcontent:coal_tiny_small>,<zcontent:coal_tiny_small>,<zcontent:coal_tiny_small>,<zcontent:coal_tiny_small>,<zcontent:coal_tiny_small>]);
recipes.addShaped(<actuallyadditions:block_misc:9>, [[<ore:plateIron>, <ore:ingotFluxAlloy>, <ore:plateIron>],[<ore:ingotFluxAlloy>, <ore:gearBrass>, <ore:ingotFluxAlloy>], [<ore:plateIron>, <ore:ingotFluxAlloy>, <ore:plateIron>]]);
recipes.addShaped(<rftools:machine_base> * 16, [[null, null, null],[<ore:ingotStainlesssteel>, <ore:ingotFluxAlloy>, <ore:ingotStainlesssteel>], [null, null, null]]);
recipes.addShaped(<actuallyadditions:item_misc:8>, [[null, <ore:wireGold>, <quark:spruce_pressure_plate>],[<ore:wireGold>, <ore:stickTreatedWood>, <ore:wireGold>], [<quark:spruce_pressure_plate>, <ore:wireGold>, null]]);
recipes.addShaped(<actuallyadditions:item_misc:7>, [[null, <ore:wireAluminum>, <quark:spruce_pressure_plate>],[<ore:wireAluminum>, <ore:stickTreatedWood>, <ore:wireAluminum>], [<quark:spruce_pressure_plate>, <ore:wireAluminum>, null]]);
recipes.addShaped(<extrautils2:teleporter:1>, [[<extrautils2:compressedcobblestone:7>, <extrautils2:compressedcobblestone:6>, <extrautils2:compressedcobblestone:7>],[<extrautils2:compressedcobblestone:6>, <draconicevolution:dislocator>, <extrautils2:compressedcobblestone:6>], [<extrautils2:compressedcobblestone:7>, <extrautils2:compressedcobblestone:6>, <extrautils2:compressedcobblestone:7>]]);
recipes.addShapeless(<minecraft:bedrock>, [<extrautils2:decorativebedrock:1>]);
recipes.addShapeless(<extrautils2:decorativebedrock:1>, [<extrautils2:decorativebedrock>]);
recipes.addShapeless(<extrautils2:decorativebedrock>, [<minecraft:bedrock>,<minecraft:bedrock>,<minecraft:bedrock>,<minecraft:bedrock>]);
recipes.addShapeless(<projecte:item.pe_tome>, [<biomesoplenty:earth>]);
furnace.addRecipe(<minecraft:bedrock>, <extrautils2:decorativebedrock:2>, 50.0);
recipes.addShaped(<tp:lava_infused_stone>, [[<tp:hardened_stone>, <mysticalagriculture:fire_essence>, <tp:hardened_stone>],[<mysticalagriculture:fire_essence>, <tp:hardened_stone>, <mysticalagriculture:fire_essence>], [<tp:hardened_stone>, <mysticalagriculture:fire_essence>, <tp:hardened_stone>]]);
recipes.addShaped(<modularmachinery:blockcasing:4>, [[<ore:ingotObsidianSteel>, <modularmachinery:itemmodularium>, <ore:ingotObsidianSteel>], [<modularmachinery:itemmodularium>, <actuallyadditions:block_crystal_empowered>, <modularmachinery:itemmodularium>], [<ore:ingotObsidianSteel>, <modularmachinery:itemmodularium>, <ore:ingotObsidianSteel>]]);
recipes.addShaped(<modularmachinery:blockcasing:1>, [[<modularmachinery:itemmodularium>, <minecraft:iron_bars>, <modularmachinery:itemmodularium>], [<ore:plateIron>, <actuallyadditions:block_crystal_empowered>, <ore:plateIron>], [<modularmachinery:itemmodularium>, <minecraft:iron_bars>, <modularmachinery:itemmodularium>]]);
recipes.addShaped(<modularmachinery:blockcasing:2>, [[<modularmachinery:itemmodularium>, <minecraft:flint>, <modularmachinery:itemmodularium>], [<ore:plateIron>, <actuallyadditions:block_crystal_empowered>, <ore:plateIron>], [<modularmachinery:itemmodularium>, <minecraft:flint>, <modularmachinery:itemmodularium>]]);
recipes.addShaped(<modularmachinery:blockcasing:3>, [[<modularmachinery:itemmodularium>, <techguns:itemshared:57>, <modularmachinery:itemmodularium>], [<ore:plateIron>, <actuallyadditions:block_crystal_empowered>, <ore:plateIron>], [<modularmachinery:itemmodularium>, <techguns:itemshared:57>, <modularmachinery:itemmodularium>]]);
recipes.addShaped(<modularmachinery:blockcasing>, [[null, <modularmachinery:itemmodularium>, null], [<modularmachinery:itemmodularium>, <actuallyadditions:block_crystal_empowered>, <modularmachinery:itemmodularium>], [null, <modularmachinery:itemmodularium>, null]]);
recipes.addShaped(<modularmachinery:blockcasing:5>, [[<modularmachinery:itemmodularium>, <techguns:itemshared:65>, <modularmachinery:itemmodularium>], [<ore:plateIron>, <actuallyadditions:block_crystal_empowered>, <ore:plateIron>], [<modularmachinery:itemmodularium>, <techguns:itemshared:65>, <modularmachinery:itemmodularium>]]);
recipes.addShaped(<modularmachinery:blockcontroller>, [[<modularmachinery:itemmodularium>, <extrautils2:screen>, <modularmachinery:itemmodularium>], [<refinedstorage:processor:4>, <actuallyadditions:block_crystal_empowered>, <refinedstorage:processor:4>], [<modularmachinery:itemmodularium>, <zcontent:server2>, <modularmachinery:itemmodularium>]]);
recipes.addShaped(<modularmachinery:blockenergyoutputhatch>, [[<ore:gemCrystalFlux>], [<modularmachinery:blockcasing>], [<minecraft:hopper>]]);
recipes.addShaped(<modularmachinery:blockenergyoutputhatch:1>, [[<ore:gemCrystalFlux>], [<modularmachinery:blockenergyoutputhatch>], [<minecraft:hopper>]]);
recipes.addShaped(<modularmachinery:blockenergyoutputhatch:2>, [[<ore:gemCrystalFlux>], [<modularmachinery:blockenergyoutputhatch:1>], [<minecraft:hopper>]]);
recipes.addShaped(<modularmachinery:blockenergyoutputhatch:3>, [[<ore:gemCrystalFlux>], [<modularmachinery:blockenergyoutputhatch:2>], [<minecraft:hopper>]]);
recipes.addShaped(<modularmachinery:blockenergyoutputhatch:4>, [[<ore:gemCrystalFlux>], [<modularmachinery:blockenergyoutputhatch:3>], [<minecraft:hopper>]]);
recipes.addShaped(<modularmachinery:blockenergyoutputhatch:5>, [[<ore:gemCrystalFlux>], [<modularmachinery:blockenergyoutputhatch:4>], [<minecraft:hopper>]]);
recipes.addShaped(<modularmachinery:blockenergyoutputhatch:6>, [[<ore:gemCrystalFlux>], [<modularmachinery:blockenergyoutputhatch:5>], [<minecraft:hopper>]]);
recipes.addShaped(<modularmachinery:blockenergyoutputhatch:7>, [[null, <ore:gemCrystalFlux>], [<quantumstorage:quantum_battery>, <modularmachinery:blockenergyoutputhatch:6>, <quantumstorage:quantum_battery>], [null, <minecraft:hopper>]]);
recipes.addShaped(<modularmachinery:blockenergyinputhatch>, [[<minecraft:hopper>], [<modularmachinery:blockcasing>], [<ore:gemCrystalFlux>]]);
recipes.addShaped(<modularmachinery:blockenergyinputhatch:1>, [[<minecraft:hopper>], [<modularmachinery:blockenergyinputhatch>], [<ore:gemCrystalFlux>]]);
recipes.addShaped(<modularmachinery:blockenergyinputhatch:2>, [[<minecraft:hopper>], [<modularmachinery:blockenergyinputhatch:1>], [<ore:gemCrystalFlux>]]);
recipes.addShaped(<modularmachinery:blockenergyinputhatch:3>, [[<minecraft:hopper>], [<modularmachinery:blockenergyinputhatch:2>], [<ore:gemCrystalFlux>]]);
recipes.addShaped(<modularmachinery:blockenergyinputhatch:4>, [[<minecraft:hopper>], [<modularmachinery:blockenergyinputhatch:3>], [<ore:gemCrystalFlux>]]);
recipes.addShaped(<modularmachinery:blockenergyinputhatch:5>, [[<minecraft:hopper>], [<modularmachinery:blockenergyinputhatch:4>], [<ore:gemCrystalFlux>]]);
recipes.addShaped(<modularmachinery:blockenergyinputhatch:6>, [[<minecraft:hopper>], [<modularmachinery:blockenergyinputhatch:5>], [<ore:gemCrystalFlux>]]);
recipes.addShaped(<modularmachinery:blockenergyinputhatch:7>, [[null, <minecraft:hopper>], [<quantumstorage:quantum_battery>, <modularmachinery:blockenergyinputhatch:6>, <quantumstorage:quantum_battery>], [null, <ore:gemCrystalFlux>]]);
recipes.addShaped(<modularmachinery:blockoutputbus>, [[<ore:chest>], [<modularmachinery:blockcasing>], [<minecraft:hopper>]]);
recipes.addShaped(<modularmachinery:blockoutputbus:1>, [[<ore:chest>], [<modularmachinery:blockoutputbus>], [<minecraft:hopper>]]);
recipes.addShaped(<modularmachinery:blockoutputbus:2>, [[<ore:chest>], [<modularmachinery:blockoutputbus:1>], [<minecraft:hopper>]]);
recipes.addShaped(<modularmachinery:blockoutputbus:3>, [[<ore:chest>], [<modularmachinery:blockoutputbus:2>], [<minecraft:hopper>]]);
recipes.addShaped(<modularmachinery:blockoutputbus:4>, [[<ore:chest>], [<modularmachinery:blockoutputbus:3>], [<minecraft:hopper>]]);
recipes.addShaped(<modularmachinery:blockoutputbus:5>, [[<ore:chest>], [<modularmachinery:blockoutputbus:4>], [<minecraft:hopper>]]);
recipes.addShaped(<modularmachinery:blockoutputbus:6>, [[<ore:chest>], [<modularmachinery:blockoutputbus:5>], [<minecraft:hopper>]]);
recipes.addShaped(<modularmachinery:blockinputbus>, [[<minecraft:hopper>], [<modularmachinery:blockcasing>], [<ore:chest>]]);
recipes.addShaped(<modularmachinery:blockinputbus:1>, [[<minecraft:hopper>], [<modularmachinery:blockinputbus>], [<ore:chest>]]);
recipes.addShaped(<modularmachinery:blockinputbus:2>, [[<minecraft:hopper>], [<modularmachinery:blockinputbus:1>], [<ore:chest>]]);
recipes.addShaped(<modularmachinery:blockinputbus:3>, [[<minecraft:hopper>], [<modularmachinery:blockinputbus:2>], [<ore:chest>]]);
recipes.addShaped(<modularmachinery:blockinputbus:4>, [[<minecraft:hopper>], [<modularmachinery:blockinputbus:3>], [<ore:chest>]]);
recipes.addShaped(<modularmachinery:blockinputbus:5>, [[<minecraft:hopper>], [<modularmachinery:blockinputbus:4>], [<ore:chest>]]);
recipes.addShaped(<modularmachinery:blockinputbus:6>, [[<minecraft:hopper>], [<modularmachinery:blockinputbus:5>], [<ore:chest>]]);
recipes.addShaped(<modularmachinery:blockfluidoutputhatch>, [[<minecraft:bucket>], [<modularmachinery:blockcasing>], [<minecraft:hopper>]]);
recipes.addShaped(<modularmachinery:blockfluidoutputhatch:1>, [[<minecraft:bucket>], [<modularmachinery:blockfluidoutputhatch>], [<minecraft:hopper>]]);
recipes.addShaped(<modularmachinery:blockfluidoutputhatch:2>, [[<minecraft:bucket>], [<modularmachinery:blockfluidoutputhatch:1>], [<minecraft:hopper>]]);
recipes.addShaped(<modularmachinery:blockfluidoutputhatch:3>, [[<minecraft:bucket>], [<modularmachinery:blockfluidoutputhatch:2>], [<minecraft:hopper>]]);
recipes.addShaped(<modularmachinery:blockfluidoutputhatch:4>, [[<minecraft:bucket>], [<modularmachinery:blockfluidoutputhatch:3>], [<minecraft:hopper>]]);
recipes.addShaped(<modularmachinery:blockfluidoutputhatch:5>, [[<minecraft:bucket>], [<modularmachinery:blockfluidoutputhatch:4>], [<minecraft:hopper>]]);
recipes.addShaped(<modularmachinery:blockfluidoutputhatch:6>, [[<minecraft:bucket>], [<modularmachinery:blockfluidoutputhatch:5>], [<minecraft:hopper>]]);
recipes.addShaped(<modularmachinery:blockfluidoutputhatch:7>, [[null, <minecraft:bucket>], [<quantumstorage:quantum_tank>, <modularmachinery:blockfluidoutputhatch:6>, <quantumstorage:quantum_tank>], [null, <minecraft:hopper>]]);
recipes.addShaped(<modularmachinery:blockfluidinputhatch>, [[<minecraft:hopper>], [<modularmachinery:blockcasing>], [<minecraft:bucket>]]);
recipes.addShaped(<modularmachinery:blockfluidinputhatch:1>, [[<minecraft:hopper>], [<modularmachinery:blockfluidinputhatch>], [<minecraft:bucket>]]);
recipes.addShaped(<modularmachinery:blockfluidinputhatch:2>, [[<minecraft:hopper>], [<modularmachinery:blockfluidinputhatch:1>], [<minecraft:bucket>]]);
recipes.addShaped(<modularmachinery:blockfluidinputhatch:3>, [[<minecraft:hopper>], [<modularmachinery:blockfluidinputhatch:2>], [<minecraft:bucket>]]);
recipes.addShaped(<modularmachinery:blockfluidinputhatch:4>, [[<minecraft:hopper>], [<modularmachinery:blockfluidinputhatch:3>], [<minecraft:bucket>]]);
recipes.addShaped(<modularmachinery:blockfluidinputhatch:5>, [[<minecraft:hopper>], [<modularmachinery:blockfluidinputhatch:4>], [<minecraft:bucket>]]);
recipes.addShaped(<modularmachinery:blockfluidinputhatch:6>, [[<minecraft:hopper>], [<modularmachinery:blockfluidinputhatch:5>], [<minecraft:bucket>]]);
recipes.addShaped(<immersiveengineering:wirecoil> * 4, [[null, <ore:wireCopper>, null], [<ore:wireCopper>, <ore:stickTreatedWood>, <ore:wireCopper>], [null, <ore:wireCopper>, null]]);
recipes.addShaped(<immersiveengineering:wirecoil:1> * 4, [[null, <ore:wireElectrum>, null], [<ore:wireElectrum>, <ore:stickTreatedWood>, <ore:wireElectrum>], [null, <ore:wireElectrum>, null]]);
recipes.addShaped(<immersiveengineering:wirecoil:2> * 4, [[null, <ore:wireSteel>, null], [<ore:wireAluminum>, <ore:stickTreatedWood>, <ore:wireAluminum>], [null, <ore:wireSteel>, null]]);
recipes.addShaped(<immersiveengineering:wirecoil:2> * 4, [[null, <ore:wireAluminum>, null], [<ore:wireSteel>, <ore:stickTreatedWood>, <ore:wireSteel>], [null, <ore:wireAluminum>, null]]);
recipes.addShaped(<immersiveengineering:wirecoil:3> * 4, [[null, <ore:fiberHemp>, null], [<ore:fiberHemp>, <ore:stickTreatedWood>, <ore:fiberHemp>], [null, <ore:fiberHemp>, null]]);
recipes.addShaped(<immersiveengineering:wirecoil:4> * 4, [[null, <ore:wireSteel>, null], [<ore:wireSteel>, <ore:stickTreatedWood>, <ore:wireSteel>], [null, <ore:wireSteel>, null]]);
recipes.addShaped(<immersiveengineering:wirecoil:5> * 4, [[null, <ore:wireAluminum>, null], [<minecraft:redstone>, <ore:stickTreatedWood>, <minecraft:redstone>], [null, <ore:wireAluminum>, null]]);
recipes.addShaped(<immersiveengineering:wirecoil:5> * 4, [[null, <minecraft:redstone>, null], [<ore:wireAluminum>, <ore:stickTreatedWood>, <ore:wireAluminum>], [null, <minecraft:redstone>, null]]);
recipes.addShaped(<cyclicmagic:crystal_pickaxe>, [[<ore:gemObsidian>, <ore:gemObsidian>, <ore:gemObsidian>], [null, <ore:stickDiamond>, null], [null, <ore:stickDiamond>, null]]);
recipes.addShaped(<cyclicmagic:crystal_axe>, [[null, <ore:gemObsidian>, <ore:gemObsidian>], [null, <ore:stickDiamond>, <ore:gemObsidian>], [null, <ore:stickDiamond>, null]]);
recipes.addShaped(<cyclicmagic:crystal_axe>, [[<ore:gemObsidian>, <ore:gemObsidian>, null], [<ore:gemObsidian>, <ore:stickDiamond>, null], [null, <ore:stickDiamond>, null]]);
recipes.addShaped(<cyclicmagic:crystal_spade>, [[null, <ore:gemObsidian>, null], [null, <ore:stickDiamond>, null], [null, <ore:stickDiamond>, null]]);
recipes.addShaped(<cyclicmagic:crystal_hoe>, [[null, <ore:gemObsidian>, <ore:gemObsidian>], [null, <ore:stickDiamond>, null], [null, <ore:stickDiamond>, null]]);
recipes.addShaped(<cyclicmagic:crystal_hoe>, [[<ore:gemObsidian>, <ore:gemObsidian>, null], [null, <ore:stickDiamond>, null], [null, <ore:stickDiamond>, null]]);
recipes.addShaped(<cyclicmagic:crystal_sword>, [[null, <ore:gemObsidian>, null], [null, <ore:gemObsidian>, null], [null, <ore:stickDiamond>, null]]);
recipes.addShaped(<cyclicmagic:mattock>, [[<ore:plateObsidianSteel>, <ore:plateObsidianSteel>, <ore:plateObsidianSteel>],[null, <techguns:itemshared:103>, <ore:plateObsidianSteel>], [<techguns:itemshared:103>, null, <ore:plateObsidianSteel>]]);
//File End
