//This file was created via CT-GUI! Editing it is not advised!
//Don't touch me!
//#Remove
//Don't touch me!
//#Add
recipes.addShaped(<enderio:item_material:3>, [[<minecraft:glass_pane>, <immersiveengineering:material:21>, <minecraft:glass_pane>],[<minecraft:glass_pane>, <immersiveengineering:material:21>, <minecraft:glass_pane>], [<thermalfoundation:material:358>, <enderio:item_material:38>, <thermalfoundation:material:358>]]);
recipes.addShapeless(<zcontent:cobalt_ingot> * 9, [<chisel:blockcobalt:2>]);
recipes.addShaped(<chisel:blockcobalt:2>, [[<zcontent:cobalt_ingot>, <zcontent:cobalt_ingot>, <zcontent:cobalt_ingot>],[<zcontent:cobalt_ingot>, <zcontent:cobalt_ingot>, <zcontent:cobalt_ingot>], [<zcontent:cobalt_ingot>, <zcontent:cobalt_ingot>, <zcontent:cobalt_ingot>]]);
recipes.addShaped(<teslacorelib:speed_tier2>, [[<zcontent:graphite_ingot>, <zcontent:brass_ingot>, <zcontent:graphite_ingot>],[<thermalfoundation:material:26>, <teslacorelib:speed_tier1>, <thermalfoundation:material:26>], [<ore:sheetPlastic>, <ore:sheetPlastic>, <ore:sheetPlastic>]]);
recipes.addShaped(<teslacorelib:speed_tier1>, [[<zcontent:graphite_ingot>, <zcontent:brass_ingot>, <zcontent:graphite_ingot>],[<thermalfoundation:material:26>, <teslacorelib:base_addon>, <thermalfoundation:material:26>], [<ore:sheetPlastic>, <ore:sheetPlastic>, <ore:sheetPlastic>]]);
recipes.addShaped(<teslacorelib:energy_tier2>, [[<zcontent:graphite_ingot>, <zcontent:brass_ingot>, <zcontent:graphite_ingot>],[<thermalfoundation:material:27>, <teslacorelib:energy_tier1>, <thermalfoundation:material:27>], [<ore:sheetPlastic>, <ore:sheetPlastic>, <ore:sheetPlastic>]]);
recipes.addShaped(<teslacorelib:energy_tier1>, [[<zcontent:graphite_ingot>, <zcontent:brass_ingot>, <zcontent:graphite_ingot>],[<thermalfoundation:material:27>, <teslacorelib:base_addon>, <thermalfoundation:material:27>], [<ore:sheetPlastic>, <ore:sheetPlastic>, <ore:sheetPlastic>]]);
recipes.addShaped(<teslacorelib:base_addon>, [[<ore:sheetPlastic>, <ore:sheetPlastic>, <ore:sheetPlastic>],[<zcontent:graphite_ingot>, <zcontent:brass_ingot>, <zcontent:graphite_ingot>], [<ore:sheetPlastic>, <ore:sheetPlastic>, <ore:sheetPlastic>]]);
recipes.addShaped(<furnus:upgrade:6>, [[<thermalfoundation:material:195>, <extrautils2:ingredients>, <thermalfoundation:material:195>],[<minecraft:redstone>, <thermalfoundation:material:324>, <minecraft:redstone>], [<minecraft:iron_ingot>, <redstonearsenal:material:96>, <minecraft:iron_ingot>]]);
recipes.addShaped(<furnus:upgrade:5>, [[<thermalfoundation:material:195>, <extrautils2:ingredients>, <thermalfoundation:material:195>],[<minecraft:redstone>, <thermalfoundation:material:324>, <minecraft:redstone>], [<minecraft:iron_ingot>, <thermalfoundation:material:258>, <minecraft:iron_ingot>]]);
recipes.addShaped(<furnus:upgrade:3>, [[<thermalfoundation:material:195>, <extrautils2:ingredients>, <thermalfoundation:material:195>],[<minecraft:redstone>, <thermalfoundation:material:324>, <minecraft:redstone>], [<minecraft:iron_ingot>, <thermalfoundation:material:26>, <minecraft:iron_ingot>]]);
recipes.addShaped(<furnus:upgrade:2>, [[<thermalfoundation:material:195>, <extrautils2:ingredients>, <thermalfoundation:material:195>],[<minecraft:redstone>, <thermalfoundation:material:324>, <minecraft:redstone>], [<minecraft:iron_ingot>, <jaopca:item_gearbrass>, <minecraft:iron_ingot>]]);
recipes.addShaped(<furnus:upgrade:4>, [[<thermalfoundation:material:195>, <extrautils2:ingredients>, <thermalfoundation:material:195>],[<minecraft:redstone>, <thermalfoundation:material:324>, <minecraft:redstone>], [<minecraft:iron_ingot>, <thermalfoundation:material:27>, <minecraft:iron_ingot>]]);
recipes.addShaped(<furnus:upgrade:1>, [[<thermalfoundation:material:195>, <extrautils2:ingredients>, <thermalfoundation:material:195>],[<minecraft:redstone>, <thermalfoundation:material:324>, <minecraft:redstone>], [<minecraft:iron_ingot>, <thermalfoundation:material:25>, <minecraft:iron_ingot>]]);
recipes.addShaped(<furnus:upgrade>, [[<thermalfoundation:material:195>, <extrautils2:ingredients>, <thermalfoundation:material:195>],[<minecraft:redstone>, <thermalfoundation:material:324>, <minecraft:redstone>], [<minecraft:iron_ingot>, <jaopca:item_gearredstonealloy>, <minecraft:iron_ingot>]]);
recipes.addShapeless(<zcontent:withered_bone_meal> * 3, [<zcontent:wither_bone>]);
recipes.addShapeless(<immersiveengineering:material:23>, [<thermalfoundation:material:352>, <immersiveengineering:tool:1> | <ore:toolShears>]);
recipes.addShapeless(<immersiveengineering:material:22>, [<thermalfoundation:material:324>, <immersiveengineering:tool:1> | <ore:toolShears>]);
recipes.addShapeless(<immersiveengineering:material:21>, [<thermalfoundation:material:353>, <immersiveengineering:tool:1> | <ore:toolShears>]);
recipes.addShapeless(<immersiveengineering:material:20>, [<thermalfoundation:material:320>, <immersiveengineering:tool:1> | <ore:toolShears>]);
recipes.addShaped(<quark:crystal:8> * 12, [[<jaopca:item_essencecrystalblack>, <jaopca:item_essencecrystalblack>, <jaopca:item_essencecrystalblack>],[<jaopca:item_essencecrystalblack>, null, <jaopca:item_essencecrystalblack>], [<jaopca:item_essencecrystalblack>, <jaopca:item_essencecrystalblack>, <jaopca:item_essencecrystalblack>]]);
recipes.addShaped(<quark:crystal:7> * 12, [[<jaopca:item_essencecrystalviolet>, <jaopca:item_essencecrystalviolet>, <jaopca:item_essencecrystalviolet>],[<jaopca:item_essencecrystalviolet>, null, <jaopca:item_essencecrystalviolet>], [<jaopca:item_essencecrystalviolet>, <jaopca:item_essencecrystalviolet>, <jaopca:item_essencecrystalviolet>]]);
recipes.addShaped(<quark:crystal:6> * 12, [[<jaopca:item_essencecrystalindigo>, <jaopca:item_essencecrystalindigo>, <jaopca:item_essencecrystalindigo>],[<jaopca:item_essencecrystalindigo>, null, <jaopca:item_essencecrystalindigo>], [<jaopca:item_essencecrystalindigo>, <jaopca:item_essencecrystalindigo>, <jaopca:item_essencecrystalindigo>]]);
recipes.addShaped(<quark:crystal:5> * 12, [[<jaopca:item_essencecrystalblue>, <jaopca:item_essencecrystalblue>, <jaopca:item_essencecrystalblue>],[<jaopca:item_essencecrystalblue>, null, <jaopca:item_essencecrystalblue>], [<jaopca:item_essencecrystalblue>, <jaopca:item_essencecrystalblue>, <jaopca:item_essencecrystalblue>]]);
recipes.addShaped(<quark:crystal:4> * 12, [[<jaopca:item_essencecrystalgreen>, <jaopca:item_essencecrystalgreen>, <jaopca:item_essencecrystalgreen>],[<jaopca:item_essencecrystalgreen>, null, <jaopca:item_essencecrystalgreen>], [<jaopca:item_essencecrystalgreen>, <jaopca:item_essencecrystalgreen>, <jaopca:item_essencecrystalgreen>]]);
recipes.addShaped(<quark:crystal:3> * 12, [[<jaopca:item_essencecrystalyellow>, <jaopca:item_essencecrystalyellow>, <jaopca:item_essencecrystalyellow>],[<jaopca:item_essencecrystalyellow>, null, <jaopca:item_essencecrystalyellow>], [<jaopca:item_essencecrystalyellow>, <jaopca:item_essencecrystalyellow>, <jaopca:item_essencecrystalyellow>]]);
recipes.addShaped(<quark:crystal:2> * 12, [[<jaopca:item_essencecrystalorange>, <jaopca:item_essencecrystalorange>, <jaopca:item_essencecrystalorange>],[<jaopca:item_essencecrystalorange>, null, <jaopca:item_essencecrystalorange>], [<jaopca:item_essencecrystalorange>, <jaopca:item_essencecrystalorange>, <jaopca:item_essencecrystalorange>]]);
recipes.addShaped(<quark:crystal:1> * 12, [[<jaopca:item_essencecrystalred>, <jaopca:item_essencecrystalred>, <jaopca:item_essencecrystalred>],[<jaopca:item_essencecrystalred>, null, <jaopca:item_essencecrystalred>], [<jaopca:item_essencecrystalred>, <jaopca:item_essencecrystalred>, <jaopca:item_essencecrystalred>]]);
recipes.addShaped(<quark:crystal> * 12, [[<jaopca:item_essencecrystalwhite>, <jaopca:item_essencecrystalwhite>, <jaopca:item_essencecrystalwhite>],[<jaopca:item_essencecrystalwhite>, null, <jaopca:item_essencecrystalwhite>], [<jaopca:item_essencecrystalwhite>, <jaopca:item_essencecrystalwhite>, <jaopca:item_essencecrystalwhite>]]);
recipes.addShapeless(<minecraft:bone> * 9, [<zcontent:bone_block>]);
recipes.addShapeless(<zcontent:wither_bone> * 9, [<zcontent:wither_bone_block>]);
recipes.addShapeless(<minecraft:gunpowder> * 9, [<zcontent:gunpowder_block>]);
recipes.addShapeless(<minecraft:flint> * 9, [<zcontent:flint_block>]);
recipes.addShapeless(<minecraft:rotten_flesh> * 9, [<zcontent:rotten_flesh_block>]);
recipes.addShapeless(<zcontent:flint_block>, [<minecraft:flint>,<minecraft:flint>,<minecraft:flint>,<minecraft:flint>,<minecraft:flint>,<minecraft:flint>,<minecraft:flint>,<minecraft:flint>,<minecraft:flint>]);
recipes.addShapeless(<zcontent:gunpowder_block>, [<minecraft:gunpowder>,<minecraft:gunpowder>,<minecraft:gunpowder>,<minecraft:gunpowder>,<minecraft:gunpowder>,<minecraft:gunpowder>,<minecraft:gunpowder>,<minecraft:gunpowder>,<minecraft:gunpowder>]);
recipes.addShapeless(<zcontent:wither_bone_block>, [<zcontent:wither_bone>,<zcontent:wither_bone>,<zcontent:wither_bone>,<zcontent:wither_bone>,<zcontent:wither_bone>,<zcontent:wither_bone>,<zcontent:wither_bone>,<zcontent:wither_bone>,<zcontent:wither_bone>]);
recipes.addShapeless(<zcontent:bone_block>, [<minecraft:bone>,<minecraft:bone>,<minecraft:bone>,<minecraft:bone>,<minecraft:bone>,<minecraft:bone>,<minecraft:bone>,<minecraft:bone>,<minecraft:bone>]);
recipes.addShapeless(<zcontent:rotten_flesh_block>, [<minecraft:rotten_flesh>,<minecraft:rotten_flesh>,<minecraft:rotten_flesh>,<minecraft:rotten_flesh>,<minecraft:rotten_flesh>,<minecraft:rotten_flesh>,<minecraft:rotten_flesh>,<minecraft:rotten_flesh>,<minecraft:rotten_flesh>]);
recipes.addShaped(<tp:unhardened_stone>, [[<ore:stoneBasalt>, <ore:stoneDiorite>, <ore:stoneBasalt>],[<ore:stoneDiorite>, <ore:blockClay>, <ore:stoneDiorite>], [<ore:stoneBasalt>, <ore:stoneDiorite>, <ore:stoneBasalt>]]);
recipes.addShaped(<quark:redstone_inductor>, [[null, null, null],[<minecraft:redstone>, <minecraft:magma_cream>, <minecraft:redstone>], [<ore:stonePolished>, <ore:stonePolished>, <ore:stonePolished>]]);
recipes.addShaped(<darkutils:timer>, [[null, <minecraft:redstone>, null],[<minecraft:redstone_torch>, <minecraft:clock>, <minecraft:redstone_torch>], [<ore:stonePolished>, <ore:stonePolished>, <ore:stonePolished>]]);
recipes.addShaped(<quark:redstone_randomizer>, [[null, <minecraft:redstone_torch>, null],[<minecraft:redstone_torch>, <actuallyadditions:item_misc:5>, <minecraft:redstone_torch>], [<ore:stonePolished>, <ore:stonePolished>, <ore:stonePolished>]]);
recipes.addShaped(<minecraft:comparator>, [[null, <minecraft:redstone_torch>, null],[<minecraft:redstone_torch>, <minecraft:quartz>, <minecraft:redstone_torch>], [<ore:stonePolished>, <ore:stonePolished>, <ore:stonePolished>]]);
recipes.addShaped(<minecraft:repeater>, [[<minecraft:redstone>, null, <minecraft:redstone>],[<minecraft:stick>, <minecraft:redstone>, <minecraft:stick>], [<ore:stonePolished>, <ore:stonePolished>, <ore:stonePolished>]]);
recipes.addShaped(<minecraft:repeater>, [[null, null, null],[<minecraft:redstone_torch>, <minecraft:redstone>, <minecraft:redstone_torch>], [<ore:stonePolished>, <ore:stonePolished>, <ore:stonePolished>]]);
recipes.addShaped(<tesseract:tesseract>, [[<jaopca:item_platedarksteel>, <thermaldynamics:duct_0:2>, <jaopca:item_platedarksteel>],[<thermaldynamics:duct_32:2>, <rftools:infused_enderpearl>, <thermaldynamics:duct_16:4>], [<jaopca:item_platedarksteel>, <techguns:itemshared:69>, <jaopca:item_platedarksteel>]]);
recipes.addShapeless(<quantumstorage:remote>, [<quantumstorage:remote>]);
recipes.addShaped(<zcontent:icesword>, [[null, <mysticalagriculture:ice_essence>, null],[<mysticalagriculture:ice_essence>, <immersiveengineering:sword_steel>, <mysticalagriculture:ice_essence>], [null, <mysticalagriculture:ice_essence>, null]]);
recipes.addShaped(<zcontent:firesword>, [[null, <mysticalagriculture:fire_essence>, null],[<mysticalagriculture:fire_essence>, <immersiveengineering:sword_steel>, <mysticalagriculture:fire_essence>], [null, <mysticalagriculture:fire_essence>, null]]);
recipes.addShaped(<quark:pipe> * 16, [[null, null, null],[<enderio:item_alloy_ingot:9>, <ore:blockGlassColorless>, <enderio:item_alloy_ingot:9>], [null, null, null]]);
recipes.addShaped(<futuremc:netherite_leggings>, [[<futuremc:netherite_ingot>, <futuremc:netherite_ingot>, <futuremc:netherite_ingot>],[<futuremc:netherite_ingot>, null, <futuremc:netherite_ingot>], [<futuremc:netherite_ingot>, null, <futuremc:netherite_ingot>]]);
recipes.addShaped(<futuremc:netherite_chestplate>, [[<futuremc:netherite_ingot>, null, <futuremc:netherite_ingot>],[<futuremc:netherite_ingot>, <futuremc:netherite_ingot>, <futuremc:netherite_ingot>], [<futuremc:netherite_ingot>, <futuremc:netherite_ingot>, <futuremc:netherite_ingot>]]);
recipes.addShaped(<futuremc:netherite_boots>, [[<futuremc:netherite_ingot>, null, <futuremc:netherite_ingot>],[<futuremc:netherite_ingot>, null, <futuremc:netherite_ingot>], [null, null, null]]);
recipes.addShaped(<futuremc:netherite_helmet>, [[<futuremc:netherite_ingot>, <futuremc:netherite_ingot>, <futuremc:netherite_ingot>],[<futuremc:netherite_ingot>, null, <futuremc:netherite_ingot>], [null, null, null]]);
recipes.addShaped(<enderio:item_material:10>, [[null, <ore:stonePolished>, null],[<ore:stonePolished>, <enderio:item_material:9>, <ore:stonePolished>], [null, <ore:stonePolished>, null]]);
recipes.addShaped(<tp:stone_hammer>, [[null, <randomthings:ingredient:3>, <ore:stringFluxed>],[null, <redstonearsenal:material:193>, <randomthings:ingredient:3>], [<redstonearsenal:material:193>, null, null]]);
recipes.addShaped(<cyclicmagic:water_candle>, [[null, <quark:tallow>, null],[<rftools:infused_diamond>, <techguns:itemshared:103>, <rftools:infused_diamond>], [<minecraft:light_weighted_pressure_plate>, <minecraft:light_weighted_pressure_plate>, <minecraft:light_weighted_pressure_plate>]]);
recipes.addShaped(<cyclicmagic:beacon_potion>, [[<ore:blockGlassColorless>, <ore:blockGlassColorless>, <ore:blockGlassColorless>],[<ore:blockGlassColorless>, <ore:netherStar>, <ore:blockGlassColorless>], [<ore:blockEmerald>, <ore:blockEmerald>, <ore:blockEmerald>]]);
recipes.addShapeless(<cyclicmagic:bundled_pipe> * 3, [<cyclicmagic:item_pipe>,<cyclicmagic:energy_pipe>,<cyclicmagic:fluid_pipe>]);
recipes.addShaped(<cyclicmagic:fluid_pump>, [[<cyclicmagic:fluid_pipe>, null, null],[<minecraft:heavy_weighted_pressure_plate>, null, null], [null, null, null]]);
recipes.addShaped(<cyclicmagic:energy_pump>, [[<cyclicmagic:energy_pipe>, null, null],[<minecraft:heavy_weighted_pressure_plate>, null, null], [null, null, null]]);
recipes.addShaped(<cyclicmagic:item_pump>, [[<cyclicmagic:item_pipe>, null, null],[<minecraft:heavy_weighted_pressure_plate>, null, null], [null, null, null]]);
recipes.addShapeless(<cyclicmagic:fluid_pipe> * 8, [<extrautils2:pipe>,<extrautils2:pipe>,<extrautils2:pipe>,<extrautils2:pipe>,<jaopca:item_nuggetsapphire>,<extrautils2:pipe>,<extrautils2:pipe>,<extrautils2:pipe>,<extrautils2:pipe>]);
recipes.addShapeless(<cyclicmagic:item_pipe> * 8, [<extrautils2:pipe>,<extrautils2:pipe>,<extrautils2:pipe>,<extrautils2:pipe>,<jaopca:item_nuggettanzanite>,<extrautils2:pipe>,<extrautils2:pipe>,<extrautils2:pipe>,<extrautils2:pipe>]);
recipes.addShapeless(<cyclicmagic:energy_pipe> * 8, [<extrautils2:pipe>,<extrautils2:pipe>,<extrautils2:pipe>,<extrautils2:pipe>,<jaopca:item_nuggetruby>,<extrautils2:pipe>,<extrautils2:pipe>,<extrautils2:pipe>,<extrautils2:pipe>]);
recipes.addShaped(<extrautils2:pipe> * 64, [[<thermalfoundation:material:129>, <thermalfoundation:material:129>, <thermalfoundation:material:129>],[<extrautils2:decorativeglass:5>, <extrautils2:decorativeglass:5>, <extrautils2:decorativeglass:5>], [<thermalfoundation:material:129>, <thermalfoundation:material:129>, <thermalfoundation:material:129>]]);
recipes.addShaped(<cyclicmagic:cable_wireless_energy>, [[<biomesoplenty:gem:1>, <cyclicmagic:ender_pearl_reuse> | <cyclicmagic:ender_pearl_mounted>, <biomesoplenty:gem:1>],[<cyclicmagic:ender_pearl_reuse> | <cyclicmagic:ender_pearl_mounted>, <ore:blockSilver>, <cyclicmagic:ender_pearl_reuse> | <cyclicmagic:ender_pearl_mounted>], [<biomesoplenty:gem:1>, <cyclicmagic:ender_pearl_reuse> | <cyclicmagic:ender_pearl_mounted>, <biomesoplenty:gem:1>]]);
recipes.addShaped(<cyclicmagic:cable_wireless_fluid>, [[<biomesoplenty:gem:6>, <cyclicmagic:ender_pearl_reuse> | <cyclicmagic:ender_pearl_mounted>, <biomesoplenty:gem:6>],[<cyclicmagic:ender_pearl_reuse> | <cyclicmagic:ender_pearl_mounted>, <ore:blockSilver>, <cyclicmagic:ender_pearl_reuse> | <cyclicmagic:ender_pearl_mounted>], [<biomesoplenty:gem:6>, <cyclicmagic:ender_pearl_reuse> | <cyclicmagic:ender_pearl_mounted>, <biomesoplenty:gem:6>]]);
recipes.addShaped(<cyclicmagic:cable_wireless>, [[<biomesoplenty:gem:4>, <cyclicmagic:ender_pearl_reuse> | <cyclicmagic:ender_pearl_mounted>, <biomesoplenty:gem:4>],[<cyclicmagic:ender_pearl_reuse> | <cyclicmagic:ender_pearl_mounted>, <ore:blockSilver>, <cyclicmagic:ender_pearl_reuse> | <cyclicmagic:ender_pearl_mounted>], [<biomesoplenty:gem:4>, <cyclicmagic:ender_pearl_reuse> | <cyclicmagic:ender_pearl_mounted>, <biomesoplenty:gem:4>]]);
recipes.addShaped(<cyclicmagic:ender_pearl_mounted>, [[<extrautils2:endershard>, <extrautils2:endershard>, <extrautils2:endershard>],[<extrautils2:endershard>, <biomesoplenty:gem:6>, <extrautils2:endershard>], [<extrautils2:endershard>, <extrautils2:endershard>, <extrautils2:endershard>]]);
recipes.addShaped(<cyclicmagic:ender_pearl_reuse>, [[<extrautils2:endershard>, <extrautils2:endershard>, <extrautils2:endershard>],[<extrautils2:endershard>, <biomesoplenty:gem:1>, <extrautils2:endershard>], [<extrautils2:endershard>, <extrautils2:endershard>, <extrautils2:endershard>]]);
recipes.addShaped(<cyclicmagic:wireless_receiver>, [[null, <minecraft:repeater>, null],[null, <cyclicmagic:ender_pearl_reuse>.giveBack(), null], [null, <quark:polished_stone>, null]]);
recipes.addShaped(<cyclicmagic:wireless_transmitter>, [[null, <minecraft:repeater>, null],[null, <cyclicmagic:ender_pearl_mounted>.giveBack(), null], [null, <quark:polished_stone>, null]]);
recipes.addShaped(<cyclicmagic:spikes_diamond>, [[null, <extendedcrafting:material:128>, null],[<extendedcrafting:material:128>, <cyclicmagic:spikes_iron>, <extendedcrafting:material:128>], [<quark:polished_stone>, <minecraft:redstone_block>, <quark:polished_stone>]]);
recipes.addShaped(<cyclicmagic:spikes_iron>, [[null, <minecraft:iron_nugget>, null],[<minecraft:iron_nugget>, <minecraft:iron_bars>, <minecraft:iron_nugget>], [<minecraft:stone>, <minecraft:redstone>, <minecraft:stone>]]);
recipes.addShapeless(<cyclicmagic:plate_push_fast>, [<cyclicmagic:plate_push_fast_angle>]);
recipes.addShapeless(<cyclicmagic:plate_push_fast_angle>, [<cyclicmagic:plate_push_fast_corner>]);
recipes.addShapeless(<cyclicmagic:plate_push_fast_corner>, [<cyclicmagic:plate_push_fast>]);
recipes.addShapeless(<cyclicmagic:plate_push_slowest>, [<cyclicmagic:plate_push_slowest_angle>]);
recipes.addShapeless(<cyclicmagic:plate_push_slowest_angle>, [<cyclicmagic:plate_push_slowest_corner>]);
recipes.addShapeless(<cyclicmagic:plate_push_slowest_corner>, [<cyclicmagic:plate_push_slowest>]);
recipes.addShapeless(<cyclicmagic:plate_push_slow>, [<cyclicmagic:plate_push_slow_angle>]);
recipes.addShapeless(<cyclicmagic:plate_push_slow_angle>, [<cyclicmagic:plate_push_slow_corner>]);
recipes.addShapeless(<cyclicmagic:plate_push_slow_corner>, [<cyclicmagic:plate_push_slow>]);
recipes.addShapeless(<cyclicmagic:plate_push>, [<cyclicmagic:plate_push_med_angle>]);
recipes.addShapeless(<cyclicmagic:plate_push_med_angle>, [<cyclicmagic:plate_push_corner>]);
recipes.addShapeless(<cyclicmagic:plate_push_corner>, [<cyclicmagic:plate_push>]);
recipes.addShaped(<cyclicmagic:plate_push_slowest> * 64, [[<thermalfoundation:material:132>, <biomesoplenty:gem:6>, <thermalfoundation:material:132>], [<minecraft:redstone>, <thermalfoundation:material:260>, <minecraft:redstone>]]);
recipes.addShaped(<cyclicmagic:plate_push_slow> * 64, [[<thermalfoundation:material:132>, <biomesoplenty:gem:4>, <thermalfoundation:material:132>], [<minecraft:redstone>, <thermalfoundation:material:260>, <minecraft:redstone>]]);
recipes.addShaped(<cyclicmagic:plate_push_fast> * 64, [[<thermalfoundation:material:132>, <biomesoplenty:gem:1>, <thermalfoundation:material:132>], [<minecraft:redstone>, <thermalfoundation:material:260>, <minecraft:redstone>]]);
recipes.addShaped(<cyclicmagic:plate_push> * 64, [[<thermalfoundation:material:132>, <biomesoplenty:gem:2>, <thermalfoundation:material:132>], [<minecraft:redstone>, <thermalfoundation:material:260>, <minecraft:redstone>]]);
recipes.addShaped(<cyclicmagic:glowing_helmet>, [[<minecraft:glowstone_dust>, <minecraft:glowstone_dust>, <minecraft:glowstone_dust>],[<minecraft:glowstone_dust>, <biomesoplenty:gem:7>, <minecraft:glowstone_dust>], [<minecraft:glowstone_dust>, <thermalfoundation:armor.helmet_constantan>, <minecraft:glowstone_dust>]]);
recipes.addShaped(<cyclicmagic:password_remote>, [[null, <minecraft:lever>, null],[null, <cyclicmagic:ender_pearl_reuse>.giveBack(), null], [null, <minecraft:stone_slab>, null]]);
recipes.addShaped(<cyclicmagic:dynamite_mining> * 64, [[<ore:paper>, <minecraft:gunpowder>],[<minecraft:gunpowder>, <ore:dyePurple>]]);
recipes.addShaped(<cyclicmagic:dynamite_safe> * 64, [[<ore:paper>, <minecraft:gunpowder>],[<minecraft:gunpowder>, <ore:dyeLime>]]);
recipes.addShaped(<cyclicmagic:moon_sensor>, [[<extrautils2:ingredients:5>],[<minecraft:daylight_detector>]]);
recipes.addShapeless(<cyclicmagic:button_large>, [<minecraft:cobblestone>,<minecraft:cobblestone>]);
recipes.addShapeless(<thermalfoundation:tome_experience>.withTag({ench: [{lvl: 1000, id: 106 as short}]}), [<minecraft:barrier>]);
recipes.addShapeless(<minecraft:nether_star>, [<mysticalagradditions:stuff>,<mysticalagradditions:stuff>,<mysticalagradditions:stuff>,<mysticalagradditions:stuff>]);
recipes.addShaped(<mysticalagriculture:mystical_fertilizer>, [[<mysticalagriculture:fertilized_essence>, <mysticalagriculture:fertilized_essence>, <mysticalagriculture:fertilized_essence>],[<mysticalagriculture:fertilized_essence>, <minecraft:dye:15>, <mysticalagriculture:fertilized_essence>], [<mysticalagriculture:fertilized_essence>, <mysticalagriculture:fertilized_essence>, <mysticalagriculture:fertilized_essence>]]);
recipes.addShaped(<mysticalagradditions:special:1>, [[<ore:essenceInsanium>, <ore:dragonEgg>, <ore:essenceInsanium>],[<ore:dragonEgg>, <extendedcrafting:storage:6>, <ore:dragonEgg>], [<ore:essenceInsanium>, <ore:dragonEgg>, <ore:essenceInsanium>]]);
recipes.addShaped(<mysticalagradditions:special:5>, [[<ore:essenceInsanium>, <ore:blockCosmicNeutronium>, <ore:essenceInsanium>],[<ore:blockCosmicNeutronium>, <extendedcrafting:storage:6>, <ore:blockCosmicNeutronium>], [<ore:essenceInsanium>, <ore:blockCosmicNeutronium>, <ore:essenceInsanium>]]);
recipes.addShaped(<mysticalagradditions:special:4>, [[<ore:essenceInsanium>, <ore:blockDraconiumAwakened>, <ore:essenceInsanium>],[<ore:blockDraconiumAwakened>, <extendedcrafting:storage:6>, <ore:blockDraconiumAwakened>], [<ore:essenceInsanium>, <ore:blockDraconiumAwakened>, <ore:essenceInsanium>]]);
recipes.addShaped(<mysticalagradditions:special>, [[<ore:essenceInsanium>, <ore:blockNetherStar>, <ore:essenceInsanium>],[<ore:blockNetherStar>, <extendedcrafting:storage:6>, <ore:blockNetherStar>], [<ore:essenceInsanium>, <ore:blockNetherStar>, <ore:essenceInsanium>]]);
recipes.addShapeless(<refinedstorage:fluid_storage_disk:3>, [<refinedstorage:storage_housing>,<refinedstorage:fluid_storage_part:3>]);
recipes.addShapeless(<refinedstorage:fluid_storage_disk:2>, [<refinedstorage:storage_housing>,<refinedstorage:fluid_storage_part:2>]);
recipes.addShapeless(<refinedstorage:fluid_storage_disk:1>, [<refinedstorage:storage_housing>,<refinedstorage:fluid_storage_part:1>]);
recipes.addShapeless(<refinedstorage:fluid_storage_disk>, [<refinedstorage:storage_housing>,<refinedstorage:fluid_storage_part>]);
recipes.addShapeless(<refinedstorage:storage_disk:3>, [<refinedstorage:storage_housing>,<refinedstorage:storage_part:3>]);
recipes.addShapeless(<refinedstorage:storage_disk:2>, [<refinedstorage:storage_housing>,<refinedstorage:storage_part:2>]);
recipes.addShapeless(<refinedstorage:storage_disk:1>, [<refinedstorage:storage_housing>,<refinedstorage:storage_part:1>]);
recipes.addShapeless(<refinedstorage:storage_disk>, [<refinedstorage:storage_housing>,<refinedstorage:storage_part>]);
recipes.addShaped(<enderio:block_enchanter>, [[null, <eplus:decorative_book:1>, null],[<minecraft:diamond>, <jaopca:item_platedensedarksteel>, <minecraft:diamond>], [<enderio:item_alloy_ingot:6>, <enderio:item_alloy_ingot:6>, <enderio:item_alloy_ingot:6>]]);
recipes.addShapeless(<tp:ender_dust>, [<enderio:item_material:28>,<enderio:item_material:28>,<enderio:item_material:28>,<enderio:item_material:28>,<enderio:item_material:28>,<enderio:item_material:28>,<enderio:item_material:28>,<enderio:item_material:28>,<enderio:item_material:28>]);
recipes.addShapeless(<enderio:item_material:28> * 9, [<tp:ender_dust>]);
recipes.addShapeless(<eplus:decorative_book:1>, [<extendedcrafting:material:7>,<extendedcrafting:material:7>,<quark:ancient_tome>,<extendedcrafting:material:7>,<extendedcrafting:material:7>]);
recipes.addShapeless(<eplus:decorative_book:1>, [<extendedcrafting:material:7>,<ore:essenceInsanium>,<extendedcrafting:material:7>,<ore:essenceInsanium>,<minecraft:enchanted_book>,<ore:essenceInsanium>,<extendedcrafting:material:7>,<ore:essenceInsanium>,<extendedcrafting:material:7>]);
recipes.addShapeless(<redstonerepository:material:1>, [<ore:dustGelidEnderium>,<thermalfoundation:material:1024>]);
recipes.addShapeless(<redstonearsenal:material:32>, [<ore:dustElectrumFlux>,<thermalfoundation:material:1024>]);
recipes.addShapeless(<thermalfoundation:material:167>, [<ore:dustEnderium>,<thermalfoundation:material:1024>]);
recipes.addShapeless(<thermalfoundation:material:166>, [<ore:dustLumium>,<thermalfoundation:material:1024>]);
recipes.addShapeless(<thermalfoundation:material:165>, [<ore:dustSignalum>,<thermalfoundation:material:1024>]);
recipes.addShapeless(<cyclicmagic:ender_torch>, [<tp:ender_dust>,<minecraft:torch>,<minecraft:torch>,<minecraft:torch>,<minecraft:torch>,<minecraft:torch>,<minecraft:torch>,<minecraft:torch>,<minecraft:torch>]);
recipes.addShaped(<tp:birthday_pickaxe>, [[null, <minecraft:diamond>, null],[null, <minecraft:cake>, null], [null, <actuallyadditions:item_pickaxe_obsidian>, null]]);
recipes.addShaped(<zcontent:silver_obsidian_axe>, [[<thermalfoundation:material:130>, <thermalfoundation:material:130>, null],[<thermalfoundation:material:130>, <jaopca:item_stickobsidian>, null], [null, <jaopca:item_stickobsidian>, null]]);
recipes.addShaped(<zcontent:silver_obsidian_shovel>, [[null, <thermalfoundation:material:130>, null],[null, <jaopca:item_stickobsidian>, null], [null, <jaopca:item_stickobsidian>, null]]);
recipes.addShaped(<zcontent:silver_obsidian_pick>, [[<thermalfoundation:material:130>, <thermalfoundation:material:130>, <thermalfoundation:material:130>],[null, <jaopca:item_stickobsidian>, null], [null, <jaopca:item_stickobsidian>, null]]);
recipes.addShaped(<zcontent:silver_obsidian_sword>, [[null, <thermalfoundation:material:130>, null],[null, <thermalfoundation:material:130>, null], [null, <jaopca:item_stickobsidian>, null]]);
recipes.addShapeless(<jaopca:item_stickobsidian>, [<ore:obsidian>,<ore:obsidian>,<tp:stone_hammer>]);
recipes.addShaped(<zcontent:sulfur_crystal>, [[<ore:dustSulfur>, <ore:crystalSlag>, <ore:dustSulfur>],[<ore:crystalSlagRich>, <ore:crystalCinnabar>, <ore:crystalSlagRich>], [<ore:dustSulfur>, <ore:crystalSlag>, <ore:dustSulfur>]]);
recipes.addShapeless(<storagenetwork:controller>, [<storagenetwork:master>,<minecraft:emerald>]);
recipes.addShapeless(<storagenetwork:request>, [<storagenetwork:master>,<minecraft:crafting_table>]);
recipes.addShaped(<storagenetwork:master>, [[<ore:blockQuartz>, <storagenetwork:kabel>, <ore:blockQuartz>],[<storagenetwork:kabel>, <fluxnetworks:fluxblock>, <storagenetwork:kabel>], [<ore:blockQuartz>, <storagenetwork:kabel>, <ore:blockQuartz>]]);
recipes.addShapeless(<storagenetwork:upgrade>, [<thermalfoundation:material:322>,<minecraft:redstone>]);
recipes.addShapeless(<storagenetwork:upgrade:2>, [<thermalfoundation:material:322>,<minecraft:glowstone_dust>]);
recipes.addShapeless(<storagenetwork:upgrade:3>, [<thermalfoundation:material:322>,<ore:blockChest>]);
recipes.addShapeless(<storagenetwork:upgrade:1>, [<thermalfoundation:material:322>,<minecraft:redstone_torch>]);
recipes.addShapeless(<storagenetwork:process_kabel> * 8, [<biomesoplenty:gem:3>,<storagenetwork:kabel>,<storagenetwork:kabel>,<storagenetwork:kabel>,<storagenetwork:kabel>,<storagenetwork:kabel>,<storagenetwork:kabel>,<storagenetwork:kabel>,<storagenetwork:kabel>]);
recipes.addShapeless(<storagenetwork:im_kabel> * 8, [<biomesoplenty:gem:1>,<storagenetwork:kabel>,<storagenetwork:kabel>,<storagenetwork:kabel>,<storagenetwork:kabel>,<storagenetwork:kabel>,<storagenetwork:kabel>,<storagenetwork:kabel>,<storagenetwork:kabel>]);
recipes.addShapeless(<storagenetwork:ex_kabel> * 8, [<biomesoplenty:gem:2>,<storagenetwork:kabel>,<storagenetwork:kabel>,<storagenetwork:kabel>,<storagenetwork:kabel>,<storagenetwork:kabel>,<storagenetwork:kabel>,<storagenetwork:kabel>,<storagenetwork:kabel>]);
recipes.addShapeless(<storagenetwork:storage_kabel> * 8, [<biomesoplenty:gem:4>,<storagenetwork:kabel>,<storagenetwork:kabel>,<storagenetwork:kabel>,<storagenetwork:kabel>,<storagenetwork:kabel>,<storagenetwork:kabel>,<storagenetwork:kabel>,<storagenetwork:kabel>]);
recipes.addShaped(<storagenetwork:kabel> * 8, [[null, null, null],[<thermalfoundation:material:132>, <deepmoblearning:soot_covered_redstone>, <thermalfoundation:material:132>], [null, null, null]]);
recipes.addShaped(<rsinfinitewireless:infinite_wireless_transmitter>, [[<enderio:block_holy_fog>, <enderio:block_holy_fog>, <enderio:block_holy_fog>],[<enderio:block_holy_fog>, <refinedstorage:wireless_transmitter>, <enderio:block_holy_fog>], [<enderio:block_holy_fog>, <enderio:block_holy_fog>, <enderio:block_holy_fog>]]);
recipes.addShaped(<refinedstorage:wireless_transmitter>, [[<extendedcrafting:material:40>], [<refinedstorage:quartz_enriched_iron>]]);
recipes.addShaped(<refinedstorage:filter> * 4, [[null, <refinedstorage:quartz_enriched_iron>, null],[<refinedstorage:quartz_enriched_iron>, <ore:paper>, <refinedstorage:quartz_enriched_iron>], [null, <refinedstorage:quartz_enriched_iron>, null]]);
recipes.addShapeless(<refinedstorage:network_card>, [<refinedstorage:upgrade:1>,<zcontent:proc_3>]);
recipes.addShapeless(<refinedstorage:upgrade:9>, [<refinedstorage:upgrade>,<minecraft:emerald>,<minecraft:emerald>,<minecraft:emerald>]);
recipes.addShapeless(<refinedstorage:upgrade:8>, [<refinedstorage:upgrade>,<minecraft:emerald>,<minecraft:emerald>]);
recipes.addShapeless(<refinedstorage:upgrade:7>, [<refinedstorage:upgrade>,<minecraft:emerald>]);
recipes.addShapeless(<refinedstorage:upgrade:6>, [<refinedstorage:upgrade>,<minecraft:sponge>]);
recipes.addShapeless(<refinedstorage:upgrade:3>, [<refinedstorage:upgrade>,<ore:craftingTableWood>]);
recipes.addShapeless(<refinedstorage:upgrade:4>, [<refinedstorage:upgrade>,<ore:blockGlowstone>]);
recipes.addShapeless(<refinedstorage:upgrade:2>, [<refinedstorage:upgrade>,<minecraft:glowstone_dust>]);
recipes.addShapeless(<refinedstorage:upgrade:1>, [<refinedstorage:upgrade>,<tp:ender_dust>]);
recipes.addShaped(<refinedstorage:upgrade> * 4, [[null, <refinedstorage:quartz_enriched_iron>, null],[<refinedstorage:quartz_enriched_iron>, <zcontent:chip2>, <refinedstorage:quartz_enriched_iron>], [null, <refinedstorage:quartz_enriched_iron>, null]]);
recipes.addShapeless(<refinedstorage:core:1>, [<refinedstorage:processor:3>, <ore:dustRedGlowstone>]);
recipes.addShapeless(<refinedstorage:core>, [<refinedstorage:processor:3>, <ore:dustCyanGlowstone>]);
recipes.addShapeless(<refinedstorage:processor:5>, [<refinedstorage:processor_binding>,<zcontent:proc_3>]);
recipes.addShapeless(<refinedstorage:processor:4>, [<refinedstorage:processor_binding>,<zcontent:proc_2>]);
recipes.addShapeless(<refinedstorage:processor:3>, [<refinedstorage:processor_binding>,<zcontent:proc_1>]);
recipes.addShapeless(<refinedstorage:crafter>, [<refinedstorage:machine_casing>,<refinedstorage:core>,<refinedstorage:core:1>]);
recipes.addShapeless(<storagedrawers:trim:5> * 4, [<futuremc:stripped_dark_oak_log>]);
recipes.addShapeless(<storagedrawers:trim:4> * 4, [<futuremc:stripped_acacia_log>]);
recipes.addShapeless(<storagedrawers:trim:3> * 4, [<futuremc:stripped_jungle_log>]);
recipes.addShapeless(<storagedrawers:trim:2> * 4, [<futuremc:stripped_birch_log>]);
recipes.addShapeless(<storagedrawers:trim:1> * 4, [<futuremc:stripped_spruce_log>]);
recipes.addShapeless(<storagedrawers:trim> * 4, [<futuremc:stripped_oak_log>]);
recipes.addShaped(<techguns:goldenrevolver>, [[<techguns:itemshared:39>, <thermalfoundation:material:33>, <minecraft:flint_and_steel>],[null, <techguns:itemshared:59>, <techguns:itemshared:44>], [null, null, null]]);
recipes.addShaped(<techguns:revolver>, [[<techguns:itemshared:38>, <thermalfoundation:material:32>, <minecraft:flint_and_steel>],[null, <techguns:itemshared:57>, <techguns:itemshared:42>], [null, null, null]]);
recipes.addShaped(<techguns:itemshared:35>, [[<techguns:itemshared:51>, <techguns:itemshared:51>, <techguns:itemshared:51>], [null, <techguns:itemshared:58>, <techguns:itemshared:84>], [null, null, <techguns:itemshared:84>]]);
recipes.addShapeless(<enderio:block_enderman_skull>, [<minecraft:skull:3>.withTag({SkullOwner: "MHF_Enderman"})]);
recipes.addShapeless(<compactstorage:compactchest>.withTag({size: [24, 10] as int[], hue: -1}), [<compactstorage:compactchest>]);
recipes.addShapeless(<compactstorage:backpack>.withTag({size: [24, 10] as int[], hue: -1}), [<compactstorage:backpack>]);
recipes.addShapeless(<thermalfoundation:material:33>, [<ore:blockSheetmetalGold>]);
recipes.addShapeless(<thermalfoundation:material:32>, [<ore:blockSheetmetalIron>]);
recipes.addShapeless(<thermalfoundation:material:352>, [<ore:blockSheetmetalSteel>]);
recipes.addShapeless(<thermalfoundation:material:353>, [<ore:blockSheetmetalElectrum>]);
recipes.addShapeless(<thermalfoundation:material:356>, [<ore:blockSheetmetalConstantan>]);
recipes.addShapeless(<immersiveengineering:metal:35>, [<ore:blockSheetmetalUranium>]);
recipes.addShapeless(<thermalfoundation:material:325>, [<ore:blockSheetmetalNickel>]);
recipes.addShapeless(<thermalfoundation:material:322>, [<ore:blockSheetmetalSilver>]);
recipes.addShapeless(<thermalfoundation:material:323>, [<ore:blockSheetmetalLead>]);
recipes.addShapeless(<thermalfoundation:material:324>, [<ore:blockSheetmetalAluminium>]);
recipes.addShapeless(<thermalfoundation:material:320>, [<ore:blockSheetmetalCopper>]);
recipes.addShaped(<minecraft:brewing_stand>, [[<minecraft:iron_nugget>, <ore:rodBlaze>, <minecraft:iron_nugget>],[null, <ore:rodBlaze>, null], [<minecraft:stone_slab>, <minecraft:stone_slab>, <minecraft:stone_slab>]]);
recipes.addShaped(<minecraft:enchanting_table>, [[<minecraft:carpet:14>, <eplus:decorative_book:1>, <minecraft:carpet:14>],[<ore:blockDiamond>, <minecraft:obsidian>, <ore:blockDiamond>], [<minecraft:obsidian>, <minecraft:obsidian>, <minecraft:obsidian>]]);
recipes.addShaped(<danknull:dank_null_5>, [[null, <danknull:dank_null_panel_5>, null],[<danknull:dank_null_panel_5>, <danknull:dank_null_panel_5>, <danknull:dank_null_panel_5>], [null, <danknull:dank_null_panel_5>, null]]);
recipes.addShaped(<danknull:dank_null_panel_5>, [[<jaopca:item_platedensecoal>, <minecraft:emerald>, <jaopca:item_platedensecoal>],[<minecraft:emerald>, <minecraft:stained_glass_pane:5>, <minecraft:emerald>], [<jaopca:item_platedensecoal>, <minecraft:emerald>, <jaopca:item_platedensecoal>]]);
recipes.addShaped(<futuremc:netherite_sword>, [[null, <futuremc:netherite_ingot>, null],[null, <futuremc:netherite_ingot>, null], [null, <ore:itemNutritiousStick>, null]]);
recipes.addShaped(<futuremc:netherite_shovel>, [[null, <futuremc:netherite_ingot>, null],[null, <ore:itemNutritiousStick>, null], [null, <ore:itemNutritiousStick>, null]]);
recipes.addShaped(<futuremc:netherite_pickaxe>, [[<futuremc:netherite_ingot>, <futuremc:netherite_ingot>, <futuremc:netherite_ingot>],[null, <ore:itemNutritiousStick>, null], [null, <ore:itemNutritiousStick>, null]]);
recipes.addShaped(<futuremc:netherite_hoe>, [[<futuremc:netherite_ingot>, <futuremc:netherite_ingot>, null],[null, <ore:itemNutritiousStick>, null], [null, <ore:itemNutritiousStick>, null]]);
recipes.addShaped(<futuremc:netherite_axe>, [[<futuremc:netherite_ingot>, <futuremc:netherite_ingot>, null],[<futuremc:netherite_ingot>, <ore:itemNutritiousStick>, null], [null, <ore:itemNutritiousStick>, null]]);
recipes.addShapeless(<thermalfoundation:coin:96> * 3, [<thermalfoundation:material:352>,<immersiveengineering:tool> | <tp:stone_hammer>,<immersiveengineering:tool:1>]);
recipes.addShaped(<furnus:pulvus>, [[<quark:charred_nether_bricks>, <quark:charred_nether_bricks>, <quark:charred_nether_bricks>],[<quark:charred_nether_bricks>, <quark:charred_nether_brick_slab>, <quark:charred_nether_bricks>], [<ore:stonePolished>, <ore:slabStone>, <ore:stonePolished>]]);
recipes.addShaped(<furnus:furnus>, [[<minecraft:brick_block>, <minecraft:brick_block>, <minecraft:brick_block>],[<minecraft:brick_block>, <ore:slabBricks>, <minecraft:brick_block>], [<ore:stonePolished>, <ore:slabStone>, <ore:stonePolished>]]);
recipes.addShaped(<futuremc:smithing_table>, [[<jaopca:item_platenetherite>, <jaopca:item_platenetherite>, <jaopca:item_platenetherite>],[<immersiveengineering:tool>.noReturn(), <ore:plankTreatedWood>, <immersiveengineering:tool:1>.noReturn()], [<ore:plankTreatedWood>, <ore:plankTreatedWood>, <ore:plankTreatedWood>]]);
recipes.addShaped(<minecraft:anvil>, [[<zcontent:iron_stone>, <zcontent:iron_stone>, <zcontent:iron_stone>],[null, <enderio:item_alloy_ingot:9>, null], [<enderio:item_alloy_ingot:9>, <enderio:item_alloy_ingot:9>, <enderio:item_alloy_ingot:9>]]);
recipes.addShapeless(<jaopca:item_dustconstructionalloy> * 2, [<ore:dustIron>,<ore:dustIron>,<ore:dustGraphite>]);
recipes.addShapeless(<refinedstorage:quartz_enriched_iron> * 9, [<refinedstorage:quartz_enriched_iron_block>]);
recipes.addShaped(<tp:infin_bucket>, [[null, <mysticalagriculture:crafting:4>, null],[<mysticalagriculture:crafting:4>, <randomthings:reinforcedenderbucket>.withTag({Fluid: {FluidName: "water", Amount: 10000}}).onlyWithTag({Fluid: {FluidName: "water", Amount: 10000}}), <mysticalagriculture:crafting:4>], [null, <mysticalagriculture:crafting:4>, null]]);
recipes.addShapeless(<jaopca:item_dustinsanium>, [<ore:essenceInsanium>,<ore:essenceInsanium>,<ore:essenceInsanium>,<ore:essenceInsanium>,<ore:dustSupremium>,<ore:essenceInsanium>,<ore:essenceInsanium>,<ore:essenceInsanium>,<ore:essenceInsanium>]);
recipes.addShapeless(<jaopca:item_dustsupremium>, [<ore:essenceSupremium>,<ore:essenceSupremium>,<ore:essenceSupremium>,<ore:essenceSupremium>,<ore:dustSuperium>,<ore:essenceSupremium>,<ore:essenceSupremium>,<ore:essenceSupremium>,<ore:essenceSupremium>]);
recipes.addShapeless(<jaopca:item_dustsuperium>, [<ore:essenceSuperium>,<ore:essenceSuperium>,<ore:essenceSuperium>,<ore:essenceSuperium>,<ore:dustIntermedium>,<ore:essenceSuperium>,<ore:essenceSuperium>,<ore:essenceSuperium>,<ore:essenceSuperium>]);
recipes.addShapeless(<jaopca:item_dustintermedium>, [<ore:essenceIntermedium>,<ore:essenceIntermedium>,<ore:essenceIntermedium>,<ore:essenceIntermedium>,<ore:dustPrudentium>,<ore:essenceIntermedium>,<ore:essenceIntermedium>,<ore:essenceIntermedium>,<ore:essenceIntermedium>]);
recipes.addShapeless(<jaopca:item_dustprudentium>, [<ore:essencePrudentium>,<ore:essencePrudentium>,<ore:essencePrudentium>,<ore:essencePrudentium>,<ore:dustInferium>,<ore:essencePrudentium>,<ore:essencePrudentium>,<ore:essencePrudentium>,<ore:essencePrudentium>]);
recipes.addShapeless(<jaopca:item_dustinferium>, [<ore:essenceInferium>,<ore:essenceInferium>,<ore:essenceInferium>,<ore:essenceInferium>,<ore:dustBaseEssence>,<ore:essenceInferium>,<ore:essenceInferium>,<ore:essenceInferium>,<ore:essenceInferium>]);
recipes.addShaped(<cookingforblockheads:sink>, [[<minecraft:iron_ingot>, <minecraft:iron_ingot>, <minecraft:iron_ingot>], [<minecraft:hardened_clay>, <tp:infin_bucket>, <minecraft:hardened_clay>], [<minecraft:hardened_clay>, <minecraft:hardened_clay>, <minecraft:hardened_clay>]]);
recipes.addShapeless(<minecraft:flint_and_steel>.withTag({Unbreakable:1}), [<thermalfoundation:material:160>, <minecraft:flint>]);
recipes.addShapeless(<tp:asphalt_block> * 512, [<ore:sand>,<ore:sand>,<minecraft:gravel>,<ore:blockGravel>,<thermalfoundation:material:833>,<immersivepetroleum:material>,<immersivepetroleum:material>,<biomesoplenty:ash>,<biomesoplenty:ash>]);
recipes.addShaped(<zcontent:stainless_steel_pick>.withTag({Unbreakable:1}), [[<zcontent:stainless_steel_ingot>, <zcontent:stainless_steel_ingot>, <zcontent:stainless_steel_ingot>],[null, <immersiveengineering:material>, null], [null, <immersiveengineering:material>, null]]);
recipes.addShaped(<zcontent:stainless_steel_shovel>.withTag({Unbreakable:1}), [[null, <zcontent:stainless_steel_ingot>, null],[null, <immersiveengineering:material>, null], [null, <immersiveengineering:material>, null]]);
recipes.addShaped(<zcontent:stainless_steel_axe>.withTag({Unbreakable:1}), [[<zcontent:stainless_steel_ingot>, <zcontent:stainless_steel_ingot>, null],[<zcontent:stainless_steel_ingot>, <immersiveengineering:material>, null], [null, <immersiveengineering:material>, null]]);
recipes.addShaped(<zcontent:stainless_steel_sword>.withTag({Unbreakable:1}), [[null, <zcontent:stainless_steel_ingot>, null],[null, <zcontent:stainless_steel_ingot>, null], [null, <immersiveengineering:material>, null]]);
recipes.addShaped(<zcontent:mastersword1>, [[null, <zcontent:masterswordblade>, null],[null, <zcontent:masterswordcore>, null], [null, <zcontent:masterswordgrip>, null]]);
recipes.addShapeless(<tp:bread_slice> * 20, [<minecraft:bread>,<minecraft:bread>]);
recipes.addShaped(<quantumstorage:chest_quantum>, [[<ore:plankWood>, <jaopca:item_stickemerald>, <ore:plankWood>],[<jaopca:item_stickemerald>, <ore:pressurePlateWood>, <jaopca:item_stickemerald>], [<ore:plankWood>, <jaopca:item_stickemerald>, <ore:plankWood>]]);
recipes.addShaped(<quantumstorage:chest_diamond>, [[<ore:plankWood>, <jaopca:item_stickdiamond>, <ore:plankWood>],[<jaopca:item_stickdiamond>, <ore:pressurePlateWood>, <jaopca:item_stickdiamond>], [<ore:plankWood>, <jaopca:item_stickdiamond>, <ore:plankWood>]]);
recipes.addShaped(<quantumstorage:chest_gold>, [[<ore:plankWood>, <jaopca:item_stickgold>, <ore:plankWood>],[<jaopca:item_stickgold>, <ore:pressurePlateWood>, <jaopca:item_stickgold>], [<ore:plankWood>, <jaopca:item_stickgold>, <ore:plankWood>]]);
recipes.addShaped(<quantumstorage:chest_iron>, [[<ore:plankWood>, <immersiveengineering:material:1>, <ore:plankWood>],[<immersiveengineering:material:1>, <ore:pressurePlateWood>, <immersiveengineering:material:1>], [<ore:plankWood>, <immersiveengineering:material:1>, <ore:plankWood>]]);
recipes.addShapeless(<biomesoplenty:ash> * 9, [<biomesoplenty:ash_block>]);
recipes.addShaped(<darkutils:wither_block>, [[<ore:dustAsh>, <ore:dustAsh>], [<ore:dustAsh>, <ore:dustAsh>]]);
recipes.addShaped(<darkutils:material:3> * 8, [[<minecraft:sugar:*>, <minecraft:sugar:*>, <minecraft:sugar:*>], [<minecraft:sugar:*>, <darkutils:material:*>, <minecraft:sugar:*>], [<minecraft:sugar:*>, <minecraft:sugar:*>, <minecraft:sugar:*>]]);
recipes.addShaped(<darkutils:trap_tile:5>, [[<ore:stone>, <ore:dustAsh>, <ore:stone>]]);
recipes.addShapeless(<darkutils:material:2>, [<ore:dustAsh>, <ore:slimeball>]);
recipes.addShapeless(<minecraft:dye:8> * 2, [<ore:dustAsh>]);
recipes.addShapeless(<biomesoplenty:ash_block>, [<ore:dustAsh>, <ore:dustAsh>, <ore:dustAsh>, <ore:dustAsh>, <ore:dustAsh>, <ore:dustAsh>, <ore:dustAsh>, <ore:dustAsh>, <ore:dustAsh>]);
recipes.addShapeless(<zcontent:charcoal_tiny_small> * 8, [<ore:charcoal>]);
recipes.addShapeless(<zcontent:coal_tiny_small> * 8, [<minecraft:coal>]);
recipes.addShapeless(<minecraft:coal:1>, [<zcontent:charcoal_tiny_small>,<zcontent:charcoal_tiny_small>,<zcontent:charcoal_tiny_small>,<zcontent:charcoal_tiny_small>,<zcontent:charcoal_tiny_small>,<zcontent:charcoal_tiny_small>,<zcontent:charcoal_tiny_small>,<zcontent:charcoal_tiny_small>]);
recipes.addShapeless(<minecraft:coal>, [<zcontent:coal_tiny_small>,<zcontent:coal_tiny_small>,<zcontent:coal_tiny_small>,<zcontent:coal_tiny_small>,<zcontent:coal_tiny_small>,<zcontent:coal_tiny_small>,<zcontent:coal_tiny_small>,<zcontent:coal_tiny_small>]);
recipes.addShaped(<actuallyadditions:block_misc:9>, [[<thermalfoundation:material:32>, <zcontent:red_alloy_ingot>, <thermalfoundation:material:32>],[<zcontent:red_alloy_ingot>, <jaopca:item_gearbrass>, <zcontent:red_alloy_ingot>], [<thermalfoundation:material:32>, <zcontent:red_alloy_ingot>, <thermalfoundation:material:32>]]);
recipes.addShaped(<rftools:machine_base> * 16, [[null, null, null],[<zcontent:stainless_steel_ingot>, <zcontent:red_alloy_ingot>, <zcontent:stainless_steel_ingot>], [null, null, null]]);
recipes.addShaped(<actuallyadditions:item_misc:8>, [[null, <ore:wireGold>, <quark:spruce_pressure_plate>],[<ore:wireGold>, <immersiveengineering:material>, <ore:wireGold>], [<quark:spruce_pressure_plate>, <ore:wireGold>, null]]);
recipes.addShaped(<actuallyadditions:item_misc:7>, [[null, <ore:wireAluminum>, <quark:spruce_pressure_plate>],[<ore:wireAluminum>, <immersiveengineering:material>, <ore:wireAluminum>], [<quark:spruce_pressure_plate>, <ore:wireAluminum>, null]]);
recipes.addShaped(<extrautils2:teleporter:1>, [[<extrautils2:compressedcobblestone:7>, <extrautils2:compressedcobblestone:6>, <extrautils2:compressedcobblestone:7>],[<extrautils2:compressedcobblestone:6>, <draconicevolution:dislocator>, <extrautils2:compressedcobblestone:6>], [<extrautils2:compressedcobblestone:7>, <extrautils2:compressedcobblestone:6>, <extrautils2:compressedcobblestone:7>]]);
recipes.addShapeless(<minecraft:bedrock>, [<extrautils2:decorativebedrock:1>]);
recipes.addShapeless(<extrautils2:decorativebedrock:1>, [<extrautils2:decorativebedrock>]);
recipes.addShapeless(<extrautils2:decorativebedrock>, [<minecraft:bedrock>,<minecraft:bedrock>,<minecraft:bedrock>,<minecraft:bedrock>]);
recipes.addShapeless(<projecte:item.pe_tome>, [<biomesoplenty:earth>]);
recipes.addShaped(<tp:lava_infused_stone>, [[<tp:hardened_stone>, <mysticalagriculture:fire_essence>, <tp:hardened_stone>],[<mysticalagriculture:fire_essence>, <tp:hardened_stone>, <mysticalagriculture:fire_essence>], [<tp:hardened_stone>, <mysticalagriculture:fire_essence>, <tp:hardened_stone>]]);
recipes.addShaped(<modularmachinery:blockcasing:4>, [[<techguns:itemshared:84>, <modularmachinery:itemmodularium>, <techguns:itemshared:84>], [<modularmachinery:itemmodularium>, <actuallyadditions:block_crystal_empowered>, <modularmachinery:itemmodularium>], [<techguns:itemshared:84>, <modularmachinery:itemmodularium>, <techguns:itemshared:84>]]);
recipes.addShaped(<modularmachinery:blockcasing:1>, [[<modularmachinery:itemmodularium>, <minecraft:iron_bars>, <modularmachinery:itemmodularium>], [<thermalfoundation:material:32>, <actuallyadditions:block_crystal_empowered>, <thermalfoundation:material:32>], [<modularmachinery:itemmodularium>, <minecraft:iron_bars>, <modularmachinery:itemmodularium>]]);
recipes.addShaped(<modularmachinery:blockcasing:2>, [[<modularmachinery:itemmodularium>, <minecraft:flint>, <modularmachinery:itemmodularium>], [<thermalfoundation:material:32>, <actuallyadditions:block_crystal_empowered>, <thermalfoundation:material:32>], [<modularmachinery:itemmodularium>, <minecraft:flint>, <modularmachinery:itemmodularium>]]);
recipes.addShaped(<modularmachinery:blockcasing:3>, [[<modularmachinery:itemmodularium>, <techguns:itemshared:57>, <modularmachinery:itemmodularium>], [<thermalfoundation:material:32>, <actuallyadditions:block_crystal_empowered>, <thermalfoundation:material:32>], [<modularmachinery:itemmodularium>, <techguns:itemshared:57>, <modularmachinery:itemmodularium>]]);
recipes.addShaped(<modularmachinery:blockcasing>, [[null, <modularmachinery:itemmodularium>, null], [<modularmachinery:itemmodularium>, <actuallyadditions:block_crystal_empowered>, <modularmachinery:itemmodularium>], [null, <modularmachinery:itemmodularium>, null]]);
recipes.addShaped(<modularmachinery:blockcasing:5>, [[<modularmachinery:itemmodularium>, <techguns:itemshared:65>, <modularmachinery:itemmodularium>], [<thermalfoundation:material:32>, <actuallyadditions:block_crystal_empowered>, <thermalfoundation:material:32>], [<modularmachinery:itemmodularium>, <techguns:itemshared:65>, <modularmachinery:itemmodularium>]]);
recipes.addShaped(<modularmachinery:blockcontroller>, [[<modularmachinery:itemmodularium>, <extrautils2:screen>, <modularmachinery:itemmodularium>], [<refinedstorage:processor:4>, <actuallyadditions:block_crystal_empowered>, <refinedstorage:processor:4>], [<modularmachinery:itemmodularium>, <zcontent:server2>, <modularmachinery:itemmodularium>]]);
recipes.addShaped(<modularmachinery:blockenergyoutputhatch>, [[<redstonearsenal:material:160>], [<modularmachinery:blockcasing>], [<minecraft:hopper>]]);
recipes.addShaped(<modularmachinery:blockenergyoutputhatch:1>, [[<redstonearsenal:material:160>], [<modularmachinery:blockenergyoutputhatch>], [<minecraft:hopper>]]);
recipes.addShaped(<modularmachinery:blockenergyoutputhatch:2>, [[<redstonearsenal:material:160>], [<modularmachinery:blockenergyoutputhatch:1>], [<minecraft:hopper>]]);
recipes.addShaped(<modularmachinery:blockenergyoutputhatch:3>, [[<redstonearsenal:material:160>], [<modularmachinery:blockenergyoutputhatch:2>], [<minecraft:hopper>]]);
recipes.addShaped(<modularmachinery:blockenergyoutputhatch:4>, [[<redstonearsenal:material:160>], [<modularmachinery:blockenergyoutputhatch:3>], [<minecraft:hopper>]]);
recipes.addShaped(<modularmachinery:blockenergyoutputhatch:5>, [[<redstonearsenal:material:160>], [<modularmachinery:blockenergyoutputhatch:4>], [<minecraft:hopper>]]);
recipes.addShaped(<modularmachinery:blockenergyoutputhatch:6>, [[<redstonearsenal:material:160>], [<modularmachinery:blockenergyoutputhatch:5>], [<minecraft:hopper>]]);
recipes.addShaped(<modularmachinery:blockenergyoutputhatch:7>, [[null, <redstonearsenal:material:160>], [<quantumstorage:quantum_battery>, <modularmachinery:blockenergyoutputhatch:6>, <quantumstorage:quantum_battery>], [null, <minecraft:hopper>]]);
recipes.addShaped(<modularmachinery:blockenergyinputhatch>, [[<minecraft:hopper>], [<modularmachinery:blockcasing>], [<redstonearsenal:material:160>]]);
recipes.addShaped(<modularmachinery:blockenergyinputhatch:1>, [[<minecraft:hopper>], [<modularmachinery:blockenergyinputhatch>], [<redstonearsenal:material:160>]]);
recipes.addShaped(<modularmachinery:blockenergyinputhatch:2>, [[<minecraft:hopper>], [<modularmachinery:blockenergyinputhatch:1>], [<redstonearsenal:material:160>]]);
recipes.addShaped(<modularmachinery:blockenergyinputhatch:3>, [[<minecraft:hopper>], [<modularmachinery:blockenergyinputhatch:2>], [<redstonearsenal:material:160>]]);
recipes.addShaped(<modularmachinery:blockenergyinputhatch:4>, [[<minecraft:hopper>], [<modularmachinery:blockenergyinputhatch:3>], [<redstonearsenal:material:160>]]);
recipes.addShaped(<modularmachinery:blockenergyinputhatch:5>, [[<minecraft:hopper>], [<modularmachinery:blockenergyinputhatch:4>], [<redstonearsenal:material:160>]]);
recipes.addShaped(<modularmachinery:blockenergyinputhatch:6>, [[<minecraft:hopper>], [<modularmachinery:blockenergyinputhatch:5>], [<redstonearsenal:material:160>]]);
recipes.addShaped(<modularmachinery:blockenergyinputhatch:7>, [[null, <minecraft:hopper>], [<quantumstorage:quantum_battery>, <modularmachinery:blockenergyinputhatch:6>, <quantumstorage:quantum_battery>], [null, <redstonearsenal:material:160>]]);
recipes.addShaped(<modularmachinery:blockoutputbus>, [[<ore:chest>], [<modularmachinery:blockcasing>], [<minecraft:hopper>]]);
recipes.addShaped(<modularmachinery:blockoutputbus:1>, [[<ore:chest>], [<modularmachinery:blockoutputbus>], [<minecraft:hopper>]]);
recipes.addShaped(<modularmachinery:blockoutputbus:2>, [[<ore:chest>], [<modularmachinery:blockoutputbus:1>], [<minecraft:hopper>]]);
recipes.addShaped(<modularmachinery:blockoutputbus:3>, [[<ore:chest>], [<modularmachinery:blockoutputbus:2>], [<minecraft:hopper>]]);
recipes.addShaped(<modularmachinery:blockoutputbus:4>, [[<ore:chest>], [<modularmachinery:blockoutputbus:3>], [<minecraft:hopper>]]);
recipes.addShaped(<modularmachinery:blockoutputbus:5>, [[<ore:chest>], [<modularmachinery:blockoutputbus:4>], [<minecraft:hopper>]]);
recipes.addShaped(<modularmachinery:blockoutputbus:6>, [[<ore:chest>], [<modularmachinery:blockoutputbus:5>], [<minecraft:hopper>]]);
recipes.addShaped(<modularmachinery:blockinputbus>, [[<minecraft:hopper>], [<modularmachinery:blockcasing>], [<ore:chest>]]);
recipes.addShaped(<modularmachinery:blockinputbus:1>, [[<minecraft:hopper>], [<modularmachinery:blockinputbus>], [<ore:chest>]]);
recipes.addShaped(<modularmachinery:blockinputbus:2>, [[<minecraft:hopper>], [<modularmachinery:blockinputbus:1>], [<ore:chest>]]);
recipes.addShaped(<modularmachinery:blockinputbus:3>, [[<minecraft:hopper>], [<modularmachinery:blockinputbus:2>], [<ore:chest>]]);
recipes.addShaped(<modularmachinery:blockinputbus:4>, [[<minecraft:hopper>], [<modularmachinery:blockinputbus:3>], [<ore:chest>]]);
recipes.addShaped(<modularmachinery:blockinputbus:5>, [[<minecraft:hopper>], [<modularmachinery:blockinputbus:4>], [<ore:chest>]]);
recipes.addShaped(<modularmachinery:blockinputbus:6>, [[<minecraft:hopper>], [<modularmachinery:blockinputbus:5>], [<ore:chest>]]);
recipes.addShaped(<modularmachinery:blockfluidoutputhatch>, [[<minecraft:bucket>], [<modularmachinery:blockcasing>], [<minecraft:hopper>]]);
recipes.addShaped(<modularmachinery:blockfluidoutputhatch:1>, [[<minecraft:bucket>], [<modularmachinery:blockfluidoutputhatch>], [<minecraft:hopper>]]);
recipes.addShaped(<modularmachinery:blockfluidoutputhatch:2>, [[<minecraft:bucket>], [<modularmachinery:blockfluidoutputhatch:1>], [<minecraft:hopper>]]);
recipes.addShaped(<modularmachinery:blockfluidoutputhatch:3>, [[<minecraft:bucket>], [<modularmachinery:blockfluidoutputhatch:2>], [<minecraft:hopper>]]);
recipes.addShaped(<modularmachinery:blockfluidoutputhatch:4>, [[<minecraft:bucket>], [<modularmachinery:blockfluidoutputhatch:3>], [<minecraft:hopper>]]);
recipes.addShaped(<modularmachinery:blockfluidoutputhatch:5>, [[<minecraft:bucket>], [<modularmachinery:blockfluidoutputhatch:4>], [<minecraft:hopper>]]);
recipes.addShaped(<modularmachinery:blockfluidoutputhatch:6>, [[<minecraft:bucket>], [<modularmachinery:blockfluidoutputhatch:5>], [<minecraft:hopper>]]);
recipes.addShaped(<modularmachinery:blockfluidoutputhatch:7>, [[null, <minecraft:bucket>], [<quantumstorage:quantum_tank>, <modularmachinery:blockfluidoutputhatch:6>, <quantumstorage:quantum_tank>], [null, <minecraft:hopper>]]);
recipes.addShaped(<modularmachinery:blockfluidinputhatch>, [[<minecraft:hopper>], [<modularmachinery:blockcasing>], [<minecraft:bucket>]]);
recipes.addShaped(<modularmachinery:blockfluidinputhatch:1>, [[<minecraft:hopper>], [<modularmachinery:blockfluidinputhatch>], [<minecraft:bucket>]]);
recipes.addShaped(<modularmachinery:blockfluidinputhatch:2>, [[<minecraft:hopper>], [<modularmachinery:blockfluidinputhatch:1>], [<minecraft:bucket>]]);
recipes.addShaped(<modularmachinery:blockfluidinputhatch:3>, [[<minecraft:hopper>], [<modularmachinery:blockfluidinputhatch:2>], [<minecraft:bucket>]]);
recipes.addShaped(<modularmachinery:blockfluidinputhatch:4>, [[<minecraft:hopper>], [<modularmachinery:blockfluidinputhatch:3>], [<minecraft:bucket>]]);
recipes.addShaped(<modularmachinery:blockfluidinputhatch:5>, [[<minecraft:hopper>], [<modularmachinery:blockfluidinputhatch:4>], [<minecraft:bucket>]]);
recipes.addShaped(<modularmachinery:blockfluidinputhatch:6>, [[<minecraft:hopper>], [<modularmachinery:blockfluidinputhatch:5>], [<minecraft:bucket>]]);
recipes.addShaped(<immersiveengineering:wirecoil> * 4, [[null, <ore:wireCopper>, null], [<ore:wireCopper>, <immersiveengineering:material>, <ore:wireCopper>], [null, <ore:wireCopper>, null]]);
recipes.addShaped(<immersiveengineering:wirecoil:1> * 4, [[null, <ore:wireElectrum>, null], [<ore:wireElectrum>, <immersiveengineering:material>, <ore:wireElectrum>], [null, <ore:wireElectrum>, null]]);
recipes.addShaped(<immersiveengineering:wirecoil:2> * 4, [[null, <ore:wireSteel>, null], [<ore:wireAluminum>, <immersiveengineering:material>, <ore:wireAluminum>], [null, <ore:wireSteel>, null]]);
recipes.addShaped(<immersiveengineering:wirecoil:2> * 4, [[null, <ore:wireAluminum>, null], [<ore:wireSteel>, <immersiveengineering:material>, <ore:wireSteel>], [null, <ore:wireAluminum>, null]]);
recipes.addShaped(<immersiveengineering:wirecoil:3> * 4, [[null, <ore:fiberHemp>, null], [<ore:fiberHemp>, <immersiveengineering:material>, <ore:fiberHemp>], [null, <ore:fiberHemp>, null]]);
recipes.addShaped(<immersiveengineering:wirecoil:4> * 4, [[null, <ore:wireSteel>, null], [<ore:wireSteel>, <immersiveengineering:material>, <ore:wireSteel>], [null, <ore:wireSteel>, null]]);
recipes.addShaped(<immersiveengineering:wirecoil:5> * 4, [[null, <ore:wireAluminum>, null], [<minecraft:redstone>, <immersiveengineering:material>, <minecraft:redstone>], [null, <ore:wireAluminum>, null]]);
recipes.addShaped(<immersiveengineering:wirecoil:5> * 4, [[null, <minecraft:redstone>, null], [<ore:wireAluminum>, <immersiveengineering:material>, <ore:wireAluminum>], [null, <minecraft:redstone>, null]]);
recipes.addShaped(<cyclicmagic:crystal_pickaxe>, [[<cyclicmagic:crystallized_obsidian>, <cyclicmagic:crystallized_obsidian>, <cyclicmagic:crystallized_obsidian>], [null, <jaopca:item_stickdiamond>, null], [null, <jaopca:item_stickdiamond>, null]]);
recipes.addShaped(<cyclicmagic:crystal_axe>, [[null, <cyclicmagic:crystallized_obsidian>, <cyclicmagic:crystallized_obsidian>], [null, <jaopca:item_stickdiamond>, <cyclicmagic:crystallized_obsidian>], [null, <jaopca:item_stickdiamond>, null]]);
recipes.addShaped(<cyclicmagic:crystal_axe>, [[<cyclicmagic:crystallized_obsidian>, <cyclicmagic:crystallized_obsidian>, null], [<cyclicmagic:crystallized_obsidian>, <jaopca:item_stickdiamond>, null], [null, <jaopca:item_stickdiamond>, null]]);
recipes.addShaped(<cyclicmagic:crystal_spade>, [[null, <cyclicmagic:crystallized_obsidian>, null], [null, <jaopca:item_stickdiamond>, null], [null, <jaopca:item_stickdiamond>, null]]);
recipes.addShaped(<cyclicmagic:crystal_hoe>, [[null, <cyclicmagic:crystallized_obsidian>, <cyclicmagic:crystallized_obsidian>], [null, <jaopca:item_stickdiamond>, null], [null, <jaopca:item_stickdiamond>, null]]);
recipes.addShaped(<cyclicmagic:crystal_hoe>, [[<cyclicmagic:crystallized_obsidian>, <cyclicmagic:crystallized_obsidian>, null], [null, <jaopca:item_stickdiamond>, null], [null, <jaopca:item_stickdiamond>, null]]);
recipes.addShaped(<cyclicmagic:crystal_sword>, [[null, <cyclicmagic:crystallized_obsidian>, null], [null, <cyclicmagic:crystallized_obsidian>, null], [null, <jaopca:item_stickdiamond>, null]]);
recipes.addShaped(<cyclicmagic:mattock>, [[<techguns:itemshared:51>, <techguns:itemshared:51>, <techguns:itemshared:51>],[null, <techguns:itemshared:103>, <techguns:itemshared:51>], [<techguns:itemshared:103>, null, <techguns:itemshared:51>]]);
//File End
