#replaceAllOccurences-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
recipes.replaceAllOccurences(<actuallyadditions:item_misc:19>, <extendedcrafting:material:40>);
recipes.replaceAllOccurences(<industrialforegoing:plastic>, <ore:sheetPlastic>);
recipes.replaceAllOccurences(<techguns:itemshared:55>, <ore:sheetPlastic>);
recipes.replaceAllOccurences(<teslacorelib:machine_case>, <zcontent:machineframe>);
recipes.replaceAllOccurences(<ore:gearDiamond>, <ore:gearPlatinum>);
recipes.replaceAllOccurences(<ore:gearGold>, <ore:gearElectrumFlux>);
recipes.replaceAllOccurences(<tp:dragon_scale>, <mysticalagradditions:stuff:3>);

#REMOVE BY MOD-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
recipes.removeByMod("better_diving");
recipes.removeByMod("deepmoblearning");
recipes.removeByMod("projecte");
recipes.removeByMod("projectex");
recipes.removeByMod("hammercore");
recipes.removeByMod("unstabletools");
recipes.removeByMod("modularmachinery");
recipes.removeByMod("quantumstorage");
recipes.removeByMod("youmatter");
recipes.removeByMod("playerstorage");
recipes.removeByMod("refinedstorage");
recipes.removeByMod("refinedstorageaddons");
recipes.removeByMod("openglider");
recipes.removeByMod("teslacorelib");
recipes.removeByMod("storagedrawersunlimited");
recipes.removeByMod("redstonefluxarsenal");
recipes.removeByMod("compactstorage");
recipes.removeByMod("danknull");
recipes.removeByMod("storagenetwork");
recipes.removeByMod("eplus");
recipes.removeByMod("akashictome");
recipes.removeByMod("furnus");

#REMOVE-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
recipes.remove(<randomthings:timeinabottle>);
recipes.remove(<randomthings:timeinabottle>);
recipes.remove(<thermaldynamics:filter:3>);
recipes.remove(<thermaldynamics:filter:2>);
recipes.remove(<thermaldynamics:servo>);
recipes.remove(<thermaldynamics:servo:1>);
recipes.remove(<thermaldynamics:filter:1>);
recipes.remove(<thermaldynamics:filter:4>);
recipes.remove(<thermaldynamics:retriever>);
recipes.remove(<thermaldynamics:retriever:1>);
recipes.remove(<thermaldynamics:retriever:2>);
recipes.remove(<thermaldynamics:retriever:3>);
recipes.remove(<thermaldynamics:retriever:4>);
recipes.remove(<thermaldynamics:filter>);
recipes.remove(<thermaldynamics:servo:4>);
recipes.remove(<thermaldynamics:servo:2>);
recipes.remove(<thermaldynamics:servo:3>);
recipes.remove(<storagedrawers:basicdrawers>);
recipes.remove(<storagedrawers:basicdrawers:1>);
recipes.remove(<storagedrawers:basicdrawers:2>);
recipes.remove(<storagedrawers:basicdrawers:3>);
recipes.remove(<storagedrawers:basicdrawers:4>);
recipes.remove(<quark:rune:*>);
recipes.remove(<extrautils2:luxsaber:*>);
recipes.remove(<immersiveengineering:blueprint>);
recipes.remove(<zcontent:server1>);
recipes.remove(<zcontent:server2>);
recipes.remove(<zcontent:server3>);
recipes.remove(<zcontent:terminalserver>);
recipes.remove(<zcontent:transistor>);
recipes.remove(<zcontent:alu>);
recipes.remove(<zcontent:card>);
recipes.remove(<zcontent:chip1>);
recipes.remove(<zcontent:chip2>);
recipes.remove(<zcontent:chip3>);
recipes.remove(<zcontent:componentbus1>);
recipes.remove(<zcontent:componentbus2>);
recipes.remove(<zcontent:componentbus3>);
recipes.remove(<zcontent:cpu1>);
recipes.remove(<zcontent:cpu2>);
recipes.remove(<zcontent:cpu3>);
recipes.remove(<zcontent:cu>);
recipes.remove(<zcontent:datacard1>);
recipes.remove(<zcontent:datacard2>);
recipes.remove(<zcontent:datacard3>);
recipes.remove(<zcontent:graphicscard1>);
recipes.remove(<zcontent:graphicscard2>);
recipes.remove(<zcontent:graphicscard3>);
recipes.remove(<zcontent:hdd1>);
recipes.remove(<zcontent:hdd2>);
recipes.remove(<zcontent:hdd3>);
recipes.remove(<zcontent:printedcircuitboard>);
recipes.remove(<zcontent:ram1>);
recipes.remove(<zcontent:ram2>);
recipes.remove(<zcontent:ram3>);
recipes.remove(<zcontent:rawcircuitboard>);
recipes.remove(<cyclicmagic:plate_push>);
recipes.remove(<cyclicmagic:plate_push_corner>);
recipes.remove(<cyclicmagic:plate_push_med_angle>);
recipes.remove(<cyclicmagic:plate_push_fast>);
recipes.remove(<cyclicmagic:plate_push_fast_corner>);
recipes.remove(<cyclicmagic:plate_push_fast_angle>);
recipes.remove(<cyclicmagic:plate_push_slow>);
recipes.remove(<cyclicmagic:plate_push_slow_corner>);
recipes.remove(<cyclicmagic:plate_push_slow_angle>);
recipes.remove(<cyclicmagic:plate_push_slowest>);
recipes.remove(<cyclicmagic:plate_push_slowest_corner>);
recipes.remove(<cyclicmagic:plate_push_slowest_angle>);
recipes.remove(<cyclicmagic:peat_biomass>);
recipes.remove(<cyclicmagic:peat_biomass>);
recipes.remove(<cyclicmagic:peat_fuel>);
recipes.remove(<cyclicmagic:peat_fuel_enriched>);
recipes.remove(<cyclicmagic:peat_unbaked>);
recipes.remove(<cyclicmagic:peat_baked>);
recipes.remove(<cyclicmagic:peat_farm>);
recipes.remove(<cyclicmagic:peat_generator>);

#REMOVE FURNACE-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
furnace.remove(<refinedstorage:processor:5>, <refinedstorage:processor:2>);
furnace.remove(<refinedstorage:processor:4>, <refinedstorage:processor:1>);
furnace.remove(<refinedstorage:processor:3>, <refinedstorage:processor>);
furnace.remove(<industrialforegoing:plastic>, <industrialforegoing:dryrubber>);
furnace.remove(<minecraft:coal:1>, <thermalfoundation:material:801>);
furnace.remove(<mysticalagriculture:crafting:28>, <mysticalagriculture:soulstone>);
furnace.remove(<techguns:itemshared:55>, <techguns:itemshared:96>);
furnace.remove(<zcontent:printedcircuitboard>, <zcontent:rawcircuitboard>);

#REMOVE BY NAME-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------


recipes.removeByRecipeName("immersiveengineering:material/wire_steel");
recipes.removeByRecipeName("immersiveengineering:material/wire_aluminum");
recipes.removeByRecipeName("immersiveengineering:material/wire_electrum");
recipes.removeByRecipeName("immersiveengineering:material/wire_copper");	
recipes.removeByRecipeName("jaopca:black_gem_ge90o4");
recipes.removeByRecipeName("jaopca:blue_gem_s0wgt9");
recipes.removeByRecipeName("jaopca:green_gem_iuuhpc");
recipes.removeByRecipeName("jaopca:indigo_gem_7rhijp");
recipes.removeByRecipeName("jaopca:orange_gem_qndgeh");
recipes.removeByRecipeName("jaopca:red_gem_a2rw0i");
recipes.removeByRecipeName("jaopca:violet_gem_ja6jo8");
recipes.removeByRecipeName("jaopca:white_gem_qa5cxm");
recipes.removeByRecipeName("jaopca:yellow_gem_pdjqgz");
recipes.removeByRecipeName("tp:unhardened_stone");
recipes.removeByRecipeName("quark:repeater");
recipes.removeByRecipeName("cyclicmagic:item.diode_1");
recipes.removeByRecipeName("minecraft:repeater");
recipes.removeByRecipeName("minecraft:comparator");
recipes.removeByRecipeName("quark:redstone_inductor");
recipes.removeByRecipeName("quark:redstone_randomizer");
recipes.removeByRecipeName("darkutils:timer");
recipes.removeByRecipeName("rftools:infused_enderpearl");
recipes.removeByRecipeName("rftools:infused_diamond");
recipes.removeByRecipeName("tp:birthday_pickaxe");
recipes.removeByRecipeName("tp:glass");
recipes.removeByRecipeName("tp:obsidian");
recipes.removeByRecipeName("tp:kappa_pick");
recipes.removeByRecipeName("cyclicmagic:item.sprout_seed_1");
recipes.removeByRecipeName("quark:pipe");
recipes.removeByRecipeName("cyclicmagic:item.dynamite_mining");
recipes.removeByRecipeName("thermalfoundation:material_60");
recipes.removeByRecipeName("mysticalagriculture:core/mystical_fertilizer_2");
recipes.removeByRecipeName("mysticalagriculture:core/mystical_fertilizer");
recipes.removeByRecipeName("cyclicmagic:tile.button_large_1");
recipes.removeByRecipeName("cyclicmagic:tile.moon_sensor_1");
recipes.removeByRecipeName("cyclicmagic:item.heart_food");
recipes.removeByRecipeName("cyclicmagic:item.heart_toxic");
recipes.removeByRecipeName("cyclicmagic:item.password_remote_1");
recipes.removeByRecipeName("cyclicmagic:item.glowing_helmet_1");
recipes.removeByRecipeName("cyclicmagic:tile.spikes_iron_1");
recipes.removeByRecipeName("cyclicmagic:tile.spikes_diamond_1");
recipes.removeByRecipeName("cyclicmagic:tile.wireless_receiver_1");
recipes.removeByRecipeName("cyclicmagic:tile.wireless_transmitter_1");
recipes.removeByRecipeName("cyclicmagic:item.ender_pearl_reuse_1");
recipes.removeByRecipeName("cyclicmagic:item.ender_pearl_mounted_1");
recipes.removeByRecipeName("extrautils2:transfer_pipes");
recipes.removeByRecipeName("cyclicmagic:tile.fluid_pipe_1");
recipes.removeByRecipeName("cyclicmagic:tile.energy_pipe_1");
recipes.removeByRecipeName("cyclicmagic:tile.item_pipe_1");
recipes.removeByRecipeName("cyclicmagic:tile.fluid_pump_1");
recipes.removeByRecipeName("cyclicmagic:tile.energy_pump_1");
recipes.removeByRecipeName("cyclicmagic:tile.item_pump_1");
recipes.removeByRecipeName("cyclicmagic:tile.bundled_pipe_1");
recipes.removeByRecipeName("cyclicmagic:tile.beacon_potion_1");
recipes.removeByRecipeName("cyclicmagic:tile.cable_wireless_fluid_1");
recipes.removeByRecipeName("cyclicmagic:tile.cable_wireless_energy_1");
recipes.removeByRecipeName("cyclicmagic:tile.cable_wireless_1");
recipes.removeByRecipeName("cyclicmagic:tile.battery_1");
recipes.removeByRecipeName("cyclicmagic:tile.water_candle_1");
recipes.removeByRecipeName("tp:stone_hammer");
recipes.removeByRecipeName("enderio:enchanter");
recipes.removeByRecipeName("mob_grinding_utils:mob_swab");
recipes.removeByRecipeName("simplevoidworld:portal");
recipes.removeByRecipeName("tesseract:tesseract");
recipes.removeByRecipeName("mob_grinding_utils:saw");
recipes.removeByRecipeName("cyclicmagic:item.ender_torch_1");
recipes.removeByRecipeName("cyclicmagic:item.ender_torch");
recipes.removeByRecipeName("enderio:upgrade_speed");
recipes.removeByRecipeName("enderio:upgrade_slowness");
recipes.removeByRecipeName("futuremc:wood/planks_from_stripped_dark_oak_log");
recipes.removeByRecipeName("futuremc:wood/planks_from_stripped_acacia_log");
recipes.removeByRecipeName("futuremc:wood/planks_from_stripped_jungle_log");
recipes.removeByRecipeName("futuremc:wood/planks_from_stripped_birch_log");
recipes.removeByRecipeName("futuremc:wood/planks_from_stripped_spruce_log");
recipes.removeByRecipeName("futuremc:wood/planks_from_stripped_oak_log");
recipes.removeByRecipeName("bettermagnets:magnet_t5_ult");
recipes.removeByRecipeName("techguns:revolver");
recipes.removeByRecipeName("techguns:goldenrevolver");
recipes.removeByRecipeName("techguns:itemshared_35_obsidiansteelreceiver");
recipes.removeByRecipeName("tp:bams_pizza");
recipes.removeByRecipeName("compactstorage:chest_builder");
recipes.removeByRecipeName("compactstorage:barrel");
recipes.removeByRecipeName("compactstorage:drum");
recipes.removeByRecipeName("mysticalagriculture:crafting_6");
recipes.removeByRecipeName("mysticalagriculture:crafting_12");
recipes.removeByRecipeName("futuremc:netherite_ingot");
recipes.removeByRecipeName("minecraft:brewing_stand");
recipes.removeByRecipeName("minecraft:enchanting_table");
recipes.removeByRecipeName("enderio:dark_paper_anvil");
recipes.removeByRecipeName("enderio:dark_steel_anvil");
recipes.removeByRecipeName("futuremc:else/smithing_table");
recipes.removeByRecipeName("minecraft:anvil");
recipes.removeByRecipeName("immersiveengineering:material/plate_aluminum");
recipes.removeByRecipeName("immersiveengineering:sheetmetal/aluminum_sheetmetal_uncraft");
recipes.removeByRecipeName("immersiveengineering:material/plate_uranium");
recipes.removeByRecipeName("immersiveengineering:sheetmetal/uranium_sheetmetal_uncraft");
recipes.removeByRecipeName("immersiveengineering:material/plate_steel");
recipes.removeByRecipeName("immersiveengineering:sheetmetal/steel_sheetmetal_uncraft");
recipes.removeByRecipeName("immersiveengineering:material/plate_copper");
recipes.removeByRecipeName("immersiveengineering:sheetmetal/copper_sheetmetal_uncraft");
recipes.removeByRecipeName("immersiveengineering:material/plate_nickel");
recipes.removeByRecipeName("immersiveengineering:sheetmetal/nickel_sheetmetal_uncraft");
recipes.removeByRecipeName("immersiveengineering:material/plate_lead");
recipes.removeByRecipeName("immersiveengineering:sheetmetal/lead_sheetmetal_uncraft");
recipes.removeByRecipeName("immersiveengineering:material/plate_silver");
recipes.removeByRecipeName("immersiveengineering:sheetmetal/silver_sheetmetal_uncraft");
recipes.removeByRecipeName("immersiveengineering:material/plate_constantan");
recipes.removeByRecipeName("immersiveengineering:sheetmetal/constantan_sheetmetal_uncraft");
recipes.removeByRecipeName("immersiveengineering:material/plate_electrum");
recipes.removeByRecipeName("immersiveengineering:sheetmetal/electrum_sheetmetal_uncraft");
recipes.removeByRecipeName("immersiveengineering:material/plate_gold");
recipes.removeByRecipeName("immersiveengineering:sheetmetal/gold_sheetmetal_uncraft");
recipes.removeByRecipeName("immersiveengineering:material/plate_iron");
recipes.removeByRecipeName("immersiveengineering:sheetmetal/iron_sheetmetal_uncraft");
recipes.removeByRecipeName("rsinfinitewireless:infinite_wireless_transmitter");
recipes.removeByRecipeName("cyclicmagic:item.applegold_1");
recipes.removeByRecipeName("cookingforblockheads:sink");
recipes.removeByRecipeName("techguns:simplemachine_11_blast_furnace");
recipes.removeByRecipeName("techguns:simplemachine2_8_grinder");
recipes.removeByRecipeName("chisel:charcoal");
recipes.removeByRecipeName("vt:content/charcoal_block");
recipes.removeByRecipeName("actuallyadditions:recipes121");
recipes.removeByRecipeName("tp:bread_slice");
recipes.removeByRecipeName("mysticalagriculture:charm");
recipes.removeByRecipeName("mysticalagriculture:crafting_13");
recipes.removeByRecipeName("mysticalagriculture:crafting_14");
recipes.removeByRecipeName("mysticalagriculture:crafting_15");
recipes.removeByRecipeName("mysticalagriculture:crafting_16");
recipes.removeByRecipeName("mysticalagradditions:dragon_egg_chunks");
recipes.removeByRecipeName("mysticalagradditions:nugget");
recipes.removeByRecipeName("mysticalagradditions:nether_star_shards");
recipes.removeByRecipeName("mysticalagradditions:resource");        
recipes.removeByRecipeName("mysticalagriculture:crafting_17");
recipes.removeByRecipeName("mysticalagriculture:crafting_18");
recipes.removeByRecipeName("mysticalagriculture:crafting_19");
recipes.removeByRecipeName("mysticalagriculture:crafting_20");
recipes.removeByRecipeName("mysticalagriculture:crafting_21");
recipes.removeByRecipeName("mysticalagradditions:insanium");
recipes.removeByRecipeName("darkutils:compact_wither");
recipes.removeByRecipeName("darkutils:skull_to_witherdust");
recipes.removeByRecipeName("darkutils:deconstruct_wither");
recipes.removeByRecipeName("biomesoplenty:coal_from_ash");
recipes.removeByRecipeName("darkutils:soulsand");
recipes.removeByRecipeName("darkutils:dark_sugar");
recipes.removeByRecipeName("darkutils:unstable_pearl");
recipes.removeByRecipeName("darkutils:dwindlecream");
recipes.removeByRecipeName("darkutils:trap_wither");
recipes.removeByRecipeName("biomesoplenty:ash_block");
recipes.removeByRecipeName("biomesoplenty:gray_dye_from_ash");
recipes.removeByRecipeName("biomesoplenty:coal_from_ash");
recipes.removeByRecipeName("actuallyadditions:recipes53");
recipes.removeByRecipeName("actuallyadditions:recipes54");
recipes.removeByRecipeName("actuallyadditions:recipes55");
recipes.removeByRecipeName("actuallyadditions:recipes56");
recipes.removeByRecipeName("actuallyadditions:recipes122");
recipes.removeByRecipeName("rftools:machine_base");
recipes.removeByRecipeName("rftools:machine_frame");
recipes.removeByRecipeName("extrautils2:teleporter");
recipes.removeByRecipeName("tp:lava_infused_stone");
recipes.removeByRecipeName("cyclicmagic:item.sword_ender_1");
recipes.removeByRecipeName("cyclicmagic:item.sword_slowness_1");
recipes.removeByRecipeName("cyclicmagic:item.sword_weakness_1");
recipes.removeByRecipeName("cyclicmagic:item.mattock_1");
recipes.removeByRecipeName("cyclicmagic:item.crystal_pickaxe_1");
recipes.removeByRecipeName("cyclicmagic:item.crystal_axe_1_2_3");
recipes.removeByRecipeName("cyclicmagic:item.crystal_axe_1");
recipes.removeByRecipeName("cyclicmagic:item.crystal_spade_1");
recipes.removeByRecipeName("cyclicmagic:item.crystal_hoe_1_2_3");
recipes.removeByRecipeName("cyclicmagic:item.crystal_hoe_1");
recipes.removeByRecipeName("cyclicmagic:item.crystal_sword_1");
recipes.removeByRecipeName("cyclicmagic:item.crystallized_obsidian_1");
recipes.removeByRecipeName("immersiveengineering:wirecoils/wirecoil_lv");
recipes.removeByRecipeName("immersiveengineering:wirecoils/wirecoil_mv");
recipes.removeByRecipeName("immersiveengineering:wirecoils/wirecoil_hv");
recipes.removeByRecipeName("immersiveengineering:wirecoils/wirecoil_hv2");
recipes.removeByRecipeName("immersiveengineering:wirecoils/wirecoil_rope");
recipes.removeByRecipeName("immersiveengineering:wirecoils/wirecoil_structural");
recipes.removeByRecipeName("immersiveengineering:wirecoils/wirecoil_redstone2");
recipes.removeByRecipeName("immersiveengineering:wirecoils/wirecoil_redstone");
recipes.removeByRecipeName("tp:wither_helmet");
recipes.removeByRecipeName("tp:wither_chestplate");
recipes.removeByRecipeName("tp:wither_leggings");
recipes.removeByRecipeName("tp:wither_boots");
recipes.removeByRecipeName("enderio:filter_basic");
recipes.removeByRecipeName("enderio:filter_advanced");
recipes.removeByRecipeName("enderio:filter_counting");
recipes.removeByRecipeName("enderio:filter_big");
recipes.removeByRecipeName("enderio:filter_big_advanced");
recipes.removeByRecipeName("enderio:filter_existing");
recipes.removeByRecipeName("enderio:filter_mod");
recipes.removeByRecipeName("enderio:filter_power");
recipes.removeByRecipeName("enderio:filter_redstone_base");
recipes.removeByRecipeName("enderio:filter_fluid");
recipes.removeByRecipeName("enderio:filter_enchantment_big");
recipes.removeByRecipeName("enderio:filter_enchantment");
recipes.removeByRecipeName("immersiveengineering:tool/wirecutters");
recipes.removeByRecipeName("immersiveengineering:tool/hammer");
recipes.removeByRecipeName("storagedrawers:compacting_drawer");
recipes.removeByRecipeName("storagedrawers:controller");
recipes.removeByRecipeName("storagedrawers:controller_slave");
recipes.removeByRecipeName("fluxnetworks:tile.fluxnetworks.fluxplug");
recipes.removeByRecipeName("fluxnetworks:tile.fluxnetworks.fluxpoint");
recipes.removeByRecipeName("redstonearsenal:tool.bow_flux");
recipes.removeByRecipeName("extrautils2:quarry_base");
recipes.removeByRecipeName("extrautils2:quarry_proxy");


recipes.removeByRecipeName("mysticalagradditions:special"); 
recipes.removeByRecipeName("mysticalagradditions:special_1");
recipes.removeByRecipeName("mysticalagradditions:special_2");
recipes.removeByRecipeName("mysticalagradditions:special_3");


recipes.removeByRecipeName("extendedcrafting:black_iron_ingot");
recipes.removeByRecipeName("minecraft:piston");
recipes.removeByRecipeName("quark:sturdy_stone");
recipes.removeByRecipeName("quark:sturdy_stone_1");
recipes.removeByRecipeName("extendedcrafting:luminessence");
recipes.removeByRecipeName("thermalfoundation:material_92");
recipes.removeByRecipeName("futuremc:else/stonecutter");
recipes.removeByRecipeName("techguns:itemshared_94_machinestackupgrade");
recipes.removeByRecipeName("quark:carved_wood");
recipes.removeByRecipeName("quark:carved_wood_1");
recipes.removeByRecipeName("quark:carved_wood_2");
recipes.removeByRecipeName("quark:carved_wood_3");
recipes.removeByRecipeName("quark:carved_wood_4");
recipes.removeByRecipeName("quark:carved_wood_5");
recipes.removeByRecipeName("immersiveengineering:material/gunpowder0");
recipes.removeByRecipeName("immersiveengineering:material/gunpowder1");
recipes.removeByRecipeName("thermalfoundation:gunpowder_1");
recipes.removeByRecipeName("extendedcrafting:ender_ingot");
recipes.removeByRecipeName("extrautils2:unstable_ingot");
recipes.removeByRecipeName("extrautils2:unstable_nugget");
recipes.removeByRecipeName("extrautils2:unstable_unpack");
recipes.removeByRecipeName("extrautils2:stable_unstable_ingot");
recipes.removeByRecipeName("enderio:enhanced_machine_dye");
recipes.removeByRecipeName("enderio:machine_dye");
recipes.removeByRecipeName("enderio:soul_machine_dye");
recipes.removeByRecipeName("techguns:basicmachine_0_ammo_press");
recipes.removeByRecipeName("techguns:basicmachine_1_metal_press");
recipes.removeByRecipeName("techguns:basicmachine_1_metal_press_alt");
recipes.removeByRecipeName("techguns:basicmachine_2_chem_lab");
recipes.removeByRecipeName("techguns:simplemachine_10_charging_station");
recipes.removeByRecipeName("quark:iron_plate");
recipes.removeByRecipeName("techguns:itemshared_62_copperwire");
recipes.removeByRecipeName("minecraft:leather");
recipes.removeByRecipeName("actuallyadditions:recipes225");
recipes.removeByRecipeName("alchemistry:electrolyzer");
recipes.removeByRecipeName("alchemistry:chemical_dissolver");
recipes.removeByRecipeName("alchemistry:chemical_combiner");
recipes.removeByRecipeName("alchemistry:evaporator");
recipes.removeByRecipeName("alchemistry:atomizer");
recipes.removeByRecipeName("alchemistry:liquifier");
recipes.removeByRecipeName("techguns:itemshared_57_mechanicalpartsiron");



recipes.removeByRecipeName("quark:purple_shulker_box");
recipes.removeByRecipeName("minecraft:purple_shulker_box");
recipes.removeByRecipeName("techguns:itemshared_7_rocket");
recipes.removeByRecipeName("immersiveengineering:stone_decoration/insulating_glass");

recipes.removeByRecipeName("actuallyadditions:recipes109");
recipes.removeByRecipeName("techguns:itemshared_68_coil");
recipes.removeByRecipeName("techguns:itemshared_72_pumpmechanism");
recipes.removeByRecipeName("virtualmachines:material");
recipes.removeByRecipeName("virtualmachines:virtual_machine");
recipes.removeByRecipeName("virtualmachines:virtual_machine_1");
recipes.removeByRecipeName("virtualmachines:virtual_machine_2");
recipes.removeByRecipeName("virtualmachines:virtual_machine_3");
recipes.removeByRecipeName("virtualmachines:virtual_machine_4");
recipes.removeByRecipeName("virtualmachines:virtual_machine_5");
recipes.removeByRecipeName("draconicevolution:draconic_core");
recipes.removeByRecipeName("draconicevolution:wyvern_core");
recipes.removeByRecipeName("redstonearsenal:gem_crystal_flux");
recipes.removeByRecipeName("extrautils2:moon_stone");
recipes.removeByRecipeName("extrautils2:moon_stone_adv");
recipes.removeByRecipeName("tp:colored_dust.0");
recipes.removeByRecipeName("tp:colored_dust.1");
recipes.removeByRecipeName("tp:colored_dust.2");
recipes.removeByRecipeName("tp:colored_dust.3");
recipes.removeByRecipeName("tp:colored_dust.4");
recipes.removeByRecipeName("tp:colored_dust.5");
recipes.removeByRecipeName("tp:colored_dust.6");
recipes.removeByRecipeName("tp:colored_dust.7");
recipes.removeByRecipeName("tp:colored_dust.8");
recipes.removeByRecipeName("tp:colored_dust.9");
recipes.removeByRecipeName("tp:colored_dust.10");
recipes.removeByRecipeName("tp:colored_dust.11");
recipes.removeByRecipeName("tp:colored_dust.12");
recipes.removeByRecipeName("tp:colored_dust.13");
recipes.removeByRecipeName("tp:colored_dust.14");
recipes.removeByRecipeName("tp:infin_water_bucket");
recipes.removeByRecipeName("fluxnetworks:item.fluxnetworks.fluxcore");
recipes.removeByRecipeName("extrautils2:screen");
recipes.removeByRecipeName("extrautils2:sun_crystal");
recipes.removeByRecipeName("randomthings:ingredient_spectreingot_2");
recipes.removeByRecipeName("randomthings:ingredient_spectreingot");
recipes.removeByRecipeName("extrautils2:redstone_eye");
recipes.removeByRecipeName("randomthings:stableenderpearl");
recipes.removeByRecipeName("minecraft:ender_eye");
recipes.removeByRecipeName("torchmaster:frozen_pearl");
recipes.removeByRecipeName("immersiveengineering:metal_decoration/light_engineering");
recipes.removeByRecipeName("immersiveengineering:metal_decoration/heavy_engineering");
recipes.removeByRecipeName("immersiveengineering:metal_decoration/radiator");
recipes.removeByRecipeName("immersiveengineering:metal_decoration/redstone_engineering");
recipes.removeByRecipeName("avaritia:blocks/crafting/extreme_crafting_table");
recipes.removeByRecipeName("avaritia:items/resource/diamond_lattice");
recipes.removeByRecipeName("chisel:voidstone");
recipes.removeByRecipeName("chisel:voidstone2");
recipes.removeByRecipeName("thermalfoundation:material_86");
recipes.removeByRecipeName("avaritia:items/resource/crystal_matrix_ingot");
recipes.removeByRecipeName("techguns:itemshared_104_rcheatray");
recipes.removeByRecipeName("techguns:simplemachine_8_camo_bench");
recipes.removeByRecipeName("randomthings:spectreilluminator");
recipes.removeByRecipeName("extrautils2:chicken_ring");
recipes.removeByRecipeName("extrautils2:squid_ring");
recipes.removeByRecipeName("extrautils2:angel_ring_convert_0");
recipes.removeByRecipeName("extrautils2:angel_ring_0");
recipes.removeByRecipeName("extrautils2:angel_ring_convert_1");
recipes.removeByRecipeName("extrautils2:angel_ring_1");
recipes.removeByRecipeName("extrautils2:angel_ring_convert_2");
recipes.removeByRecipeName("extrautils2:angel_ring_2");
recipes.removeByRecipeName("extrautils2:angel_ring_convert_3");
recipes.removeByRecipeName("extrautils2:angel_ring_3");
recipes.removeByRecipeName("extrautils2:angel_ring_convert_4");
recipes.removeByRecipeName("extrautils2:angel_ring_4");
recipes.removeByRecipeName("extrautils2:angel_ring_convert_5");
recipes.removeByRecipeName("extrautils2:angel_ring_5");
recipes.removeByRecipeName("randomthings:spectreaxe");
recipes.removeByRecipeName("randomthings:spectreshovel");
recipes.removeByRecipeName("randomthings:spectrepickaxe");
recipes.removeByRecipeName("randomthings:spectresword");
recipes.removeByRecipeName("engineersdecor:dependent/small_solar_panel_recipe");
recipes.removeByRecipeName("arcanearchives:radiant_chest1");
recipes.removeByRecipeName("everlastingabilities:ability_bottle");
recipes.removeByRecipeName("biomesoplenty:terrestrial_artifact");
recipes.removeByRecipeName("randomthings:enderbucket");
recipes.removeByRecipeName("randomthings:reinforcedenderbucket");
recipes.removeByRecipeName("techguns:minigun_alt");
recipes.removeByRecipeName("techguns:minigun");
recipes.removeByRecipeName("minecraft:observer");
recipes.removeByRecipeName("darkutils:convert_bud");
recipes.removeByRecipeName("randomthings:igniter");
recipes.removeByRecipeName("minecraft:dropper");
recipes.removeByRecipeName("minecraft:dispenser");
recipes.removeByRecipeName("randomthings:blockbreaker");
recipes.removeByRecipeName("randomthings:potionvaporizer");
recipes.removeByRecipeName("quark:soul_powder");
recipes.removeByRecipeName("enderio:enhanced_chassis_parts");
recipes.removeByRecipeName("enderio:simple_chassis_parts");
recipes.removeByRecipeName("enderio:chassis_parts");
recipes.removeByRecipeName("enderio:conduit_refined_storage");
recipes.removeByRecipeName("enderio:upgrade_conduit_refined_storage");
recipes.removeByRecipeName("tp:pouch");
recipes.removeByRecipeName("tp:enderpearl");
recipes.removeByRecipeName("quark:pickarang");
recipes.removeByRecipeName("quark:rope");
recipes.removeByRecipeName("randomthings:ingredient_eviltear");
recipes.removeByRecipeName("extrautils2:compound_bow");
recipes.removeByRecipeName("extrautils2:fire_axe");
recipes.removeByRecipeName("extrautils2:kikoku");
recipes.removeByRecipeName("actuallyadditions:recipes17");
recipes.removeByRecipeName("randomthings:advancedredstonetorch_on");
recipes.removeByRecipeName("draconicevolution:fusion_crafting_core");
recipes.removeByRecipeName("denseneutroncollectors:compressed_neutron_collector_reverse");
recipes.removeByRecipeName("denseneutroncollectors:double_compressed_neutron_collector_reverse");
recipes.removeByRecipeName("denseneutroncollectors:compressed_neutron_collector");
recipes.removeByRecipeName("denseneutroncollectors:triple_compressed_neutron_collector_reverse");
recipes.removeByRecipeName("denseneutroncollectors:double_compressed_neutron_collector");
recipes.removeByRecipeName("denseneutroncollectors:triple_compressed_neutron_collector");
recipes.removeByRecipeName("alchemistry:fission_casing");
recipes.removeByRecipeName("alchemistry:fission_core");
recipes.removeByRecipeName("alchemistry:fission_controller");
recipes.removeByRecipeName("alchemistry:fusion_casing");
recipes.removeByRecipeName("alchemistry:fusion_core");
recipes.removeByRecipeName("alchemistry:fusion_controller");
recipes.removeByRecipeName("extendedcrafting:frame");
recipes.removeByRecipeName("extendedcrafting:lamp_glowstone");
recipes.removeByRecipeName("extendedcrafting:lamp_luminessence");
recipes.removeByRecipeName("extendedcrafting:interface");
recipes.removeByRecipeName("extendedcrafting:compressor");
recipes.removeByRecipeName("extendedcrafting:crafting_core");
recipes.removeByRecipeName("techguns:itemshared_131_plasmagenerator");
recipes.removeByRecipeName("techguns:multiblockmachine_0_fabricator_housing");
recipes.removeByRecipeName("techguns:multiblockmachine_1_fabricator_glass");
recipes.removeByRecipeName("techguns:multiblockmachine_2_fabricator_controller");
recipes.removeByRecipeName("techguns:multiblockmachine_3_reactionchamber_housing");
recipes.removeByRecipeName("techguns:multiblockmachine_4_reactionchamber_glass");
recipes.removeByRecipeName("techguns:multiblockmachine_5_reactionchamber_controller");
recipes.removeByRecipeName("thermalfoundation:upgrade_3");
recipes.removeByRecipeName("thermalfoundation:upgrade_2");
recipes.removeByRecipeName("thermalfoundation:upgrade_1");
recipes.removeByRecipeName("thermalfoundation:upgrade");
recipes.removeByRecipeName("traverse:red_rock_furnace");
recipes.removeByRecipeName("traverse:blue_rock_furnace");
recipes.removeByRecipeName("minecraft:furnace");
recipes.removeByRecipeName("futuremc:else/blast_furnace");
recipes.removeByRecipeName("futuremc:else/smoker");
recipes.removeByRecipeName("extendedcrafting:table_basic");
recipes.removeByRecipeName("extendedcrafting:table_advanced");
recipes.removeByRecipeName("extendedcrafting:table_elite");
recipes.removeByRecipeName("extendedcrafting:table_ultimate");
recipes.removeByRecipeName("extendedcrafting:crafting_catalyst_basic");
recipes.removeByRecipeName("extendedcrafting:crafting_catalyst_advanced");
recipes.removeByRecipeName("extendedcrafting:crafting_catalyst_elite");
recipes.removeByRecipeName("extendedcrafting:crafting_catalyst_ultimate");
recipes.removeByRecipeName("extendedcrafting:crafting_catalyst_crystaltine");
recipes.removeByRecipeName("extendedcrafting:catalyst_ultimate");
recipes.removeByRecipeName("extendedcrafting:crafting_component_basic");
recipes.removeByRecipeName("extendedcrafting:crafting_component_advanced");
recipes.removeByRecipeName("extendedcrafting:crafting_component_elite");
recipes.removeByRecipeName("extendedcrafting:crafting_component_ultimate");
recipes.removeByRecipeName("extendedcrafting:crafting_component_crystaltine");
recipes.removeByRecipeName("extendedcrafting:component_ultimate");
recipes.removeByRecipeName("extrautils2:machine_base");
recipes.removeByRecipeName("thermalexpansion:frame");
recipes.removeByRecipeName("thermalexpansion:frame_1");
recipes.removeByRecipeName("thermalexpansion:frame_2");
recipes.removeByRecipeName("actuallyadditions:recipes124");
recipes.removeByRecipeName("actuallyadditions:recipes125");
recipes.removeByRecipeName("enderio:unsouled_chassis");
recipes.removeByRecipeName("enderio:simple_chassis");
recipes.removeByRecipeName("enderio:end_steel_chassis");
recipes.removeByRecipeName("thermalfoundation:material_82");
recipes.removeByRecipeName("thermalfoundation:material_83");
recipes.removeByRecipeName("thermalfoundation:material_84");
recipes.removeByRecipeName("thermalfoundation:material_85");
recipes.removeByRecipeName("techguns:itemshared_70_electricengine");
recipes.removeByRecipeName("techguns:itemshared_65_circuitboard");
recipes.removeByRecipeName("techguns:itemshared_66_circuitboardelite");
recipes.removeByRecipeName("thermalfoundation:fertilizer_1");
recipes.removeByRecipeName("thermalfoundation:fertilizer_3");
recipes.removeByRecipeName("thermalfoundation:material_59");
recipes.removeByRecipeName("quark:hopper");
recipes.removeByRecipeName("extrautils2:shortcut_hopper");
recipes.removeByRecipeName("minecraft:hopper");
recipes.removeByRecipeName("darkutils-unstable_pearl-modified");
recipes.removeByRecipeName("randomthings:eclipsedclock");
recipes.removeByRecipeName("integrateddynamics:energy_battery");
recipes.removeByRecipeName("fluxnetworks:tile.fluxnetworks.fluxblock");
recipes.removeByRecipeName("fluxnetworks:tile.fluxnetworks.fluxstorage");
recipes.removeByRecipeName("fluxnetworks:tile.fluxnetworks.herculeanfluxstorage");
recipes.removeByRecipeName("fluxnetworks:tile.fluxnetworks.gargantuanfluxstorage");
recipes.removeByRecipeName("storagedrawers:trim_oak");
recipes.removeByRecipeName("storagedrawers:trim_spruce");
recipes.removeByRecipeName("storagedrawers:trim_birch");
recipes.removeByRecipeName("storagedrawers:trim_jungle");
recipes.removeByRecipeName("storagedrawers:trim_acacia");
recipes.removeByRecipeName("storagedrawers:trim_dark_oak");
recipes.removeByRecipeName("simplyjetpacks:upgraderecipe9");
recipes.removeByRecipeName("industrialforegoing:infinity_drill_0");
recipes.removeByRecipeName("actuallyadditions:recipes44");
recipes.removeByRecipeName("actuallyadditions:recipes47");
recipes.removeByRecipeName("quark:iron_plate_1");

#WIP
#refinedstorage
recipes.addShaped(<refinedstorage:processor_binding>, [[null, <jaopca:item_nuggetquartz>, null],[<zcontent:cold_iron_ingot>, null, <zcontent:cold_iron_ingot>], [<jaopca:item_nuggetquartz>, <thermalfoundation:material:162>, <jaopca:item_nuggetquartz>]]);

recipes.addShapeless(<refinedstorage:writer>, [<refinedstorage:cable>,<jaopca:item_platestainlesssteel>]);
recipes.addShapeless(<refinedstorage:reader>, [<refinedstorage:cable>,<jaopca:item_platedarksteel>]);
recipes.addShapeless(<refinedstorage:destructor>, [<refinedstorage:cable>,<jaopca:item_plategalvanizedsteel>]);
recipes.addShapeless(<refinedstorage:constructor>, [<refinedstorage:cable>,<jaopca:item_plateelectricalsteel>]);
recipes.addShapeless(<refinedstorage:external_storage>, [<refinedstorage:cable>,<thermalfoundation:material:352>]);
recipes.addShapeless(<refinedstorage:exporter>, [<refinedstorage:cable>,<jaopca:item_plateconstructionalloy>]);
recipes.addShapeless(<refinedstorage:importer>, [<refinedstorage:cable>,<thermalfoundation:material:32>]);
recipes.addShaped(<refinedstorage:disk_manipulator>, [[<refinedstorage:quartz_enriched_iron>, <refinedstorage:storage_housing>, <refinedstorage:quartz_enriched_iron>], [<refinedstorage:core>, <refinedstorage:machine_casing>, <refinedstorage:core:1>], [<refinedstorage:quartz_enriched_iron>, <refinedstorage:storage_housing>, <refinedstorage:quartz_enriched_iron>]]);
recipes.addShaped(<refinedstorage:network_receiver>, [[<zcontent:chip3>, <zcontent:chip3>, <zcontent:chip3>], [<refinedstorage:core>, <refinedstorage:machine_casing>, <refinedstorage:core:1>], [<minecraft:ender_pearl>, <minecraft:ender_pearl>, <minecraft:ender_pearl>]]);
recipes.addShaped(<refinedstorage:network_transmitter>, [[<minecraft:ender_pearl>, <minecraft:ender_pearl>, <minecraft:ender_pearl>], [<refinedstorage:core>, <refinedstorage:machine_casing>, <refinedstorage:core:1>], [<zcontent:chip3>, <zcontent:chip3>, <zcontent:chip3>]]);
recipes.addShaped(<refinedstorage:quartz_enriched_iron_block>, [[<refinedstorage:quartz_enriched_iron>, <refinedstorage:quartz_enriched_iron>, <refinedstorage:quartz_enriched_iron>], [<refinedstorage:quartz_enriched_iron>, <refinedstorage:quartz_enriched_iron>, <refinedstorage:quartz_enriched_iron>], [<refinedstorage:quartz_enriched_iron>, <refinedstorage:quartz_enriched_iron>, <refinedstorage:quartz_enriched_iron>]]);
recipes.addShapeless(<refinedstorage:fluid_interface>, [<refinedstorage:interface>, <zcontent:chip3>, <minecraft:bucket>]);
recipes.addShaped(<refinedstorage:interface>, [[<refinedstorage:quartz_enriched_iron>, <refinedstorage:importer>, <refinedstorage:quartz_enriched_iron>], [<minecraft:redstone>, <refinedstorage:machine_casing>, <minecraft:redstone>], [<refinedstorage:quartz_enriched_iron>, <refinedstorage:exporter>, <refinedstorage:quartz_enriched_iron>]]);
recipes.addShapeless(<refinedstorage:relay>, [<refinedstorage:machine_casing>, <refinedstorage:cable>, <minecraft:redstone_torch>]);
recipes.addShaped(<refinedstorage:disk_drive>, [[<refinedstorage:quartz_enriched_iron>, <ore:chest>, <refinedstorage:quartz_enriched_iron>], [<refinedstorage:quartz_enriched_iron>, <refinedstorage:machine_casing>, <refinedstorage:quartz_enriched_iron>], [<refinedstorage:quartz_enriched_iron>, <zcontent:chip3>, <refinedstorage:quartz_enriched_iron>]]);
recipes.addShaped(<refinedstorage:security_manager>, [[<refinedstorage:quartz_enriched_iron>, <ore:chest>, <refinedstorage:quartz_enriched_iron>], [<refinedstorage:security_card>, <refinedstorage:machine_casing>, <refinedstorage:security_card>], [<refinedstorage:quartz_enriched_iron>, <refinedstorage:security_card>, <refinedstorage:quartz_enriched_iron>]]);
recipes.addShaped(<refinedstorage:storage_monitor>, [[<zcontent:chip1>, <refinedstorage:core>, <ore:blockGlass>], [<refinedstorage:quartz_enriched_iron>, <refinedstorage:machine_casing>, <ore:blockGlass>], [<zcontent:chip1>, <refinedstorage:core:1>, <ore:blockGlass>]]);
recipes.addShaped(<refinedstorage:crafting_monitor>, [[<zcontent:chip2>, <refinedstorage:pattern>, <ore:blockGlass>], [<refinedstorage:quartz_enriched_iron>, <refinedstorage:machine_casing>, <ore:blockGlass>], [<zcontent:chip2>, <refinedstorage:pattern>, <ore:blockGlass>]]);
recipes.addShaped(<refinedstorage:detector>, [[<refinedstorage:quartz_enriched_iron>, <minecraft:redstone_torch>, <refinedstorage:quartz_enriched_iron>], [<minecraft:comparator>, <refinedstorage:machine_casing>, <minecraft:comparator>], [<refinedstorage:quartz_enriched_iron>, <zcontent:chip2>, <refinedstorage:quartz_enriched_iron>]]);
recipes.addShaped(<refinedstorage:cutting_tool>, [[null, null, <refinedstorage:quartz_enriched_iron>], [null, <minecraft:stick>, null], [<minecraft:stick>, null, null]]);
recipes.addShaped(<refinedstorage:storage_housing> * 16, [[<ore:blockGlass>, <minecraft:redstone>, <ore:blockGlass>], [<minecraft:redstone>, null, <minecraft:redstone>], [<refinedstorage:quartz_enriched_iron>, <refinedstorage:quartz_enriched_iron>, <refinedstorage:quartz_enriched_iron>]]);
recipes.addShaped(<refinedstorage:pattern> * 16, [[<ore:blockGlass>, <minecraft:redstone>, <ore:blockGlass>], [<minecraft:redstone>, <ore:blockGlass>, <minecraft:redstone>], [<refinedstorage:quartz_enriched_iron>, <refinedstorage:quartz_enriched_iron>, <refinedstorage:quartz_enriched_iron>]]);
recipes.addShaped(<refinedstorage:filter>, [[<refinedstorage:quartz_enriched_iron>, <minecraft:paper>, <refinedstorage:quartz_enriched_iron>], [<minecraft:paper>, <minecraft:hopper>, <minecraft:paper>], [<refinedstorage:quartz_enriched_iron>, <minecraft:paper>, <refinedstorage:quartz_enriched_iron>]]);
recipes.addShaped(<refinedstorage:network_card>, [[<refinedstorage:quartz_enriched_iron>, <refinedstorage:quartz_enriched_iron>, <refinedstorage:quartz_enriched_iron>], [<minecraft:paper>, <zcontent:chip3>, <minecraft:paper>], [<refinedstorage:quartz_enriched_iron>, <refinedstorage:quartz_enriched_iron>, <refinedstorage:quartz_enriched_iron>]]);
recipes.addShaped(<refinedstorage:security_card>, [[<refinedstorage:quartz_enriched_iron>, <refinedstorage:quartz_enriched_iron>, <refinedstorage:quartz_enriched_iron>], [<refinedstorage:network_card>, <zcontent:chip3>, <refinedstorage:network_card>], [<refinedstorage:quartz_enriched_iron>, <refinedstorage:quartz_enriched_iron>, <refinedstorage:quartz_enriched_iron>]]);
recipes.addShaped(<refinedstorage:wrench>, [[<refinedstorage:quartz_enriched_iron>, <zcontent:chip1>, <refinedstorage:quartz_enriched_iron>], [<refinedstorage:quartz_enriched_iron>, <refinedstorage:quartz_enriched_iron>, <refinedstorage:quartz_enriched_iron>], [null, <refinedstorage:quartz_enriched_iron>, null]]);
