#priority 8000
import mods.avaritia.ExtremeCrafting;

print("---loading mods/avaritia.zs---");

# Remove
ExtremeCrafting.remove(<avaritia:neutron_collector>);
ExtremeCrafting.remove(<avaritia:neutronium_compressor>);
ExtremeCrafting.remove(<avaritia:skullfire_sword>);
ExtremeCrafting.remove(<avaritia:endest_pearl>);
ExtremeCrafting.remove(<avaritia:resource:5>);
ExtremeCrafting.remove(<avaritia:cosmic_meatballs>);
ExtremeCrafting.remove(<avaritia:ultimate_stew>);
ExtremeCrafting.remove(<eternalsingularity:eternal_singularity>);

# Add
mods.avaritia.ExtremeCrafting.addShaped("new_infinity_catalyst", <avaritia:resource:5>, [[<projecte:item.pe_matter>, <avaritia:endest_pearl>, <projecte:item.pe_matter>, <ore:dustMana>, <ore:dustMana>, <ore:dustMana>, <projecte:item.pe_matter>, <avaritia:endest_pearl>, <projecte:item.pe_matter>], [<avaritia:endest_pearl>, <quark:rune:16>, <avaritia:endest_pearl>, <eternalsingularity:combined_singularity>, <eternalsingularity:combined_singularity:1>, <eternalsingularity:combined_singularity:3>, <avaritia:endest_pearl>, <quark:rune:16>, <avaritia:endest_pearl>], [<projecte:item.pe_matter>, <avaritia:endest_pearl>, <projecte:item.pe_matter>, <ore:dustMana>, <ore:dustMana>, <ore:dustMana>, <projecte:item.pe_matter>, <avaritia:endest_pearl>, <projecte:item.pe_matter>], [<ore:dustMana>, <eternalsingularity:combined_singularity:10>, <ore:dustMana>, <enderio:block_infinity_fog>, <enderio:block_infinity_fog>, <enderio:block_infinity_fog>, <ore:dustMana>, <eternalsingularity:combined_singularity:4>, <ore:dustMana>], [<ore:dustMana>, <eternalsingularity:combined_singularity:13>, <ore:dustMana>, <enderio:block_infinity_fog>, <eternalsingularity:eternal_singularity>, <enderio:block_infinity_fog>, <ore:dustMana>, <eternalsingularity:combined_singularity:6>, <ore:dustMana>], [<ore:dustMana>, <eternalsingularity:combined_singularity:12>, <ore:dustMana>, <enderio:block_infinity_fog>, <enderio:block_infinity_fog>, <enderio:block_infinity_fog>, <ore:dustMana>, <eternalsingularity:combined_singularity:7>, <ore:dustMana>], [<projecte:item.pe_matter>, <avaritia:endest_pearl>, <projecte:item.pe_matter>, <ore:dustMana>, <ore:dustMana>, <ore:dustMana>, <projecte:item.pe_matter>, <avaritia:endest_pearl>, <projecte:item.pe_matter>], [<avaritia:endest_pearl>, <quark:rune:16>, <avaritia:endest_pearl>, <eternalsingularity:combined_singularity:11>, <eternalsingularity:combined_singularity:9>, <eternalsingularity:combined_singularity:8>, <avaritia:endest_pearl>, <quark:rune:16>, <avaritia:endest_pearl>], [<projecte:item.pe_matter>, <avaritia:endest_pearl>, <projecte:item.pe_matter>, <ore:dustMana>, <ore:dustMana>, <ore:dustMana>, <projecte:item.pe_matter>, <avaritia:endest_pearl>, <projecte:item.pe_matter>]]); 
mods.avaritia.ExtremeCrafting.addShaped("new_endest_pearl", <avaritia:endest_pearl>, [[null, null, <enderio:item_alloy_ingot:8>, <enderio:item_alloy_ingot:8>, <enderio:item_alloy_ingot:8>, <enderio:item_alloy_ingot:8>, <enderio:item_alloy_ingot:8>, null, null], [null, <enderio:item_alloy_ingot:8>, <enderio:item_alloy_ingot:8>, <minecraft:ender_pearl>, <minecraft:ender_pearl>, <minecraft:ender_pearl>, <enderio:item_alloy_ingot:8>, <enderio:item_alloy_ingot:8>, null], [<enderio:item_alloy_ingot:8>, <enderio:item_alloy_ingot:8>, <minecraft:ender_pearl>, <minecraft:ender_pearl>, <avaritia:resource:4>, <minecraft:ender_pearl>, <minecraft:ender_pearl>, <enderio:item_alloy_ingot:8>, <enderio:item_alloy_ingot:8>], [<enderio:item_alloy_ingot:8>, <minecraft:ender_pearl>, <minecraft:ender_pearl>, <extendedcrafting:material:48>, <extendedcrafting:material:48>, <extendedcrafting:material:48>, <minecraft:ender_pearl>, <minecraft:ender_pearl>, <enderio:item_alloy_ingot:8>], [<enderio:item_alloy_ingot:8>, <minecraft:ender_pearl>, <avaritia:resource:4>, <extendedcrafting:material:48>, <ore:netherStar>, <extendedcrafting:material:48>, <avaritia:resource:4>, <minecraft:ender_pearl>, <enderio:item_alloy_ingot:8>], [<enderio:item_alloy_ingot:8>, <minecraft:ender_pearl>, <minecraft:ender_pearl>, <extendedcrafting:material:48>, <extendedcrafting:material:48>, <extendedcrafting:material:48>, <minecraft:ender_pearl>, <minecraft:ender_pearl>, <enderio:item_alloy_ingot:8>], [<enderio:item_alloy_ingot:8>, <enderio:item_alloy_ingot:8>, <minecraft:ender_pearl>, <minecraft:ender_pearl>, <avaritia:resource:4>, <minecraft:ender_pearl>, <minecraft:ender_pearl>, <enderio:item_alloy_ingot:8>, <enderio:item_alloy_ingot:8>], [null, <enderio:item_alloy_ingot:8>, <enderio:item_alloy_ingot:8>, <minecraft:ender_pearl>, <minecraft:ender_pearl>, <minecraft:ender_pearl>, <enderio:item_alloy_ingot:8>, <enderio:item_alloy_ingot:8>, null], [null, null, <enderio:item_alloy_ingot:8>, <enderio:item_alloy_ingot:8>, <enderio:item_alloy_ingot:8>, <enderio:item_alloy_ingot:8>, <enderio:item_alloy_ingot:8>, null, null]]); 
mods.avaritia.ExtremeCrafting.addShaped("new_skullfire_sword", <avaritia:skullfire_sword>.withTag({Unbreakable:1}), [[null, null, null, null, null, null, <mysticalagriculture:fire_essence>, <extrautils2:simpledecorative:2>, <extrautils2:simpledecorative:2>], [null, null, null, null, null, <mysticalagriculture:fire_essence>, <extrautils2:simpledecorative:2>, <extrautils2:simpledecorative:2>, <extrautils2:simpledecorative:2>], [null, null, null, null, <mysticalagriculture:fire_essence>, <extrautils2:simpledecorative:2>, <extrautils2:simpledecorative:2>, <extrautils2:simpledecorative:2>, <mysticalagriculture:fire_essence>], [null, null, null, <mysticalagriculture:fire_essence>, <extrautils2:simpledecorative:2>, <extrautils2:simpledecorative:2>, <extrautils2:simpledecorative:2>, <mysticalagriculture:fire_essence>, null], [null, null, <minecraft:gold_block>, <extrautils2:simpledecorative:2>, <extrautils2:simpledecorative:2>, <extrautils2:simpledecorative:2>, <mysticalagriculture:fire_essence>, null, null], [null, <minecraft:gold_block>, <extrautils2:simpledecorative:2>, <extrautils2:simpledecorative:2>, <extrautils2:simpledecorative:2>, <mysticalagriculture:fire_essence>, null, null, null], [null, <minecraft:gold_block>, <biomesoplenty:gem_block:1>, <extrautils2:simpledecorative:2>, <minecraft:gold_block>, null, null, null, null], [null, <minecraft:log>, <minecraft:gold_block>, <minecraft:gold_block>, null, null, null, null, null], [<biomesoplenty:gem_block:1>, null, null, null, null, null, null, null, null]]); 
mods.avaritia.ExtremeCrafting.addShaped("new_collector", <avaritia:neutron_collector>, [[<ore:blockStellarAlloy>, <jaopca:item_platedenseiridium>, <jaopca:item_platedenseiridium>, <jaopca:item_platedenseiridium>, <ore:blockStellarAlloy>, <jaopca:item_platedenseiridium>, <jaopca:item_platedenseiridium>, <jaopca:item_platedenseiridium>, <ore:blockStellarAlloy>], [<jaopca:item_platedenseiridium>, <ore:fiberCarbon>, <ore:fiberCarbon>, <ore:fiberCarbon>, <thermalfoundation:material:328>, <ore:fiberCarbon>, <ore:fiberCarbon>, <ore:fiberCarbon>, <jaopca:item_platedenseiridium>], [<jaopca:item_platedenseiridium>, <ore:fiberCarbon>, <avaritia:resource:1>, <ore:fiberCarbon>, <thermalfoundation:material:328>, <ore:fiberCarbon>, <avaritia:resource:1>, <ore:fiberCarbon>, <jaopca:item_platedenseiridium>], [<jaopca:item_platedenseiridium>, <ore:fiberCarbon>, <ore:fiberCarbon>, <ore:fiberCarbon>, <thermalfoundation:material:328>, <ore:fiberCarbon>, <ore:fiberCarbon>, <ore:fiberCarbon>, <jaopca:item_platedenseiridium>], [<ore:blockStellarAlloy>, <thermalfoundation:material:328>, <thermalfoundation:material:328>, <thermalfoundation:material:328>, <techguns:itemshared:66>, <thermalfoundation:material:328>, <thermalfoundation:material:328>, <thermalfoundation:material:328>, <ore:blockStellarAlloy>], [<jaopca:item_platedenseiridium>, <ore:fiberCarbon>, <ore:fiberCarbon>, <ore:fiberCarbon>, <thermalfoundation:material:328>, <ore:fiberCarbon>, <ore:fiberCarbon>, <ore:fiberCarbon>, <jaopca:item_platedenseiridium>], [<jaopca:item_platedenseiridium>, <ore:fiberCarbon>, <avaritia:resource:1>, <ore:fiberCarbon>, <thermalfoundation:material:328>, <ore:fiberCarbon>, <avaritia:resource:1>, <ore:fiberCarbon>, <jaopca:item_platedenseiridium>], [<jaopca:item_platedenseiridium>, <ore:fiberCarbon>, <ore:fiberCarbon>, <ore:fiberCarbon>, <thermalfoundation:material:328>, <ore:fiberCarbon>, <ore:fiberCarbon>, <ore:fiberCarbon>, <jaopca:item_platedenseiridium>], [<ore:blockStellarAlloy>, <jaopca:item_platedenseiridium>, <jaopca:item_platedenseiridium>, <jaopca:item_platedenseiridium>, <ore:blockStellarAlloy>, <jaopca:item_platedenseiridium>, <jaopca:item_platedenseiridium>, <jaopca:item_platedenseiridium>, <ore:blockStellarAlloy>]]); 
mods.avaritia.ExtremeCrafting.addShaped("new_compressor", <avaritia:neutronium_compressor>, [[<ore:blockStellarAlloy>, <jaopca:item_platedenseiridium>, <jaopca:item_platedenseiridium>, <ore:blockStellarAlloy>, <ore:blockCrystalMatrix>, <ore:blockStellarAlloy>, <jaopca:item_platedenseiridium>, <jaopca:item_platedenseiridium>, <ore:blockStellarAlloy>], [<jaopca:item_platedenseiridium>, <techguns:itemshared:131>, <techguns:itemshared:131>, <avaritia:resource:4>, <ore:fiberCarbon>, <avaritia:resource:4>, <techguns:itemshared:131>, <techguns:itemshared:131>, <jaopca:item_platedenseiridium>], [<jaopca:item_platedenseiridium>, <techguns:itemshared:131>, <techguns:itemshared:131>, <avaritia:resource:4>, <ore:fiberCarbon>, <avaritia:resource:4>, <techguns:itemshared:131>, <techguns:itemshared:131>, <jaopca:item_platedenseiridium>], [<ore:blockStellarAlloy>, <avaritia:resource:4>, <avaritia:resource:4>, <enderio:block_infinity_fog>, <enderio:block_infinity_fog>, <enderio:block_infinity_fog>, <avaritia:resource:4>, <avaritia:resource:4>, <ore:blockStellarAlloy>], [<ore:blockCrystalMatrix>, <ore:fiberCarbon>, <ore:fiberCarbon>, <enderio:block_infinity_fog>, <projecte:item.pe_matter>, <enderio:block_infinity_fog>, <ore:fiberCarbon>, <ore:fiberCarbon>, <ore:blockCrystalMatrix>], [<ore:blockStellarAlloy>, <avaritia:resource:4>, <avaritia:resource:4>, <enderio:block_infinity_fog>, <enderio:block_infinity_fog>, <enderio:block_infinity_fog>, <avaritia:resource:4>, <avaritia:resource:4>, <ore:blockStellarAlloy>], [<jaopca:item_platedenseiridium>, <techguns:itemshared:131>, <techguns:itemshared:131>, <avaritia:resource:4>, <ore:fiberCarbon>, <avaritia:resource:4>, <techguns:itemshared:131>, <techguns:itemshared:131>, <jaopca:item_platedenseiridium>], [<jaopca:item_platedenseiridium>, <techguns:itemshared:131>, <techguns:itemshared:131>, <avaritia:resource:4>, <ore:fiberCarbon>, <avaritia:resource:4>, <techguns:itemshared:131>, <techguns:itemshared:131>, <jaopca:item_platedenseiridium>], [<ore:blockStellarAlloy>, <jaopca:item_platedenseiridium>, <jaopca:item_platedenseiridium>, <ore:blockStellarAlloy>, <ore:blockCrystalMatrix>, <ore:blockStellarAlloy>, <jaopca:item_platedenseiridium>, <jaopca:item_platedenseiridium>, <ore:blockStellarAlloy>]]);

print("---initialized mods/avaritia.zs---");