#priority 2000

print("---loading recipes/industrialforegoing.zs---");

# Remove
recipes.removeByRecipeName("industrialforegoing:infinity_drill_0");
recipes.removeByRecipeName("industrialforegoing:protein_reactor");
recipes.removeByRecipeName("industrialforegoing:enchantment_invoker");
recipes.removeByRecipeName("industrialforegoing:black_hole_tank");
recipes.removeByRecipeName("industrialforegoing:enchantment_refiner");
recipes.removeByRecipeName("industrialforegoing:mob_slaughter_factory");
recipes.removeByRecipeName("industrialforegoing:fluid_transfer_addon_pull_0");
recipes.removeByRecipeName("industrialforegoing:wither_builder");
recipes.removeByRecipeName("industrialforegoing:dye_mixer");
recipes.removeByRecipeName("industrialforegoing:laser_drill");
recipes.removeByRecipeName("industrialforegoing:animal_growth_increaser");
recipes.removeByRecipeName("industrialforegoing:plant_interactor");
recipes.removeByRecipeName("industrialforegoing:oredictionary_converter");
recipes.removeByRecipeName("industrialforegoing:mob_detector");
recipes.removeByRecipeName("industrialforegoing:range_addon_6");
recipes.removeByRecipeName("industrialforegoing:range_addon_7");
recipes.removeByRecipeName("industrialforegoing:range_addon_8");
recipes.removeByRecipeName("industrialforegoing:range_addon_9");
recipes.removeByRecipeName("industrialforegoing:range_addon_0");
recipes.removeByRecipeName("industrialforegoing:range_addon_1");
recipes.removeByRecipeName("industrialforegoing:range_addon_2");
recipes.removeByRecipeName("industrialforegoing:range_addon_3");
recipes.removeByRecipeName("industrialforegoing:range_addon_4");
recipes.removeByRecipeName("industrialforegoing:range_addon_5");
recipes.removeByRecipeName("industrialforegoing:hydrator");
recipes.removeByRecipeName("industrialforegoing:block_placer");
recipes.removeByRecipeName("industrialforegoing:sewage_composter_solidifier");
recipes.removeByRecipeName("industrialforegoing:black_hole_label");
recipes.removeByRecipeName("industrialforegoing:lava_fabricator");
recipes.removeByRecipeName("industrialforegoing:fortune_addon");
recipes.removeByRecipeName("industrialforegoing:animal_byproduct_recolector");
recipes.removeByRecipeName("industrialforegoing:material_stonework_factory");
recipes.removeByRecipeName("industrialforegoing:potion_enervator");
recipes.removeByRecipeName("industrialforegoing:crop_sower");
recipes.removeByRecipeName("industrialforegoing:laser_base");
recipes.removeByRecipeName("industrialforegoing:fluid_crafter");
recipes.removeByRecipeName("industrialforegoing:mob_imprisonment_tool");
recipes.removeByRecipeName("industrialforegoing:itemstack_transfer_addon_pull_0");
recipes.removeByRecipeName("industrialforegoing:animal_resource_harvester");
recipes.removeByRecipeName("industrialforegoing:petrified_fuel_generator");
recipes.removeByRecipeName("industrialforegoing:crop_enrich_material_injector");
recipes.removeByRecipeName("industrialforegoing:bioreactor");
recipes.removeByRecipeName("industrialforegoing:resourceful_furnace");
recipes.removeByRecipeName("industrialforegoing:mob_duplicator");
recipes.removeByRecipeName("industrialforegoing:sludge_refiner");
recipes.removeByRecipeName("industrialforegoing:enchantment_aplicator");
recipes.removeByRecipeName("industrialforegoing:fluiddictionary_converter");
recipes.removeByRecipeName("industrialforegoing:animal_stock_increaser");
recipes.removeByRecipeName("industrialforegoing:adult_filter");
recipes.removeByRecipeName("industrialforegoing:black_hole_unit");
recipes.removeByRecipeName("industrialforegoing:leaf_shearing");
recipes.removeByRecipeName("industrialforegoing:fluid_transfer_addon_push_0");
recipes.removeByRecipeName("industrialforegoing:water_resources_collector");
recipes.removeByRecipeName("industrialforegoing:water_condensator");
recipes.removeByRecipeName("industrialforegoing:biofuel_generator");
recipes.removeByRecipeName("industrialforegoing:straw");
recipes.removeByRecipeName("industrialforegoing:protein_generator");
recipes.removeByRecipeName("industrialforegoing:froster");
recipes.removeByRecipeName("industrialforegoing:ore_sieve");
recipes.removeByRecipeName("industrialforegoing:enchantment_extractor");
recipes.removeByRecipeName("industrialforegoing:mob_relocator");
recipes.removeByRecipeName("industrialforegoing:crop_recolector");
recipes.removeByRecipeName("industrialforegoing:spores_recreator");
recipes.removeByRecipeName("industrialforegoing:conveyor_0");
recipes.removeByRecipeName("industrialforegoing:meat_feeder");
recipes.removeByRecipeName("industrialforegoing:ore_washer");
recipes.removeByRecipeName("industrialforegoing:ore_processor");
recipes.removeByRecipeName("industrialforegoing:animal_independence_selector");
recipes.removeByRecipeName("industrialforegoing:villager_trade_exchanger");
recipes.removeByRecipeName("industrialforegoing:conveyor_upgrade_0");
recipes.removeByRecipeName("industrialforegoing:conveyor_upgrade_1");
recipes.removeByRecipeName("industrialforegoing:itemstack_transfer_addon_push_0");
recipes.removeByRecipeName("industrialforegoing:block_destroyer");
recipes.removeByRecipeName("industrialforegoing:fluid_pump");
recipes.removeByRecipeName("industrialforegoing:range_addon_11");
recipes.removeByRecipeName("industrialforegoing:range_addon_10");
recipes.removeByRecipeName("industrialforegoing:black_hole_controller_reworked");
recipes.removeByRecipeName("industrialforegoing:item_splitter");
recipes.removeByRecipeName("industrialforegoing:energy_field_provider");
recipes.removeByRecipeName("industrialforegoing:pitiful_fuel_generator");
recipes.removeByRecipeName("industrialforegoing:laser_lens_inverted_0");
recipes.removeByRecipeName("industrialforegoing:laser_lens_inverted_1");
recipes.removeByRecipeName("industrialforegoing:laser_lens_inverted_2");
recipes.removeByRecipeName("industrialforegoing:laser_lens_inverted_3");
recipes.removeByRecipeName("industrialforegoing:laser_lens_inverted_4");
recipes.removeByRecipeName("industrialforegoing:laser_lens_inverted_5");
recipes.removeByRecipeName("industrialforegoing:laser_lens_inverted_6");
recipes.removeByRecipeName("industrialforegoing:laser_lens_inverted_7");
recipes.removeByRecipeName("industrialforegoing:laser_lens_inverted_8");
recipes.removeByRecipeName("industrialforegoing:laser_lens_inverted_9");
recipes.removeByRecipeName("industrialforegoing:laser_lens_inverted_10");
recipes.removeByRecipeName("industrialforegoing:laser_lens_inverted_11");
recipes.removeByRecipeName("industrialforegoing:laser_lens_inverted_12");
recipes.removeByRecipeName("industrialforegoing:laser_lens_inverted_13");
recipes.removeByRecipeName("industrialforegoing:laser_lens_inverted_14");
recipes.removeByRecipeName("industrialforegoing:laser_lens_inverted_15");

# Add
recipes.addShapeless(<industrialforegoing:laser_lens>, [<industrialforegoing:laser_lens_inverted>]);
recipes.addShapeless(<industrialforegoing:laser_lens_inverted>, [<industrialforegoing:laser_lens>]);
recipes.addShaped(<industrialforegoing:pitiful_fuel_generator>, [[<quark:sturdy_stone>, <quark:sturdy_stone>, <quark:sturdy_stone>],[<quark:sturdy_stone>, <ore:gearGold>, <quark:sturdy_stone>], [<ore:ingotIron>, <ore:ingotConductiveIron>, <ore:ingotIron>]]);
recipes.addShaped(<industrialforegoing:energy_field_provider>, [[<ore:ingotGold>, <industrialforegoing:energy_field_addon>, <ore:ingotGold>], [<ore:ingotGold>, <teslacorelib:machine_case>, <ore:ingotGold>], [<minecraft:repeater>, <ore:gearPlatinum>, <minecraft:repeater>]]);
recipes.addShaped(<industrialforegoing:protein_reactor>, [[<ore:sheetPlastic>, <minecraft:porkchop>, <ore:sheetPlastic>], [<minecraft:egg>, <teslacorelib:machine_case>, <minecraft:egg>], [<minecraft:brick>, <minecraft:rabbit_foot>, <minecraft:brick>]]);
recipes.addShaped(<industrialforegoing:enchantment_invoker>, [[<ore:sheetPlastic>, <minecraft:book>, <ore:sheetPlastic>], [<ore:gemDiamond>, <teslacorelib:machine_case>, <ore:gemDiamond>], [<minecraft:obsidian>, <minecraft:obsidian>, <minecraft:obsidian>]]);
recipes.addShaped(<industrialforegoing:black_hole_tank>, [[<ore:sheetPlastic>, <ore:sheetPlastic>, <ore:sheetPlastic>], [<minecraft:ender_eye>, <minecraft:ender_pearl>, <minecraft:ender_eye>], [<minecraft:bucket>, <teslacorelib:machine_case>, <minecraft:bucket>]]);
recipes.addShaped(<industrialforegoing:enchantment_refiner>, [[<ore:sheetPlastic>, <minecraft:ender_pearl>, <ore:sheetPlastic>], [<minecraft:book>, <teslacorelib:machine_case>, <minecraft:enchanted_book>], [<ore:sheetPlastic>, <ore:gearPlatinum>, <ore:sheetPlastic>]]);
recipes.addShaped(<industrialforegoing:mob_slaughter_factory>, [[<ore:sheetPlastic>, <ore:gearElectrumFlux>, <ore:sheetPlastic>], [<minecraft:iron_sword>, <teslacorelib:machine_case>, <minecraft:iron_sword>], [<minecraft:iron_axe>, <minecraft:redstone>, <minecraft:iron_axe>]]);
recipes.addShaped(<industrialforegoing:fluid_transfer_addon_pull>, [[<ore:sheetPlastic>, <minecraft:bucket>, <ore:sheetPlastic>], [<ore:dyeLightBlue>, <minecraft:sticky_piston>, <ore:dyeLightBlue>], [<ore:sheetPlastic>, <minecraft:bucket>, <ore:sheetPlastic>]]);
recipes.addShaped(<industrialforegoing:wither_builder>, [[<ore:sheetPlastic>, <minecraft:nether_star>, <ore:sheetPlastic>], [<minecraft:skull:1>, <teslacorelib:machine_case>, <minecraft:skull:1>], [<minecraft:soul_sand>, <minecraft:soul_sand>, <minecraft:soul_sand>]]);
recipes.addShaped(<industrialforegoing:dye_mixer>, [[<ore:sheetPlastic>, <ore:dyeGreen>, <ore:sheetPlastic>], [<ore:dyeRed>, <teslacorelib:machine_case>, <ore:dyeBlue>], [<ore:sheetPlastic>, <ore:gearElectrumFlux>, <ore:sheetPlastic>]]);
recipes.addShaped(<industrialforegoing:laser_drill>, [[<ore:sheetPlastic>, <industrialforegoing:laser_lens>, <ore:sheetPlastic>], [<ore:blockGlassColorless>, <minecraft:glowstone>, <ore:blockGlassColorless>], [<ore:gearPlatinum>, <teslacorelib:machine_case>, <ore:gearPlatinum>]]);
recipes.addShaped(<industrialforegoing:animal_growth_increaser>, [[<ore:sheetPlastic>, <minecraft:wheat>, <ore:sheetPlastic>], [<minecraft:wheat>, <teslacorelib:machine_case>, <minecraft:wheat>], [<ore:dyePurple>, <ore:gearElectrumFlux>, <ore:dyePurple>]]);
recipes.addShaped(<industrialforegoing:plant_interactor>, [[<ore:sheetPlastic>, <minecraft:iron_hoe>, <ore:sheetPlastic>], [<minecraft:iron_hoe>, <teslacorelib:machine_case>, <minecraft:iron_hoe>], [<ore:gearElectrumFlux>, <minecraft:redstone>, <ore:gearElectrumFlux>]]);
recipes.addShaped(<industrialforegoing:oredictionary_converter>, [[<ore:sheetPlastic>, <ore:sheetPlastic>, <ore:sheetPlastic>], [<ore:sheetPlastic>, <teslacorelib:machine_case>, <ore:sheetPlastic>], [<ore:nuggetIron>, <ore:ingotIron>, <ore:blockIron>]]);
recipes.addShaped(<industrialforegoing:mob_detector>, [[<ore:sheetPlastic>, <ore:sheetPlastic>, <ore:sheetPlastic>], [<minecraft:repeater>, <minecraft:comparator>, <minecraft:repeater>], [<minecraft:observer>, <teslacorelib:machine_case>, <minecraft:observer>]]);
recipes.addShaped(<industrialforegoing:range_addon:6>, [[<ore:ingotSilver>, <ore:sheetPlastic>, <ore:ingotSilver>], [<ore:ingotSilver>, <ore:paneGlass>, <ore:ingotSilver>], [<ore:ingotSilver>, <ore:sheetPlastic>, <ore:ingotSilver>]]);
recipes.addShaped(<industrialforegoing:range_addon:7>, [[<ore:ingotGold>, <ore:sheetPlastic>, <ore:ingotGold>], [<ore:ingotGold>, <ore:paneGlass>, <ore:ingotGold>], [<ore:ingotGold>, <ore:sheetPlastic>, <ore:ingotGold>]]);
recipes.addShaped(<industrialforegoing:range_addon:8>, [[<minecraft:quartz>, <ore:sheetPlastic>, <minecraft:quartz>], [<minecraft:quartz>, <ore:paneGlass>, <minecraft:quartz>], [<minecraft:quartz>, <ore:sheetPlastic>, <minecraft:quartz>]]);
recipes.addShaped(<industrialforegoing:range_addon:9>, [[<minecraft:diamond>, <ore:sheetPlastic>, <minecraft:diamond>], [<minecraft:diamond>, <ore:paneGlass>, <minecraft:diamond>], [<minecraft:diamond>, <ore:sheetPlastic>, <minecraft:diamond>]]);
recipes.addShaped(<industrialforegoing:range_addon>, [[<minecraft:cobblestone>, <ore:sheetPlastic>, <minecraft:cobblestone>], [<minecraft:cobblestone>, <ore:paneGlass>, <minecraft:cobblestone>], [<minecraft:cobblestone>, <ore:sheetPlastic>, <minecraft:cobblestone>]]);
recipes.addShaped(<industrialforegoing:range_addon:1>, [[<minecraft:dye:4>, <ore:sheetPlastic>, <minecraft:dye:4>], [<minecraft:dye:4>, <ore:paneGlass>, <minecraft:dye:4>], [<minecraft:dye:4>, <ore:sheetPlastic>, <minecraft:dye:4>]]);
recipes.addShaped(<industrialforegoing:range_addon:2>, [[<ore:ingotIron>, <ore:sheetPlastic>, <ore:ingotIron>], [<ore:ingotIron>, <ore:paneGlass>, <ore:ingotIron>], [<ore:ingotIron>, <ore:sheetPlastic>, <ore:ingotIron>]]);
recipes.addShaped(<industrialforegoing:range_addon:3>, [[<ore:ingotTin>, <ore:sheetPlastic>, <ore:ingotTin>], [<ore:ingotTin>, <ore:paneGlass>, <ore:ingotTin>], [<ore:ingotTin>, <ore:sheetPlastic>, <ore:ingotTin>]]);
recipes.addShaped(<industrialforegoing:range_addon:4>, [[<ore:ingotCopper>, <ore:sheetPlastic>, <ore:ingotCopper>], [<ore:ingotCopper>, <ore:paneGlass>, <ore:ingotCopper>], [<ore:ingotCopper>, <ore:sheetPlastic>, <ore:ingotCopper>]]);
recipes.addShaped(<industrialforegoing:range_addon:5>, [[<ore:ingotBronze>, <ore:sheetPlastic>, <ore:ingotBronze>], [<ore:ingotBronze>, <ore:paneGlass>, <ore:ingotBronze>], [<ore:ingotBronze>, <ore:sheetPlastic>, <ore:ingotBronze>]]);
recipes.addShaped(<industrialforegoing:hydrator>, [[<ore:sheetPlastic>, <minecraft:water_bucket>, <ore:sheetPlastic>], [<industrialforegoing:fertilizer>, <teslacorelib:machine_case>, <industrialforegoing:fertilizer>], [<ore:gearConductiveIron>, <minecraft:piston>, <ore:gearConductiveIron>]]);
recipes.addShaped(<industrialforegoing:block_placer>, [[<ore:sheetPlastic>, <minecraft:dropper>, <ore:sheetPlastic>], [<minecraft:dropper>, <teslacorelib:machine_case>, <minecraft:dropper>], [<ore:sheetPlastic>, <minecraft:redstone>, <ore:sheetPlastic>]]);
recipes.addShaped(<industrialforegoing:sewage_composter_solidifier>, [[<ore:sheetPlastic>, <minecraft:furnace>, <ore:sheetPlastic>], [<minecraft:piston>, <teslacorelib:machine_case>, <minecraft:piston>], [<minecraft:brick>, <minecraft:redstone>, <minecraft:brick>]]);
recipes.addShaped(<industrialforegoing:black_hole_label> * 4, [[<ore:sheetPlastic>, <ore:sheetPlastic>, <ore:sheetPlastic>], [<minecraft:paper>, <minecraft:redstone>, <minecraft:paper>], [<ore:sheetPlastic>, <ore:sheetPlastic>, <ore:sheetPlastic>]]);
recipes.addShaped(<industrialforegoing:lava_fabricator>, [[<ore:sheetPlastic>, <minecraft:obsidian>, <ore:sheetPlastic>], [<minecraft:magma_cream>, <teslacorelib:machine_case>, <minecraft:magma_cream>], [<minecraft:blaze_rod>, <minecraft:redstone_block>, <minecraft:blaze_rod>]]);
recipes.addShaped(<industrialforegoing:fortune_addon>, [[<minecraft:emerald>, <ore:sheetPlastic>, <minecraft:emerald>], [<minecraft:emerald>, <industrialforegoing:pink_slime_ingot>, <minecraft:emerald>], [<minecraft:emerald>, <ore:sheetPlastic>, <minecraft:emerald>]]);
recipes.addShaped(<industrialforegoing:animal_byproduct_recolector>, [[<ore:sheetPlastic>, <minecraft:bucket>, <ore:sheetPlastic>], [<minecraft:brick>, <teslacorelib:machine_case>, <minecraft:brick>], [<minecraft:brick>, <minecraft:redstone>, <minecraft:brick>]]);
recipes.addShaped(<industrialforegoing:material_stonework_factory>, [[<ore:sheetPlastic>, <minecraft:crafting_table>, <ore:sheetPlastic>], [<minecraft:iron_pickaxe>, <teslacorelib:machine_case>, <minecraft:furnace>], [<minecraft:lava_bucket>, <industrialforegoing:pink_slime>, <minecraft:water_bucket>]]);
recipes.addShaped(<industrialforegoing:potion_enervator>, [[<ore:sheetPlastic>, <minecraft:brewing_stand>, <ore:sheetPlastic>], [<ore:gearElectrumFlux>, <teslacorelib:machine_case>, <ore:gearElectrumFlux>], [<minecraft:repeater>, <ore:gearElectrumFlux>, <minecraft:repeater>]]);
recipes.addShaped(<industrialforegoing:crop_sower>, [[<ore:sheetPlastic>, <minecraft:flower_pot>, <ore:sheetPlastic>], [<minecraft:piston>, <teslacorelib:machine_case>, <minecraft:piston>], [<ore:gearConductiveIron>, <minecraft:redstone>, <ore:gearConductiveIron>]]);
recipes.addShaped(<industrialforegoing:laser_base>, [[<ore:sheetPlastic>, <minecraft:glowstone>, <ore:sheetPlastic>], [<ore:gearElectrumFlux>, <minecraft:glowstone>, <ore:gearElectrumFlux>], [<ore:gearPlatinum>, <teslacorelib:machine_case>, <ore:gearPlatinum>]]);
recipes.addShaped(<industrialforegoing:fluid_crafter>, [[<ore:sheetPlastic>, <minecraft:crafting_table>, <ore:sheetPlastic>], [<minecraft:bucket>, <teslacorelib:machine_case>, <minecraft:bucket>], [<ore:sheetPlastic>, <ore:gearElectrumFlux>, <ore:sheetPlastic>]]);
recipes.addShaped(<industrialforegoing:mob_imprisonment_tool>, [[null, <ore:sheetPlastic>, null], [<ore:sheetPlastic>, <minecraft:ghast_tear>, <ore:sheetPlastic>], [null, <ore:sheetPlastic>, null]]);
recipes.addShaped(<industrialforegoing:itemstack_transfer_addon_pull>, [[<ore:sheetPlastic>, <ore:chestWood>, <ore:sheetPlastic>], [<ore:dyeMagenta>, <minecraft:sticky_piston>, <ore:dyeMagenta>], [<ore:sheetPlastic>, <ore:chestWood>, <ore:sheetPlastic>]]);
recipes.addShaped(<industrialforegoing:animal_resource_harvester>, [[<ore:sheetPlastic>, <ore:sheetPlastic>, <ore:sheetPlastic>], [<minecraft:shears>, <minecraft:bucket>, <minecraft:shears>], [<ore:gearElectrumFlux>, <teslacorelib:machine_case>, <ore:gearElectrumFlux>]]);
recipes.addShaped(<industrialforegoing:petrified_fuel_generator>, [[<ore:sheetPlastic>, <ore:gemDiamond>, <ore:sheetPlastic>], [<ore:gearElectrumFlux>, <teslacorelib:machine_case>, <ore:gearElectrumFlux>], [<ore:sheetPlastic>, <minecraft:furnace>, <ore:sheetPlastic>]]);
recipes.addShaped(<industrialforegoing:crop_enrich_material_injector>, [[<ore:sheetPlastic>, <minecraft:glass_bottle>, <ore:sheetPlastic>], [<minecraft:leather>, <teslacorelib:machine_case>, <minecraft:leather>], [<ore:gearConductiveIron>, <minecraft:redstone>, <ore:gearConductiveIron>]]);
recipes.addShaped(<industrialforegoing:bioreactor>, [[<ore:sheetPlastic>, <minecraft:fermented_spider_eye>, <ore:sheetPlastic>], [<minecraft:slime_ball>, <teslacorelib:machine_case>, <minecraft:slime_ball>], [<minecraft:brick>, <minecraft:sugar>, <minecraft:brick>]]);
recipes.addShaped(<industrialforegoing:resourceful_furnace>, [[<ore:sheetPlastic>, <minecraft:bucket>, <ore:sheetPlastic>], [<minecraft:furnace>, <teslacorelib:machine_case>, <minecraft:furnace>], [<ore:sheetPlastic>, <ore:gearElectrumFlux>, <ore:sheetPlastic>]]);
recipes.addShaped(<industrialforegoing:mob_duplicator>, [[<ore:sheetPlastic>, <minecraft:nether_wart>, <ore:sheetPlastic>], [<minecraft:magma_cream>, <teslacorelib:machine_case>, <minecraft:magma_cream>], [<ore:gemEmerald>, <minecraft:redstone>, <ore:gemEmerald>]]);
recipes.addShaped(<industrialforegoing:sludge_refiner>, [[<ore:sheetPlastic>, <minecraft:bucket>, <ore:sheetPlastic>], [<minecraft:furnace>, <teslacorelib:machine_case>, <minecraft:furnace>], [<ore:gearConductiveIron>, <ore:gearElectrumFlux>, <ore:gearConductiveIron>]]);
recipes.addShaped(<industrialforegoing:enchantment_aplicator>, [[<ore:sheetPlastic>, <ore:sheetPlastic>, <ore:sheetPlastic>], [<minecraft:anvil>, <teslacorelib:machine_case>, <minecraft:anvil>], [<ore:gearConductiveIron>, <minecraft:anvil>, <ore:gearConductiveIron>]]);
recipes.addShaped(<industrialforegoing:fluiddictionary_converter>, [[<ore:sheetPlastic>, <ore:sheetPlastic>, <ore:sheetPlastic>], [<ore:blockGlass>, <teslacorelib:machine_case>, <ore:blockGlass>], [<minecraft:bucket>, <ore:gearConductiveIron>, <minecraft:bucket>]]);
recipes.addShaped(<industrialforegoing:animal_stock_increaser>, [[<ore:sheetPlastic>, <minecraft:golden_apple>, <ore:sheetPlastic>], [<minecraft:golden_carrot>, <teslacorelib:machine_case>, <minecraft:golden_carrot>], [<ore:dyePurple>, <ore:gearConductiveIron>, <ore:dyePurple>]]);
recipes.addShaped(<industrialforegoing:adult_filter>, [[<ore:nuggetGold>, <ore:sheetPlastic>, <ore:nuggetGold>], [<ore:nuggetGold>, <ore:egg>, <ore:nuggetGold>], [<ore:nuggetGold>, <ore:sheetPlastic>, <ore:nuggetGold>]]);
recipes.addShaped(<industrialforegoing:black_hole_unit>, [[<ore:sheetPlastic>, <ore:sheetPlastic>, <ore:sheetPlastic>], [<minecraft:ender_eye>, <minecraft:ender_pearl>, <minecraft:ender_eye>], [<ore:chestWood>, <teslacorelib:machine_case>, <ore:chestWood>]]);
recipes.addShaped(<industrialforegoing:leaf_shearing>, [[<ore:nuggetGold>, <ore:sheetPlastic>, <ore:nuggetGold>], [<ore:nuggetGold>, <minecraft:shears>, <ore:nuggetGold>], [<ore:nuggetGold>, <ore:sheetPlastic>, <ore:nuggetGold>]]);
recipes.addShaped(<industrialforegoing:fluid_transfer_addon_push>, [[<ore:sheetPlastic>, <minecraft:bucket>, <ore:sheetPlastic>], [<ore:dyeLightBlue>, <minecraft:piston>, <ore:dyeLightBlue>], [<ore:sheetPlastic>, <minecraft:bucket>, <ore:sheetPlastic>]]);
recipes.addShaped(<industrialforegoing:water_resources_collector>, [[<ore:sheetPlastic>, <minecraft:fishing_rod>, <ore:sheetPlastic>], [<minecraft:bucket>, <teslacorelib:machine_case>, <minecraft:bucket>], [<ore:gearConductiveIron>, <minecraft:redstone>, <ore:gearConductiveIron>]]);
recipes.addShaped(<industrialforegoing:water_condensator>, [[<ore:sheetPlastic>, <minecraft:water_bucket>, <ore:sheetPlastic>], [<minecraft:piston>, <teslacorelib:machine_case>, <minecraft:piston>], [<ore:gearConductiveIron>, <minecraft:redstone>, <ore:gearConductiveIron>]]);
recipes.addShaped(<industrialforegoing:biofuel_generator>, [[<ore:sheetPlastic>, <minecraft:furnace>, <ore:sheetPlastic>], [<minecraft:piston>, <teslacorelib:machine_case>, <minecraft:piston>], [<minecraft:blaze_rod>, <minecraft:piston>, <minecraft:blaze_rod>]]);
recipes.addShaped(<industrialforegoing:straw>, [[<ore:sheetPlastic>, <ore:sheetPlastic>], [<ore:sheetPlastic>, null], [<ore:sheetPlastic>, null]]);
recipes.addShaped(<industrialforegoing:protein_generator>, [[<ore:sheetPlastic>, <minecraft:furnace>, <ore:sheetPlastic>], [<minecraft:piston>, <industrialforegoing:biofuel_generator>, <minecraft:piston>], [<minecraft:spider_eye>, <minecraft:piston>, <minecraft:spider_eye>]]);
recipes.addShaped(<industrialforegoing:froster>, [[<ore:sheetPlastic>, <minecraft:ice>, <ore:sheetPlastic>], [<minecraft:snowball>, <teslacorelib:machine_case>, <minecraft:snowball>], [<ore:sheetPlastic>, <ore:gearElectrumFlux>, <ore:sheetPlastic>]]);
recipes.addShaped(<industrialforegoing:ore_sieve>, [[<ore:sheetPlastic>, <industrialforegoing:pink_slime>, <ore:sheetPlastic>], [<minecraft:iron_bars>, <minecraft:iron_bars>, <minecraft:iron_bars>], [<ore:gearElectrumFlux>, <teslacorelib:machine_case>, <ore:gearElectrumFlux>]]);
recipes.addShaped(<industrialforegoing:enchantment_extractor>, [[<ore:sheetPlastic>, <minecraft:nether_brick>, <ore:sheetPlastic>], [<minecraft:book>, <teslacorelib:machine_case>, <minecraft:book>], [<ore:gemDiamond>, <ore:gearElectrumFlux>, <ore:gemDiamond>]]);
recipes.addShaped(<industrialforegoing:mob_relocator>, [[<ore:sheetPlastic>, <minecraft:iron_sword>, <ore:sheetPlastic>], [<minecraft:book>, <teslacorelib:machine_case>, <minecraft:book>], [<ore:gearElectrumFlux>, <minecraft:redstone>, <ore:gearElectrumFlux>]]);
recipes.addShaped(<industrialforegoing:crop_recolector>, [[<ore:sheetPlastic>, <minecraft:iron_hoe>, <ore:sheetPlastic>], [<minecraft:iron_axe>, <teslacorelib:machine_case>, <minecraft:iron_axe>], [<ore:gearElectrumFlux>, <minecraft:redstone>, <ore:gearElectrumFlux>]]);
recipes.addShaped(<industrialforegoing:spores_recreator>, [[<ore:sheetPlastic>, <ore:sheetPlastic>, <ore:sheetPlastic>], [<minecraft:red_mushroom>, <teslacorelib:machine_case>, <minecraft:red_mushroom>], [<ore:sheetPlastic>, <ore:gearConductiveIron>, <ore:sheetPlastic>]]);
recipes.addShaped(<industrialforegoing:conveyor> * 4, [[<ore:sheetPlastic>, <ore:sheetPlastic>, <ore:sheetPlastic>], [<ore:ingotIron>, <minecraft:redstone>, <ore:ingotIron>], [<ore:sheetPlastic>, <ore:sheetPlastic>, <ore:sheetPlastic>]]);
recipes.addShaped(<industrialforegoing:meat_feeder>, [[<ore:sheetPlastic>, <ore:ingotIron>, <ore:sheetPlastic>], [<minecraft:glass_bottle>, <ore:ingotIron>, <minecraft:glass_bottle>], [null, <ore:ingotIron>, null]]);
recipes.addShaped(<industrialforegoing:ore_washer>, [[<industrialforegoing:pink_slime_ingot>, <industrialforegoing:meat_feeder>, <industrialforegoing:pink_slime_ingot>], [<ore:sheetPlastic>, <teslacorelib:machine_case>, <ore:sheetPlastic>], [<industrialforegoing:conveyor:*>, <ore:gearPlatinum>, <industrialforegoing:conveyor:*>]]);
recipes.addShaped(<industrialforegoing:ore_processor>, [[<ore:sheetPlastic>, <minecraft:piston>, <ore:sheetPlastic>], [<minecraft:iron_pickaxe>, <teslacorelib:machine_case>, <minecraft:iron_pickaxe>], [<minecraft:book>, <minecraft:redstone>, <minecraft:book>]]);
recipes.addShaped(<industrialforegoing:animal_independence_selector>, [[<ore:sheetPlastic>, <ore:gemEmerald>, <ore:sheetPlastic>], [<ore:gemEmerald>, <teslacorelib:machine_case>, <ore:gemEmerald>], [<ore:dyePurple>, <ore:gearElectrumFlux>, <ore:dyePurple>]]);
recipes.addShaped(<industrialforegoing:villager_trade_exchanger>, [[<ore:sheetPlastic>, <minecraft:gold_ingot>, <ore:sheetPlastic>], [<minecraft:emerald>, <teslacorelib:machine_case>, <minecraft:emerald>], [<ore:sheetPlastic>, <ore:gearElectrumFlux>, <ore:sheetPlastic>]]);
recipes.addShaped(<industrialforegoing:conveyor_upgrade>, [[<ore:ingotIron>, <ore:sheetPlastic>, <ore:ingotIron>], [<ore:ingotIron>, <minecraft:dispenser>, <ore:ingotIron>], [<ore:ingotIron>, <industrialforegoing:conveyor:*>, <ore:ingotIron>]]);
recipes.addShaped(<industrialforegoing:conveyor_upgrade:1>, [[<ore:ingotIron>, <ore:sheetPlastic>, <ore:ingotIron>], [<ore:ingotIron>, <minecraft:hopper>, <ore:ingotIron>], [<ore:ingotIron>, <industrialforegoing:conveyor:*>, <ore:ingotIron>]]);
recipes.addShaped(<industrialforegoing:itemstack_transfer_addon_push>, [[<ore:sheetPlastic>, <ore:chestWood>, <ore:sheetPlastic>], [<ore:dyeMagenta>, <minecraft:piston>, <ore:dyeMagenta>], [<ore:sheetPlastic>, <ore:chestWood>, <ore:sheetPlastic>]]);
recipes.addShaped(<industrialforegoing:block_destroyer>, [[<ore:sheetPlastic>, <ore:gearElectrumFlux>, <ore:sheetPlastic>], [<minecraft:iron_pickaxe>, <teslacorelib:machine_case>, <minecraft:iron_shovel>], [<ore:gearConductiveIron>, <minecraft:redstone>, <ore:gearConductiveIron>]]);
recipes.addShaped(<industrialforegoing:fluid_pump>, [[<ore:sheetPlastic>, <minecraft:bucket>, <ore:sheetPlastic>], [<minecraft:lava_bucket>, <teslacorelib:machine_case>, <minecraft:water_bucket>], [<ore:sheetPlastic>, <ore:gearElectrumFlux>, <ore:sheetPlastic>]]);
recipes.addShaped(<industrialforegoing:range_addon:11>, [[<minecraft:emerald>, <ore:sheetPlastic>, <minecraft:emerald>], [<minecraft:emerald>, <ore:paneGlass>, <minecraft:emerald>], [<minecraft:emerald>, <ore:sheetPlastic>, <minecraft:emerald>]]);
recipes.addShaped(<industrialforegoing:range_addon:10>, [[<ore:ingotPlatinum>, <ore:sheetPlastic>, <ore:ingotPlatinum>], [<ore:ingotPlatinum>, <ore:paneGlass>, <ore:ingotPlatinum>], [<ore:ingotPlatinum>, <ore:sheetPlastic>, <ore:ingotPlatinum>]]);
recipes.addShaped(<industrialforegoing:black_hole_controller_reworked>, [[<ore:sheetPlastic>, <minecraft:diamond_block>, <ore:sheetPlastic>], [<industrialforegoing:pink_slime_ingot>, <minecraft:ender_chest>, <industrialforegoing:pink_slime_ingot>], [<ore:sheetPlastic>, <teslacorelib:machine_case>, <ore:sheetPlastic>]]);
recipes.addShaped(<industrialforegoing:item_splitter>, [[<ore:sheetPlastic>, <ore:chestWood>, <ore:sheetPlastic>], [<minecraft:hopper>, <teslacorelib:machine_case>, <minecraft:hopper>], [<ore:sheetPlastic>, <ore:gearConductiveIron>, <ore:sheetPlastic>]]);


print("---initialized recipes/industrialforegoing.zs---");