#priority 2033

print("---loading recipes/projecte.zs---");

# Remove
recipes.removeByRecipeName("projecte:philstone_smelt_minecraft_porkchop_32767");
recipes.removeByRecipeName("projecte:philstone_smelt_minecraft_fish_0");
recipes.removeByRecipeName("projecte:philstone_smelt_minecraft_fish_1");
recipes.removeByRecipeName("projecte:philstone_smelt_biomesoplenty_log_4_5");
recipes.removeByRecipeName("projecte:philstone_smelt_biomesoplenty_mud_0");
recipes.removeByRecipeName("projecte:philstone_smelt_minecraft_golden_chestplate_32767");
recipes.removeByRecipeName("projecte:philstone_smelt_minecraft_iron_ore_32767");
recipes.removeByRecipeName("projecte:philstone_smelt_minecraft_stained_hardened_clay_15");
recipes.removeByRecipeName("projecte:philstone_smelt_minecraft_stained_hardened_clay_11");
recipes.removeByRecipeName("projecte:philstone_smelt_minecraft_stained_hardened_clay_12");
recipes.removeByRecipeName("projecte:philstone_smelt_minecraft_stained_hardened_clay_13");
recipes.removeByRecipeName("projecte:philstone_smelt_minecraft_stained_hardened_clay_14");
recipes.removeByRecipeName("projecte:philstone_smelt_minecraft_stained_hardened_clay_10");
recipes.removeByRecipeName("projecte:philstone_smelt_biomesoplenty_log_3_7");
recipes.removeByRecipeName("projecte:philstone_smelt_biomesoplenty_log_3_5");
recipes.removeByRecipeName("projecte:philstone_smelt_biomesoplenty_log_3_6");
recipes.removeByRecipeName("projecte:philstone_smelt_biomesoplenty_log_3_4");
recipes.removeByRecipeName("projecte:philstone_smelt_biomesoplenty_white_sand_0");
recipes.removeByRecipeName("projecte:philstone_smelt_minecraft_emerald_ore_32767");
recipes.removeByRecipeName("projecte:philstone_smelt_minecraft_chicken_32767");
recipes.removeByRecipeName("projecte:philstone_smelt_biomesoplenty_log_2_6");
recipes.removeByRecipeName("projecte:philstone_smelt_biomesoplenty_log_2_7");
recipes.removeByRecipeName("projecte:philstone_smelt_biomesoplenty_log_2_4");
recipes.removeByRecipeName("projecte:philstone_smelt_biomesoplenty_log_2_5");
recipes.removeByRecipeName("projecte:philstone_smelt_minecraft_potato_32767");
recipes.removeByRecipeName("projecte:philstone_smelt_minecraft_iron_boots_32767");
recipes.removeByRecipeName("projecte:philstone_smelt_minecraft_golden_horse_armor_32767");
recipes.removeByRecipeName("projecte:philstone_smelt_minecraft_cobblestone_32767");
recipes.removeByRecipeName("projecte:philstone_smelt_biomesoplenty_log_1_7");
recipes.removeByRecipeName("projecte:philstone_smelt_biomesoplenty_log_1_5");
recipes.removeByRecipeName("projecte:philstone_smelt_biomesoplenty_log_1_6");
recipes.removeByRecipeName("projecte:philstone_smelt_biomesoplenty_log_1_4");
recipes.removeByRecipeName("projecte:philstone_smelt_minecraft_quartz_ore_32767");
recipes.removeByRecipeName("projecte:philstone_smelt_biomesoplenty_mudball_32767");
recipes.removeByRecipeName("projecte:philstone_smelt_biomesoplenty_gem_ore_7");
recipes.removeByRecipeName("projecte:philstone_smelt_biomesoplenty_gem_ore_4");
recipes.removeByRecipeName("projecte:philstone_smelt_biomesoplenty_gem_ore_3");
recipes.removeByRecipeName("projecte:philstone_smelt_biomesoplenty_gem_ore_6");
recipes.removeByRecipeName("projecte:philstone_smelt_biomesoplenty_gem_ore_5");
recipes.removeByRecipeName("projecte:philstone_smelt_biomesoplenty_gem_ore_0");
recipes.removeByRecipeName("projecte:philstone_smelt_biomesoplenty_gem_ore_2");
recipes.removeByRecipeName("projecte:philstone_smelt_biomesoplenty_gem_ore_1");
recipes.removeByRecipeName("projecte:philstone_smelt_minecraft_coal_ore_32767");
recipes.removeByRecipeName("projecte:philstone_smelt_minecraft_golden_shovel_32767");
recipes.removeByRecipeName("projecte:philstone_smelt_minecraft_netherrack_32767");
recipes.removeByRecipeName("projecte:philstone_smelt_furnus_dust_0");
recipes.removeByRecipeName("projecte:philstone_smelt_furnus_dust_1");
recipes.removeByRecipeName("projecte:philstone_smelt_minecraft_beef_32767");
recipes.removeByRecipeName("projecte:philstone_smelt_minecraft_iron_hoe_32767");
recipes.removeByRecipeName("projecte:philstone_smelt_minecraft_iron_pickaxe_32767");
recipes.removeByRecipeName("projecte:philstone_smelt_minecraft_iron_leggings_32767");
recipes.removeByRecipeName("projecte:philstone_smelt_minecraft_clay_32767");
recipes.removeByRecipeName("projecte:philstone_smelt_minecraft_log2_32767");
recipes.removeByRecipeName("projecte:philstone_smelt_minecraft_iron_chestplate_32767");
recipes.removeByRecipeName("projecte:philstone_smelt_minecraft_diamond_ore_32767");
recipes.removeByRecipeName("projecte:philstone_smelt_minecraft_stained_hardened_clay_1");
recipes.removeByRecipeName("projecte:philstone_smelt_minecraft_stained_hardened_clay_0");
recipes.removeByRecipeName("projecte:philstone_smelt_minecraft_stained_hardened_clay_3");
recipes.removeByRecipeName("projecte:philstone_smelt_minecraft_stained_hardened_clay_2");
recipes.removeByRecipeName("projecte:philstone_smelt_minecraft_stained_hardened_clay_5");
recipes.removeByRecipeName("projecte:philstone_smelt_minecraft_stained_hardened_clay_4");
recipes.removeByRecipeName("projecte:philstone_smelt_minecraft_stained_hardened_clay_7");
recipes.removeByRecipeName("projecte:philstone_smelt_minecraft_stained_hardened_clay_6");
recipes.removeByRecipeName("projecte:philstone_smelt_minecraft_stained_hardened_clay_9");
recipes.removeByRecipeName("projecte:philstone_smelt_minecraft_stained_hardened_clay_8");
recipes.removeByRecipeName("projecte:philstone_smelt_minecraft_log_32767");
recipes.removeByRecipeName("projecte:philstone_smelt_minecraft_golden_hoe_32767");
recipes.removeByRecipeName("projecte:philstone_smelt_minecraft_golden_helmet_32767");
recipes.removeByRecipeName("projecte:philstone_smelt_minecraft_chainmail_leggings_32767");
recipes.removeByRecipeName("projecte:philstone_smelt_minecraft_cactus_32767");
recipes.removeByRecipeName("projecte:philstone_smelt_minecraft_sponge_1");
recipes.removeByRecipeName("projecte:philstone_smelt_minecraft_lapis_ore_32767");
recipes.removeByRecipeName("projecte:philstone_smelt_biomesoplenty_plant_1_6");
recipes.removeByRecipeName("projecte:philstone_smelt_minecraft_iron_helmet_32767");
recipes.removeByRecipeName("projecte:philstone_smelt_minecraft_gold_ore_32767");
recipes.removeByRecipeName("projecte:philstone_smelt_minecraft_stonebrick_0");
recipes.removeByRecipeName("projecte:philstone_smelt_industrialforegoing_dryrubber_32767");
recipes.removeByRecipeName("projecte:philstone_smelt_minecraft_redstone_ore_32767");
recipes.removeByRecipeName("projecte:philstone_smelt_minecraft_clay_ball_32767");
recipes.removeByRecipeName("projecte:philstone_smelt_minecraft_chainmail_helmet_32767");
recipes.removeByRecipeName("projecte:philstone_smelt_minecraft_golden_sword_32767");
recipes.removeByRecipeName("projecte:philstone_smelt_minecraft_sand_32767");
recipes.removeByRecipeName("projecte:philstone_smelt_extrautils2_ironwood_log_32767");
recipes.removeByRecipeName("projecte:philstone_smelt_minecraft_mutton_32767");
recipes.removeByRecipeName("projecte:philstone_smelt_minecraft_iron_sword_32767");
recipes.removeByRecipeName("projecte:philstone_smelt_minecraft_rabbit_32767");
recipes.removeByRecipeName("projecte:philstone_smelt_biomesoplenty_log_0_6");
recipes.removeByRecipeName("projecte:philstone_smelt_biomesoplenty_log_0_7");
recipes.removeByRecipeName("projecte:philstone_smelt_biomesoplenty_log_0_4");
recipes.removeByRecipeName("projecte:philstone_smelt_biomesoplenty_log_0_5");
recipes.removeByRecipeName("projecte:philstone_smelt_minecraft_iron_shovel_32767");
recipes.removeByRecipeName("projecte:philstone_smelt_minecraft_iron_axe_32767");
recipes.removeByRecipeName("projecte:philstone_smelt_minecraft_iron_horse_armor_32767");
recipes.removeByRecipeName("projecte:philstone_smelt_minecraft_golden_pickaxe_32767");
recipes.removeByRecipeName("projecte:philstone_smelt_minecraft_chorus_fruit_32767");
recipes.removeByRecipeName("projecte:philstone_smelt_minecraft_golden_leggings_32767");
recipes.removeByRecipeName("projecte:philstone_smelt_minecraft_golden_axe_32767");
recipes.removeByRecipeName("projecte:philstone_smelt_minecraft_chainmail_boots_32767");
recipes.removeByRecipeName("projecte:philstone_smelt_minecraft_chainmail_chestplate_32767");
recipes.removeByRecipeName("projecte:philstone_smelt_extrautils2_decorativesolid_4");
recipes.removeByRecipeName("projecte:philstone_smelt_minecraft_golden_boots_32767");
recipes.removeByRecipeName("projecte:philstone_smelt_quark_biome_cobblestone_2");
recipes.removeByRecipeName("projecte:philstone_smelt_extrautils2_ironwood_planks_32767");
recipes.removeByRecipeName("projecte:alchemical_chest");
recipes.removeByRecipeName("projecte:collector_mk1");
recipes.removeByRecipeName("projecte:collector_mk2");
recipes.removeByRecipeName("projecte:collector_mk3");
recipes.removeByRecipeName("projecte:condenser_mk1");
recipes.removeByRecipeName("projecte:condenser_mk2");
recipes.removeByRecipeName("projecte:dm_furnace");
recipes.removeByRecipeName("projecte:dm_pedestal");
recipes.removeByRecipeName("projecte:interdiction_torch");
recipes.removeByRecipeName("projecte:item.pe_archangel_smite_0");
recipes.removeByRecipeName("projecte:item.pe_black_hole_0");
recipes.removeByRecipeName("projecte:item.pe_body_stone_0");
recipes.removeByRecipeName("projecte:item.pe_covalence_dust_0");
recipes.removeByRecipeName("projecte:item.pe_covalence_dust_1");
recipes.removeByRecipeName("projecte:item.pe_covalence_dust_2");
recipes.removeByRecipeName("projecte:item.pe_dm_axe");
recipes.removeByRecipeName("projecte:item.pe_dm_hammer");
recipes.removeByRecipeName("projecte:item.pe_dm_hoe");
recipes.removeByRecipeName("projecte:item.pe_dm_pick");
recipes.removeByRecipeName("projecte:item.pe_dm_shears");
recipes.removeByRecipeName("projecte:item.pe_dm_shovel");
recipes.removeByRecipeName("projecte:item.pe_dm_sword");
recipes.removeByRecipeName("projecte:item.pe_evertide_amulet");
recipes.removeByRecipeName("projecte:item.pe_gem_armor_0");
recipes.removeByRecipeName("projecte:item.pe_gem_armor_1");
recipes.removeByRecipeName("projecte:item.pe_gem_armor_2");
recipes.removeByRecipeName("projecte:item.pe_gem_armor_3");
recipes.removeByRecipeName("projecte:item.pe_gem_density");
recipes.removeByRecipeName("projecte:item.pe_harvest_god_0");
recipes.removeByRecipeName("projecte:item.pe_ignition_0");
recipes.removeByRecipeName("projecte:item.pe_klein_star_0");
recipes.removeByRecipeName("projecte:item.pe_life_stone_0");
recipes.removeByRecipeName("projecte:item.pe_matter_0");
recipes.removeByRecipeName("projecte:item.pe_matter_1");
recipes.removeByRecipeName("projecte:item.pe_matter_1_alt");
recipes.removeByRecipeName("projecte:item.pe_mind_stone_0");
recipes.removeByRecipeName("projecte:item.pe_ring_iron_band_alt");
recipes.removeByRecipeName("projecte:item.pe_rm_axe");
recipes.removeByRecipeName("projecte:item.pe_rm_hammer");
recipes.removeByRecipeName("projecte:item.pe_rm_hoe");
recipes.removeByRecipeName("projecte:item.pe_rm_katar");
recipes.removeByRecipeName("projecte:item.pe_rm_morning_star");
recipes.removeByRecipeName("projecte:item.pe_rm_pick");
recipes.removeByRecipeName("projecte:item.pe_rm_shears");
recipes.removeByRecipeName("projecte:item.pe_rm_shovel");
recipes.removeByRecipeName("projecte:item.pe_rm_sword");
recipes.removeByRecipeName("projecte:item.pe_soul_stone_0");
recipes.removeByRecipeName("projecte:item.pe_swrg");
recipes.removeByRecipeName("projecte:item.pe_time_watch");
recipes.removeByRecipeName("projecte:item.pe_tome");
recipes.removeByRecipeName("projecte:item.pe_transmutation_tablet");
recipes.removeByRecipeName("projecte:item.pe_volcanite_amulet");
recipes.removeByRecipeName("projecte:item.pe_zero_ring");
recipes.removeByRecipeName("projecte:matter_block_0");
recipes.removeByRecipeName("projecte:matter_block_1");
recipes.removeByRecipeName("projecte:philosophers_stone");
recipes.removeByRecipeName("projecte:philosophers_stone_alt");
recipes.removeByRecipeName("projecte:relay_mk1");
recipes.removeByRecipeName("projecte:relay_mk2");
recipes.removeByRecipeName("projecte:relay_mk3");
recipes.removeByRecipeName("projecte:rm_furnace");
recipes.removeByRecipeName("projecte:transmutation_table");
recipes.removeByRecipeName("projecte:conversions/rm_block_deconstruct");
recipes.removeByRecipeName("projecte:conversions/dm_block_deconstruct");
recipes.removeByRecipeName("projecte:conversions/gold_to_diamond");
recipes.removeByRecipeName("projecte:conversions/emerald_to_diamond");
recipes.removeByRecipeName("projecte:conversions/iron_to_gold");
recipes.removeByRecipeName("projecte:conversions/iron_to_ender_pearl");
recipes.removeByRecipeName("projecte:conversions/diamond_to_iron");
recipes.removeByRecipeName("projecte:conversions/gold_to_iron");
recipes.removeByRecipeName("projecte:conversions/diamond_to_emerald");


# Add
recipes.addShaped(<projecte:item.pe_rm_katar>, [[<projecte:item.pe_matter:1>, <projecte:item.pe_rm_sword>, <projecte:item.pe_matter:1>],[<projecte:item.pe_rm_axe>, <projecte:item.pe_matter:1>, <projecte:item.pe_rm_shears>], [<projecte:item.pe_matter:1>, <projecte:item.pe_rm_hoe>, <projecte:item.pe_matter:1>]]);
recipes.addShaped(<projecte:item.pe_rm_morning_star>, [[<projecte:item.pe_matter:1>, <projecte:item.pe_matter:1>, <projecte:item.pe_matter:1>],[<projecte:item.pe_rm_pick>, <projecte:item.pe_rm_shovel>, <projecte:item.pe_rm_hammer>], [<projecte:item.pe_matter:1>, <projecte:item.pe_matter:1>, <projecte:item.pe_matter:1>]]);
recipes.addShapeless(<projecte:item.pe_rm_hammer>, [<projecte:item.pe_dm_hammer>,<projecte:item.pe_matter:1>,<projecte:item.pe_matter:1>]);
recipes.addShapeless(<projecte:item.pe_rm_shears>, [<projecte:item.pe_dm_shears>,<projecte:item.pe_matter:1>]);
recipes.addShapeless(<projecte:item.pe_rm_hoe>, [<projecte:item.pe_dm_hoe>,<projecte:item.pe_matter:1>,<projecte:item.pe_matter:1>]);
recipes.addShapeless(<projecte:item.pe_rm_sword>, [<projecte:item.pe_dm_sword>,<projecte:item.pe_matter:1>,<projecte:item.pe_matter:1>]);
recipes.addShapeless(<projecte:item.pe_rm_shovel>, [<projecte:item.pe_dm_shovel>,<projecte:item.pe_matter:1>]);
recipes.addShapeless(<projecte:item.pe_rm_axe>, [<projecte:item.pe_dm_axe>,<projecte:item.pe_matter:1>,<projecte:item.pe_matter:1>,<projecte:item.pe_matter:1>]);
recipes.addShapeless(<projecte:item.pe_rm_pick>, [<projecte:item.pe_dm_pick>,<projecte:item.pe_matter:1>,<projecte:item.pe_matter:1>,<projecte:item.pe_matter:1>]);
recipes.addShaped(<projecte:item.pe_dm_hammer>, [[<projecte:item.pe_matter>, <jaopca:item_stickdiamond>, <projecte:item.pe_matter>],[null, <jaopca:item_stickdiamond>, null], [null, <jaopca:item_stickdiamond>, null]]);
recipes.addShaped(<projecte:item.pe_dm_shears>, [[<projecte:item.pe_matter>],[<thermalfoundation:material:26>, <projecte:item.pe_matter>]]);
recipes.addShaped(<projecte:item.pe_dm_hoe>, [[<projecte:item.pe_matter>, <projecte:item.pe_matter>],[null, <jaopca:item_stickdiamond>], [null, <jaopca:item_stickdiamond>]]);
recipes.addShaped(<projecte:item.pe_dm_sword>, [[<projecte:item.pe_matter>],[<projecte:item.pe_matter>], [<jaopca:item_stickdiamond>]]);
recipes.addShaped(<projecte:item.pe_dm_shovel>, [[<projecte:item.pe_matter>],[<jaopca:item_stickdiamond>], [<jaopca:item_stickdiamond>]]);
recipes.addShaped(<projecte:item.pe_dm_axe>, [[<projecte:item.pe_matter>, <projecte:item.pe_matter>],[<projecte:item.pe_matter>, <jaopca:item_stickdiamond>], [null, <jaopca:item_stickdiamond>]]);
recipes.addShaped(<projecte:item.pe_dm_pick>, [[<projecte:item.pe_matter>, <projecte:item.pe_matter>, <projecte:item.pe_matter>],[null, <jaopca:item_stickdiamond>, null], [null, <jaopca:item_stickdiamond>, null]]);
recipes.addShaped(<projecte:interdiction_torch>, [[<projecte:item.pe_philosophers_stone>],[<jaopca:item_stickdiamond>]]);
recipes.addShaped(<projecte:dm_pedestal>, [[null, <projecte:matter_block>, null],[null, <projecte:matter_block>, null], [<projecte:matter_block>, <projecte:matter_block>, <projecte:matter_block>]]);
recipes.addShapeless(<projecte:transmutation_table>, [<projecte:item.pe_transmutation_tablet>]);
recipes.addShapeless(<projecte:item.pe_transmutation_tablet>, [<projecte:transmutation_table>]);
recipes.addShaped(<projecte:alchemical_chest>, [[<tp:hardened_stone>, <tp:hardened_stone>, <tp:hardened_stone>],[<tp:hardened_stone>, <projecte:item.pe_covalence_dust:2>, <tp:hardened_stone>], [<tp:hardened_stone>, <tp:hardened_stone>, <tp:hardened_stone>]]);
recipes.addShapeless(<projecte:item.pe_tome>, [<biomesoplenty:earth>]);

print("---initialized recipes/projecte.zs---");