#priority 5000
import mods.immersiveengineering.Crusher;

print("---loading immersiveengineering_ores.zs---");

# Remove
Crusher.removeRecipesForInput(<biomesoplenty:gem_ore:1>);
Crusher.removeRecipesForInput(<biomesoplenty:gem_ore:2>);
Crusher.removeRecipesForInput(<biomesoplenty:gem_ore:3>);
Crusher.removeRecipesForInput(<biomesoplenty:gem_ore:4>);
Crusher.removeRecipesForInput(<biomesoplenty:gem_ore:5>);
Crusher.removeRecipesForInput(<biomesoplenty:gem_ore:6>);
Crusher.removeRecipesForInput(<biomesoplenty:gem_ore:7>);
Crusher.removeRecipesForInput(<biomesoplenty:gem_ore>);
Crusher.removeRecipesForInput(<draconicevolution:draconium_ore:1>);
Crusher.removeRecipesForInput(<draconicevolution:draconium_ore:2>);
Crusher.removeRecipesForInput(<futuremc:ancient_debris>);
Crusher.removeRecipesForInput(<minecraft:coal_ore>);
Crusher.removeRecipesForInput(<minecraft:diamond_ore>);
Crusher.removeRecipesForInput(<minecraft:emerald_ore>);
Crusher.removeRecipesForInput(<minecraft:gold_ore>);
Crusher.removeRecipesForInput(<minecraft:iron_ore>);
Crusher.removeRecipesForInput(<minecraft:lapis_ore>);
Crusher.removeRecipesForInput(<minecraft:quartz_ore>);
Crusher.removeRecipesForInput(<minecraft:redstone_ore>);
Crusher.removeRecipesForInput(<quark:biotite_ore>);
Crusher.removeRecipesForInput(<rftools:dimensional_shard_ore>);
Crusher.removeRecipesForInput(<rftools:dimensional_shard_ore:1>);
Crusher.removeRecipesForInput(<rftools:dimensional_shard_ore:2>);
Crusher.removeRecipesForInput(<thermalfoundation:ore_fluid:1>);
Crusher.removeRecipesForInput(<thermalfoundation:ore_fluid:2>);
Crusher.removeRecipesForInput(<thermalfoundation:ore_fluid:3>);
Crusher.removeRecipesForInput(<thermalfoundation:ore_fluid:4>);
Crusher.removeRecipesForInput(<thermalfoundation:ore_fluid:5>);
Crusher.removeRecipesForInput(<thermalfoundation:ore_fluid>);
Crusher.removeRecipesForInput(<tp:ender_ore>);
Crusher.removeRecipesForInput(<zcontent:aluminum_ore>);
Crusher.removeRecipesForInput(<zcontent:ardite_ore>);
Crusher.removeRecipesForInput(<zcontent:cobalt_ore>);
Crusher.removeRecipesForInput(<zcontent:copper_ore>);
Crusher.removeRecipesForInput(<zcontent:iridium_ore>);
Crusher.removeRecipesForInput(<zcontent:lead_ore>);
Crusher.removeRecipesForInput(<zcontent:meteor_block>);
Crusher.removeRecipesForInput(<zcontent:mithril_ore>);
Crusher.removeRecipesForInput(<zcontent:nickel_ore>);
Crusher.removeRecipesForInput(<zcontent:platinum_ore>);
Crusher.removeRecipesForInput(<zcontent:silver_ore>);
Crusher.removeRecipesForInput(<zcontent:tin_ore>);
Crusher.removeRecipesForInput(<zcontent:titanium_ore>);
Crusher.removeRecipesForInput(<zcontent:uranium_ore>);

# Add
Crusher.addRecipe(<biomesoplenty:gem:1> * 3, <biomesoplenty:gem_ore:1>, 4000);
Crusher.addRecipe(<biomesoplenty:gem:2> * 3, <biomesoplenty:gem_ore:2>, 4000);
Crusher.addRecipe(<biomesoplenty:gem:3> * 3, <biomesoplenty:gem_ore:3>, 4000);
Crusher.addRecipe(<biomesoplenty:gem:4> * 3, <biomesoplenty:gem_ore:4>, 4000);
Crusher.addRecipe(<biomesoplenty:gem:5> * 3, <biomesoplenty:gem_ore:5>, 4000);
Crusher.addRecipe(<biomesoplenty:gem:6> * 3, <biomesoplenty:gem_ore:6>, 4000);
Crusher.addRecipe(<biomesoplenty:gem:7> * 3, <biomesoplenty:gem_ore:7>, 4000);
Crusher.addRecipe(<biomesoplenty:gem> * 3, <biomesoplenty:gem_ore>, 4000);
Crusher.addRecipe(<draconicevolution:draconium_dust> * 8, <draconicevolution:draconium_ore:1>, 4000);
Crusher.addRecipe(<draconicevolution:draconium_dust> * 8, <draconicevolution:draconium_ore:2>, 4000);
Crusher.addRecipe(<minecraft:coal> * 3, <minecraft:coal_ore>, 4000, <thermalfoundation:material:768>, 0.25);
Crusher.addRecipe(<minecraft:diamond> * 3, <minecraft:diamond_ore>, 4000);
Crusher.addRecipe(<minecraft:emerald> * 3, <minecraft:emerald_ore>, 4000);
Crusher.addRecipe(<thermalfoundation:material:1> * 2, <minecraft:gold_ore>, 4000, <thermalfoundation:material:866>, 0.10);
Crusher.addRecipe(<thermalfoundation:material> * 2, <minecraft:iron_ore>, 4000, <thermalfoundation:material:69>, 0.10);
Crusher.addRecipe(<minecraft:dye:4> * 10, <minecraft:lapis_ore>, 4000, <thermalfoundation:material:771>, 0.20);
Crusher.addRecipe(<minecraft:quartz> * 3, <minecraft:quartz_ore>, 4000, <thermalfoundation:material:771>, 0.15);
Crusher.addRecipe(<minecraft:redstone> * 6, <minecraft:redstone_ore>, 4000, <thermalfoundation:material:866>, 0.25);
Crusher.addRecipe(<quark:biotite> * 3, <quark:biotite_ore>, 4000, <minecraft:ender_pearl>, 0.5);
Crusher.addRecipe(<rftools:dimensional_shard> * 8, <rftools:dimensional_shard_ore>, 4000);
Crusher.addRecipe(<rftools:dimensional_shard> * 8, <rftools:dimensional_shard_ore:1>, 4000);
Crusher.addRecipe(<rftools:dimensional_shard> * 8, <rftools:dimensional_shard_ore:2>, 4000);
Crusher.addRecipe(<thermalfoundation:material:892> * 3, <thermalfoundation:ore_fluid:1>, 4000, <minecraft:flint>, 0.50);
Crusher.addRecipe(<thermalfoundation:material:893> * 3, <thermalfoundation:ore_fluid:2>, 4000, <thermalfoundation:material:866>, 0.50);
Crusher.addRecipe(<thermalfoundation:material:894> * 3, <thermalfoundation:ore_fluid:3>, 4000, <thermalfoundation:material:771>, 0.30);
Crusher.addRecipe(<thermalfoundation:material:895> * 3, <thermalfoundation:ore_fluid:4>, 4000);
Crusher.addRecipe(<thermalfoundation:material:892> * 3, <thermalfoundation:ore_fluid:5>, 4000, <thermalfoundation:material:833>, 0.50);
Crusher.addRecipe(<thermalfoundation:material:892> * 3, <thermalfoundation:ore_fluid>, 4000, <thermalfoundation:material:833>, 0.50);
Crusher.addRecipe(<tp:ender_dust> * 8, <tp:ender_ore>, 4000);
Crusher.addRecipe(<thermalfoundation:material:68> * 2, <zcontent:aluminum_ore>, 4000);
Crusher.addRecipe(<jaopca:item_dustardite> * 2, <zcontent:ardite_ore>, 4000, <thermalfoundation:material:1>, 0.10);
Crusher.addRecipe(<jaopca:item_dustcobalt> * 2, <zcontent:cobalt_ore>, 4000, <thermalfoundation:material>, 0.10);
Crusher.addRecipe(<thermalfoundation:material:64> * 2, <zcontent:copper_ore>, 4000, <thermalfoundation:material:1>, 0.10);
Crusher.addRecipe(<thermalfoundation:material:71> * 2, <zcontent:iridium_ore>, 4000, <thermalfoundation:material:70>, 0.10);
Crusher.addRecipe(<thermalfoundation:material:67> * 2, <zcontent:lead_ore>, 4000, <thermalfoundation:material:66>, 0.10);
Crusher.addRecipe(<zcontent:meteor_dust>, <zcontent:meteor_block>, 4000);
Crusher.addRecipe(<thermalfoundation:material:72> * 2, <zcontent:mithril_ore>, 4000, <thermalfoundation:material:1>, 0.10);
Crusher.addRecipe(<thermalfoundation:material:69> * 2, <zcontent:nickel_ore>, 4000, <thermalfoundation:material:70>, 0.10);
Crusher.addRecipe(<thermalfoundation:material:70> * 2, <zcontent:platinum_ore>, 4000, <thermalfoundation:material:71>, 0.10);
Crusher.addRecipe(<thermalfoundation:material:66> * 2, <zcontent:silver_ore>, 4000, <thermalfoundation:material:67>, 0.10);
Crusher.addRecipe(<thermalfoundation:material:65> * 2, <zcontent:tin_ore>, 4000, <thermalfoundation:material>, 0.10);
Crusher.addRecipe(<jaopca:item_dusttitanium> * 2, <zcontent:titanium_ore>, 4000, <thermalfoundation:material>, 0.10);
Crusher.addRecipe(<immersiveengineering:metal:14> * 2, <zcontent:uranium_ore>, 4000, <thermalfoundation:material:67>, 0.10);

print("---initialized immersiveengineering_ores.zs---");